### ISSUE TITLE
Changes/Stream API

### ISSUE THREAD

**Issue by zeroware** [techfort/LokiJS#13]
Do you plan to add a changes event feature like the CouchDB change API ?

**Comment by dragantl** [comment]
The Changes API currently implemented is a great feature for syncing changes to the db at times when the API is invoked. However, the API does not push/emit any events to possible subscribers. Is this on the table to implement at any point in time? That is, something similar that @wxygeek mentioned in the post above?

There are many scenarios under which this is helpful. If application has a reasonable code separation, certain components that encapsulate collections are not aware of one another. However, actions on one can be performed to affect the other. This can be seen in a simple `favoriting` feature of something. It would be great to have the ability to sign up and listen for a change event in order to refetch or rerender the data.
