### ISSUE TITLE
find and findOne not working as expected

### ISSUE THREAD

**Issue by davidraviv** [techfort/LokiJS#150]
when constructing a query with multiple conditions it seems that the search ensure at least one of the condition applies instead of ensuring all of the conditions applies.

e.g.:

find( {
   key1: 1,   key2: 2
});

will return the following object:
{
    key:1 , key2:3
}

**Comment by techfort** [comment]
hi @davidraviv  - this is one aspect that needs to be documented more explicitly, as it has caused some confusion. Can you try the following syntax:
`find({key1: 1}, { key2: 2});`

**Comment by obeliskos** [comment]
It's actually more verbose than that atm, try : 
```javascript
find({'$and': [{'key1':1}, {'key2':2}]});
```

**Comment by techfort** [comment]
thanks @obeliskos - what am i like when i've got a flu...

**Comment by molszanski** [comment]
Oh this doesn't work anymore. Multi-property query seems to be broken atm. 
![stuff](https://cloud.githubusercontent.com/assets/1117009/11326048/f4752814-915e-11e5-9940-369e1ef16c26.png)

**Comment by obeliskos** [comment]
yea your top query is (and has always been) in an unsupported format.

your bottom query is formatted correctly, and as far as I can tell its returning the correct result (empty array).

**Comment by molszanski** [comment]
IMO it is worth adding with a red bold font that this type of queries is not supported. I somehow expected that, giving the fact that sorting and mongo-style stuff ($in like) is supported. 

Oh, I should have included an object with '111a6' into the screenshot. I am pretty sure that was as an element 0 or 1. Would not be able to reproduce, because I've completely removed loki from deps :(
