### ISSUE TITLE
Lowercase constructor in the browser version?

### ISSUE THREAD

**Issue by retorquere** [techfort/LokiJS#156]
The constructor for the in-browser version is `loki` rather than `Loki`. Is this intentional?

**Comment by techfort** [comment]
yes, as that's how it is documented on the website. Originally Loki was
aimed at node/cordova (even though I kept it browser friendly), under which
constructors are normally lower case (i.e. var loki = require('lokijs')).
It stayed like that since those days (nearly 2 years ago) and it got
documented like that on the site, so I'm inclined to leave it like that.
But yeah - i can see how constructors are traditionally Upper case.

**Comment by retorquere** [comment]
OK, no issue
