### ISSUE TITLE
Using $regex in case-insensitive mode

### ISSUE THREAD

**Issue by countermeasure** [techfort/LokiJS#159]
I'd like to be able to use `$regex` in case-insensitive mode.

I can get it working case-sensitive like so:
```
find({"myField":{"$regex":"myfieldvalue"}})
```

I'd like to be able to use something like the `/.../i` pattern to make it case-insensitive, for example:
```
find({"myField":{"$regex":"/myfieldvalue/i"}})
```

That doesn't seem to work though. Any thoughts on a work-around to get a case-insensitive search/regex?

Cheers!

**Comment by techfort** [comment]
This doesn't work because the regex is instantiated with the RegExp object syntax, and no options are passed into it.
I agree that case-insensitive should be the default behaviour, so changing this line 
`if (operator === '$regex') value = new RegExp(value);` 
to
if (operator === '$regex') value = new RegExp(value, 'i');

should do the trick.
Will try to include it in 1.3

**Comment by countermeasure** [comment]
Actually, after seeing your answer, I realise that I wasn't understanding that LokiJS either wants the regex without quotes, or wants a `RegExp` object. I've just sent a PR for the docs site to clarify this.

I've now got a case insensitive regex working with this snippet so that I don't have to change any LokiJS code:

```javascript
var searchRegex = new RegExp(searchString, 'i');
collection.find({'myField': {'$regex': searchRegex}});
```
Maybe better not to make `$regex` case-insensitive by default so that people have complete control over their regex behaviour without any default behaviour which could cause confusion?

Thanks for your help!

**Comment by techfort** [comment]
Yep, makes sense. Thanks for PR!
