### ISSUE TITLE
Implement Lamport timestamps

### ISSUE THREAD

**Issue by techfort** [techfort/LokiJS#16]
Timestamp logic for distributed architecture.

**Comment by seriousme** [comment]
This might help ;-)
http://swarmjs.github.io/articles/lamport/

**Comment by techfort** [comment]
Been discussing peer-device syncrhonization for a truly distributed db, this would come in really handy.

**Comment by RnbWd** [comment]
He introduced me to the concept - it turns out some well known libraries already use these under the hood (maybe not in JS though). I've discovered a few libs that implement vector clocks / lamport signatures  in JS - 

https://github.com/dominictarr/lamport

https://github.com/mixu/vectorclock 

https://github.com/AWinterman/vector-clock

Substack / Macintosh have also been prolific recently

https://github.com/mafintosh/merkle-dag

https://github.com/substack/hash-exchange

https://github.com/substack/fwdb

https://github.com/substack/forkdb

https://github.com/substack/wikidb

Put together in the browser here: https://github.com/substack/shipboard

**Comment by techfort** [comment]
closing this as it has probably become a bit irrelevant. May be useful on server wrappers.
