### ISSUE TITLE
Demo Still broken

### ISSUE THREAD

**Issue by DrMabuse23** [techfort/LokiJS#168]
Hi i try out the demo and its still broken
`````
Cannot read property '$loki' of undefinedCollection.remove @ lokijs.js:3113
2lokijs.js:3113 
````

**Comment by techfort** [comment]
will look into it asap, could be with file renaming or something trivial like that. Thanks for reporting it!

**Comment by apo-j** [comment]
I found the bug in this line : self.constraints.unique[key].remove(doc); (line 3316) in the function remove.
If i call it like this self.constraints.unique[key].remove(doc.$loki); il works well.
This is something wrong in the KeyMap

**Comment by techfort** [comment]
@apo-j is the bug related to the broken demo? sounds more like a problem with unique index. If you want to open a separate issue and/or submit a PR go ahead!

**Comment by apo-j** [comment]
I think it's the same bug.
The problem comes from the construction of the object KeyMap. It has $loki as key and the correspondant object as  value. But when I call collection.remove(obj), inside the .constraints.unique[key].remove(doc), you used this.KeyMap[key], but the value of key here is the object passed through the collection.remove() method instead of the $loki, thus KeyMap return null.

**Comment by apo-j** [comment]
this is the method
UniqueIndex.prototype.remove = function (key) {
      var obj = this.keyMap[key];
      this.keyMap[key] = undefined;
      this.lokiMap[obj.$loki] = undefined;
    };

**Comment by techfort** [comment]
Ok thanks @apo-j - i should be able to get on this tonight (GMT)

**Comment by kberryman** [comment]
I think I fixed this issue with the pull request for issue #177 I didn't realize this was the same issue till after the PR.

**Comment by techfort** [comment]
thanks @kberryman !

**Comment by kberryman** [comment]
no problem.  It was easy to fix once @Whoaa512 pointed out it was due to the unique indexes on a collection.  The issue was because the remove function for UniqueIndex takes the key value as the parameter to remove the object.  The collection.remove function takes the object itself.  It might be worth thinking about changing the UniqueIndex.remove function to take the object instead of the key value to make it  consistent with collection.remove.  I don't think it would be a big  deal since my guess is that UniqueIndex.remove is only an internal function.  I can't see a reason for an end user to want to remove an object from an index if it is still in the collection.

**Comment by techfort** [comment]
It definitely is worth considering! Meanwhile thanks for all your work, hope Loki is making your life a bit easier.
