### ISSUE TITLE
Don't expose global for IndexedDB adapter

### ISSUE THREAD

**Issue by 0x8890** [techfort/LokiJS#173]
https://github.com/techfort/LokiJS/blob/master/src/loki-indexed-adapter.js#L51

Modular approach would be much preferred here.

**Comment by techfort** [comment]
hey there - thanks for flagging this. Will include it in 1.4.

**Comment by obeliskos** [comment]
Now that es6 has been released and there is an 'official' (albeit not yet fully supported) way of handling modules, should that be the format to support?  

If you have thoughts or pull request feel free to chime in... otherwise I might get philosophical on this one at least while researching es6 changes.

**Comment by daliwali** [comment]
I think the same thing could be applied for this package in general, use ES6 modules. 

for this you could use the default export:

```js
export default IndexedAdapter
```

then a build step would be required. I would recommend browserify + babelify.

**Comment by obeliskos** [comment]
I believe we adopted a commonjs amd wrapper to that adapter, so I will close this.  If you feel otherwise, feel free to reopen/elaborate.  Thanks
