### ISSUE TITLE
Module is undefined in lokijs-indexed-adapter

### ISSUE THREAD

**Issue by tlkiong** [techfort/LokiJS#189]
568     if(module && module.exports) {
      569       module.exports = IndexedAdapter; 
      570     }

The above code is screaming the error. I am building a cordova app. This error came about when I upgraded LokiJS from 1.3.4 to the current version of 1.3.7. (It broke my app)
V1.3.4 didn't have these lines.

**Comment by techfort** [comment]
Thank you very much for reporting this. Actually @tlkiong if i can be so bold as to take advantage of your generosity, would you have a PR for this which supports `module.exports` but doesn't throw the `module is undefined` error? it will be a couple of days before i can tackle this properly otherwise as i'm up the walls with other projects

**Comment by obeliskos** [comment]
Probably just a simple typeof check would do.  Something like : 
```javascript
if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
  module.exports = IndexedAdapter;
}
```
If no one else does, I can change that later tonight.

**Comment by techfort** [comment]
hey @obeliskos - problem with this kind of check is that the second condition will always be checked, and if `module` is undefined then `module.exports` throws an error because it tries to retrieve a property of an undefined. 
So either we do the same trick as in lokijs.js 
```
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD
    define([], factory);
  } else if (typeof exports === 'object') {
    // CommonJS
    module.exports = factory();
  } else {
    // Browser globals
    root.loki = factory();
  }
}(this, function () {

  return (function () {
  // ... etc.
```
or we do nested IFs (if module then if module.exports).

**Comment by obeliskos** [comment]
I think it would use short-circuit Boolean evaluation.  Seemed to work for me in a browser...

Maybe others can test or suggest.

**Comment by techfort** [comment]
@obeliskos you know, the problem is that i really need to give some TLC to
LokiJS in Corodva. There are more and more requests for a ready-made fs
adapter for cordova and this breaks in Cordova (if i get this right).
Only today i discovered IndexedDB is not supported in Cordova for iOS so
it's either localStorage or fs, and most people wouldn't feel very
comfortable with localStorage

**Comment by obeliskos** [comment]
Ok, I'll let you figure out how you want to handle cordova.  This does seem to fix normal browser use in non-commonjs environments though.

**Comment by techfort** [comment]
cool - go ahead and commit that so because having only cordova broken is
better than everything broken :)

**Comment by tlkiong** [comment]
Thanks guys.
I did modified my code while waiting for a response as I am not sure is it by design or not.
So, I guess I'll wait for the latest changes before pulling again. Thanks again.
*Good to hear that indexedDD is not supported for iOS.
