### ISSUE TITLE
Collections' Constraints: null

### ISSUE THREAD

**Issue by tlkiong** [techfort/LokiJS#190]
On database save, the constraints is set to null for all collection.

     532     /**
     533     * serializeReplacer - used to prevent certain properties from being serialized
     534     *
     535     */
     536     Loki.prototype.serializeReplacer = function (key, value) {
     537       switch (key) {
     538       case 'autosaveHandle':
     539       case 'persistenceAdapter':
     540       case 'constraints':
     541         return null;
     542       default:
     543         return value;
     544       }
     545     };
>The above code is under lokijs.js

This means that my constraints of unique-ness will not persist in the database.
I am wondering whether this is by design or not.

If it is, then perhaps there is a bug on loadCollection where by we should be able to reinject the contraints (or else uniqueness constraint will no longer be present)

else, the constraint should not be set to null when we want to serialize the database

As of this writing, I have just only identified this section that made 'constraints' to null. I notice after a while (I am presuming on save DB but haven't identified yet),

constraints.unique = {}
constraints.exact = {}

**Comment by techfort** [comment]
@tlkiong this is by design, unique index uses object references, so serializing would cause a JSON.stringify of the referenced objects - so when you do a JSON.parse you lost that reference.
I actually put it in the docs as an important note - but if you have a better option i'm all ears, i'd like to be able to persist uniqueIndex too.

**Comment by tlkiong** [comment]
@techfort, I couldn't find it in the docs after going through the [site](http://lokijs.org/) and the [wiki](https://github.com/techfort/LokiJS/wiki/). Weird.

Either way, I have to dig through the source code to figure this out. Thanks for the reply :)

On a side note, I would like to ask, if I want to contribute to help with the docs (make it more beginner friendly), how should I go about it? This is because when I chose LokiJS cause its JS and its an fast in-memory db. But implementing it with not enough documentation is a pain. I have to go through the source codes to see what is currently possible and what is not.

**Comment by obeliskos** [comment]
In theory, in the serializeReplacer, instead of just returning null for 'constraints' lokijs could clone or recreate the contraints object hierarchy without the duplicate objects and then on load database, check for their existence and rebuild them.  That would avoid duplicating objects yet retain enough info about the uniqueindex column names to regenerate on load.

**Comment by obeliskos** [comment]
As of recent commit, Unique indexes will now be automatically regenerate across db save / load cycles.

**Comment by tlkiong** [comment]
Just went through the codes. It seems to be perfect. Will check it out.
Btw, is it in the latest npm?

**Comment by obeliskos** [comment]
Not yet, its currently only available in main github site (both full and minified versions now). Once @techfort decides to bump version he will publish to npm.

**Comment by tlkiong** [comment]
I see. Thanks for the heads up @obeliskos
