### ISSUE TITLE
Uncaught Error: NOT_FOUND_ERR: DOM IDBDatabase Exception 3

### ISSUE THREAD

**Issue by cosmith** [techfort/LokiJS#196]
Hi,

I'm seeing this error in my Flurry logs when using Loki with the IndexedDB adapter:

```
Uncaught Error: NOT_FOUND_ERR: DOM IDBDatabase Exception 3
```

I found this SO question http://stackoverflow.com/questions/9872806/dom-idbdatabase-exception-3-when-using-indexeddb that seems to give a solution, but I'm not sure where it could happen in the adapter code. I thought adding a try/catch block around the adapter instantiation would fix it but no luck.

The error is happening only on certain devices (I'm using Cordova), most notably the Samsung Galaxy S III.

This is my code at the moment:

```js
    static _getAdapter() {
        var adapter = null, dbname = "loki";

        try {
            adapter = new LokiIndexedAdapter(dbname);
            if (!adapter.checkAvailability()) {
                adapter = new LokiCordovaFSAdapter({"prefix": dbname});
            }
        }
        catch (e) {
            console.warn("[Database]", e);
            adapter = new LokiCordovaFSAdapter({"prefix": dbname});
        }

        return adapter;
    }
```

I'm not sure the error is in that code though... all I get is "error in loki-indexed-adapter.min.js at line 1". Maybe I should use the unminified version to get more info.

I'm going to keep investigating, but if anyone has an idea or has seen this before...

**Comment by techfort** [comment]
hey @cosmith is this the error that iOS throws because it does not support
indexedDB?
maybe you could avoid trying to create the indexed adapter at all if the
agent is safari?
boy - Apple has become like IE 8.

**Comment by obeliskos** [comment]
Works on IOS, I think he's running into android compatibility.

This link shows you need android 4.4 or higher browser to use indexeddb?  That seems rather late arrival for old feature.

http://caniuse.com/#feat=indexeddb 

But yea if you can run unminified version, you can let me know the line number.

**Comment by obeliskos** [comment]
If that is the case and you just have to work with it, you might look into a polyfill (like this one?) since those earlier android browsers probably -do- support websql : 

https://github.com/axemclion/IndexedDBShim

**Comment by cosmith** [comment]
@techfort @obeliskos yes it's on Android, I hadn't realized I needed 4.4. I'm going to test it in the emulator and report back. I think I should probably use the filesystem adapter on all devices, looks like I'll have better support.

**Comment by techfort** [comment]
@cosmith @obeliskos that's actually very good to know - may be worth putting in the docs so developers don't run into similar issues.

**Comment by obeliskos** [comment]
@techfort  and @cosmith can decide on how to document this.  IndexedDB is almost ubiquitous now but in mobile arena I suppose another year or so before older android phones get upgraded.

That compatibility chart is for android native browser support, which I would guess is what cordova uses.  Another year or so and % of support would probably be much higher to warrant that as requirement.

If it were me I would probably pursue that polyfill since newer devices will support indexeddb and websql will probably be obsoleted soon?  Or if you are only storing a single database or key then I guess filesystem adapter would be fine.

If emulator tests show its there but with spotty support (maybe they only expose functionality via object named 'webkitIndexedDB' or something), let me know and I will see if it can be supported.

**Comment by techfort** [comment]
@cosmith @obeliskos I think we should probably cater for all scenarios, so include caveats in the docs and offer the shim workaround, as well as the link to @cosmith 's fs-adaptor. Personally, if the fs adaptor works well i wouldn't use anything else in cordova/phonegap because i think of it as a more universal approach (i'd do anything to banish browsers really...) but that's just me.

**Comment by cosmith** [comment]
Not sure I'd have used cordova if I had realized what a pain it was to have all those browsers to support... my plan is to move to React Native as soon as it's out anyway.

I'm using a single database so the filesystem adapter is ok, but the issue now is that I'd have to migrate all the devices that use IndexedDB to the filesystem... more potential for things to break in unexpected ways.

**Comment by cosmith** [comment]
Ok so I know where the error happens: it throws every time there's a call to `this.db.transaction(['LokiAKV'], 'readonly');` like in https://github.com/techfort/LokiJS/blob/master/src/loki-indexed-adapter.js#L347 (but not only there)

So I'm thinking of testing it like this, adding a call to `getDatabaseList()`:
```js
    static _getAdapter() {
        var adapter = null, dbname = "loki";

        try {
            adapter = new LokiIndexedAdapter(dbname);
            adapter.getDatabaseList(); // this call will break on some devices
            if (!adapter.checkAvailability()) {
                adapter = new LokiCordovaFSAdapter({"prefix": dbname});
            }
        }
        catch (e) {
            console.warn("[Database]", e);
            adapter = new LokiCordovaFSAdapter({"prefix": dbname});
        }


        return adapter;
    }
```

I'll let you know how it goes in the wild ;)

**Comment by cosmith** [comment]
`adapter.getDatabaseList()` is async so this is obviously not going to work...

**Comment by cosmith** [comment]
So I ended up removing the indexedDB adapter completely, and forcing an update for those who where using it.

**Comment by techfort** [comment]
@cosmith it's good that you resolved your problem - i'd love to know if
indexedDB is bust on cordova for android legacy devices. I suppose a note
explaining about this in the docs will at the very least provide a fair
warning

**Comment by techfort** [comment]
This seems stable so I'm closing.
