### ISSUE TITLE
Large databases and memory footprint

### ISSUE THREAD

**Issue by anri-asaturov** [techfort/LokiJS#197]
I have a question related to memory footprint when using large databases on mobile.
Is it possible to limit the operating(loaded into RAM) part of data, in case I know exactly which part of my data i'm going to use next? Or maybe limit amount of RAM cache while trading off the performance?  

I understand that for desktop it's rarely a problem, but for mobile apps you don't really want to have the whole database in memory all the time, even if it is no more then a few hundreds of megabytes.

btw, I'm considering using LokiJS for http://peerio.com apps.

**Comment by techfort** [comment]
@anri-asaturov: short answer: not yet. 

I completely understand the problem. This is in fact a much larger issue than just mobile, and i have been toying with numerous solutions so far. The main rationale for adopting the approach you mention was - for me - so that i can use LokiJS as a MRU or LFU cache front for a large traditional DB (of any kind really, i have experiments with LokiJS writing to MySQL, RethinkDB and MongoDB), which would be like a super-powered Redis, you know - fast, in memory but also with queries and dynamic views.
The results are really encouraging but I haven't managed to develop something that would allow only a portion of the data to be loaded.
peerio looks awesome, I'd be really happy to see LokiJS implemented in something like that. If you have any ideas with regards to the implementation of this mechanism I am all ears.

**Comment by anri-asaturov** [comment]
Ok, thanks, I think I'll go ahead and implement storage with LokiJS as it is now and then see if I can be useful on this matter.

First thing that come to mind (and will work in my case), grouping data in separate databases by date/amount of documents. This much i can do with features LokiJs currently provides I think. It would slow down search a bit, if, for instance, user wants to do a global search in his messages, but still good enough.

**Comment by techfort** [comment]
that's actually pretty smart. I will keep going on this anyway and report when i have more definite results.
