### ISSUE TITLE
Implement transactions

### ISSUE THREAD

**Issue by techfort** [techfort/LokiJS#2]
Implement some form of transaction that caches the collection's state and rolls back to it if something fails during the operation.

**Comment by alexmipego** [comment]
This would be very useful. I currently have a service that I use to sync data with my current phonegap db solution. One of the design choices was to implement transactions so that the "sync server" doesn't need to worry about conflicts among other useful bits. I'm looking into lokijs and would love to see this.

**Comment by techfort** [comment]
Hi Alex, transactions are actually partially implemented, although they are under revision, in that the whole dataset is cached and restored in case of errors during the operation. Having said that, Loki records also contain a meta object which contains a *created* timestamp, a last update timestamp and a revision number (the number of times the object has been changed) so you can apply a last-write-wins type of logic. If this is not sufficient and you want to explain your use case in more detail please do, either here or drop me a mail.

**Comment by xeoshow** [comment]
Hello,
Since the last post of this thread is 3 years ago, just would like to know how about the transaction support for lokiJS now?

Thanks a lot!

Best regards, Jason
