### ISSUE TITLE
Best practice for error handling

### ISSUE THREAD

**Issue by acanimal** [techfort/LokiJS#227]
Hi, I discover this awesome project a couple of days ago.
Is there any good practices to handle errors on insert, update, delete operations or `try{}catch{}` is enough?

**Comment by techfort** [comment]
@acanimal hey there, thanks for the kind words!
No particular best practices, you can use try-catch, also, an 'error' event is emitted so you can attach listeners to the event on the collection to take action. Loki be with you.

**Comment by kaasdude** [comment]
Hi all,

I got a similar question about how to handle potential errors thrown by LokiJS.
I can't seem to find this in the documentation, could be mistaken of course ;)

Currently in trying to get more code covered in the unit tests (very important), I dearly want to simulate an error for example in this piece of code:
```
/**
 * This callback with an optional LokiJS error?
 * @callback LokiJSGibbonAdapter~removeUser
 * @param {Error} [error] - This could contain an error emitted by LokiJS
 */

/**
 * Remove a user from the user collection
 * @param {object} user
 * @param {LokiJSGibbonAdapter~removeUser} callback
 */
LokiJSGibbonAdapter.prototype.removeUser = function (user, callback) {
    try {
        this.userCollection.findAndRemove({name: user.name});
    } catch (error) {
        return callback(error);
    }
    callback();
};

```
I'm used to predict errors in code a bit, because sometimes one is able to handle the error and even act upon it if possible.

Thanks, Cheers!

:star2: Kudo's LokiJS! :star2:

**Comment by obeliskos** [comment]
I'm not sure if anything in that code path is extremely sensitive to exceptions but I did notice unintended behavior when passing other than a filter object.... like : 

```javascript
users.findAndRemove(1);
```

The 'find' part sees no valid filter so it treats it like find() which returns all documents, then summarily removes all of them.  

Have you ever encountered an exception from this method?  Or perhaps just unexpected behavior with no return value to guage whether it worked?  'Exception-wise' we are really just scanning and manipulating an array.

That method ultimately depends on collection.remove() which can raise an error of passed documents which don't exist in the collection, but since we are feeding it results of a query on that collection that shouldn't happen.

Sorry I don't know what your looking for I suppose you could override that proto method and raise an exception yourself :P

**Comment by kaasdude** [comment]
Yes, for example, if one reads the documentation about `JSON.parse()`, here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse
The documentation states, it's could throw an error, so eventually a developer knows in advance to wrap a try catch around it.

But if this method would not throw any error, an "efficient/lazy" developer doesn't wrap this statement with a try catch, because this eats resources. We don't put try catches around each synchronous method, only when a potential error could be thrown by the code.

Me as a "lazy" developer, would like to know if synchronous methods could throw an error in advance by reading the documentation.

_Long story short:_

Which methods of LokiJS could throw an Error?

**For example:**
A small snippet of your code, could use the `@throws {Error}` jsdoc annotations?

I would suggest to add: `@throws {TypeError} when `doc` is not an object or is equal to null` to be reflect in the generated jsdocs for everybody to see, which errors could be thrown.

```
    /**
     * Adds object(s) to collection, ensure object(s) have meta properties, clone it if necessary, etc.
     * @param {(object|array)} doc - the document (or array of documents) to be inserted
     * @returns {(object|array)} document or documents inserted
     * @memberof Collection
     */
    Collection.prototype.insert = function (doc) {
      if (!Array.isArray(doc)) {
        return this.insertOne(doc);
      }

      // holder to the clone of the object inserted if collections is set to clone objects
      var obj;
      var results = [];

      this.emit('pre-insert', doc);
      for (var i = 0, len = doc.length; i < len; i++) {
        obj = this.insertOne(doc[i], true);
        if (!obj) {
          return undefined;
        }
        results.push(obj);
      }
      this.emit('insert', results);
      return results.length === 1 ? results[0] : results;
    };
```

**Comment by obeliskos** [comment]
great suggestion about jsdocs, that's something we could definitely do...

we could even easily add a few of those type checks to findAndRemove.  we might throw error if you pass anything other than null or object.
