### ISSUE TITLE
Rehydrating unique index claims duplicate key

### ISSUE THREAD

**Issue by KodeAndGame** [techfort/LokiJS#232]
I had a weird issue with a database I was building. The database can be found at [this gist](https://gist.github.com/KodeAndGame/00173a20825672c81492). When I load it using the below code, I get a duplicate key error `Error: Duplicate key for property threadId: 1109852`

```
self.db = new loki(dbpath, {
        autoload: true,
        autosave: true, ,
        autosaveInterval: 10000
      })
    })
```

The stack at this error is:

```
debug> bt
#0 UniqueIndex.set lokijs.js:3927
#1 lokijs.js:3035:15
#2 Collection.ensureUniqueIndex lokijs.js:3034:17
#3 Loki.loadJSON lokijs.js:693:22
#4 lokijs.js:897:18
#5 lokijs.js:826:11
```

I'm not really sure what I did wrong but I started to use dynamic views and then kind of realized I wasn't really aware if they persisted to file properly or if they were even meant to in the first place. So I removed all of the code that used the dynamic view but not the code that built the dynamic view; I'm still early in prototyping the process of building and loading a database - thus I'm constantly rebuilding it from scratch and then loading from file. The initial load would work but a subsequent load would throw the duplicate key error. I tried diff'ing the json after the initial build and the json after the first load and found the differences here:

![image](https://cloud.githubusercontent.com/assets/1966944/10260619/444cc0da-6947-11e5-9c24-91c7061710bc.png)

The only differences were in the dynamic view I wasn't using so I removed it and everything seems to work fine now. Hope this bug report helps.

**Comment by obeliskos** [comment]
Thanks for posting that gist, made this pretty easy to reproduce.  I tried loading your database using our sandbox and I get the 'duplicate key' for property 'threadId' error.

The data in that collection ('threads') does appear to have duplicate documents.  Of the four documents in that collection, two are duplicates... so there is a clash not only with the 'threadId' property but with the $loki id as well.   I would be interested in knowing how that happened.

Only 'find' filters added to DynamicView will persist.  Your 'where' filter (since it points to a javascript function) can't be persisted, so it is cleared out when inflating.  If you wish to use 'where' filters with dynamic views, you need to reapply them manually after loading the database.

Using a text editor I was able to clear out the 'uniqueNames' property of the 'threads' collection, setting it to empty array [] and the database was able to load the dirty data and I could inspect the database using our sandbox.   

Could the data have been dirty before the unique index was first applied?  Might need some new tests for this, let me know if you know how to reproduce this.

**Comment by jpablom** [comment]
It happens because on __Collection.prototype.update = function (doc)__ ....

```
        obj = arr[0];
        Object.keys(this.constraints.unique).forEach(function (key) {
          self.constraints.unique[key].update(obj);
        });
```

but __obj__ is the __old item__

solved by:

```
        obj = arr[0];
        Object.keys(this.constraints.unique).forEach(function (key) {
          self.constraints.unique[key].update(doc);
        });
```

where __doc__ is the __updated item__

**Comment by obeliskos** [comment]
I think i may take some time to look over this since i am unfamiliar with techfort's unique index implementation here.  

I'll see if i can devise a test case to reproduce this sometime this weekend.  If you already have a test case, feel free to post it.

**Comment by obeliskos** [comment]
Ok, so I think I know what is going on here but a few other issues came up while researching this.

First, I think I found out that the current implementation of unique indexes does not act reliably if you update the property you defined the unique index on.

[Here is a loki sandbox gist which demonstrates this problem.](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/0a51279b685a6ca8e16f/raw/a89867a4a517581a653ad2cb548628869e72b12e/LokiUniqueIndexFail)

So, for now, if you define a unique index then that property should never change or else you would need to remove and (re)insert.

I might be able to hack a quick fix, but instead I think we need to look over our object referencing implementations/strategies.  Once techfort gets back I will see how he wants to handle object instancing in light of the fact that we support 'clone' objects which does not seem to work as I would expect we would want it to.

**Comment by jpablom** [comment]
something new in this ?

**Comment by obeliskos** [comment]
First off I believe this issue is either resolved or needs more complete repro error from users.  My gist did not seem to indicate an error afterall but showed other issues.

First off, if it was me, I would never update a document property marked as a unique index after it had been inserted the first time.  I would treat it like the built in $loki property and never change it.  

If you wish to update this property, you can do so.  When you call update it will update the collection.constraints.unique.  If you have an object with a unique index on ... say 'username'.  After updating that property in a document and calling update(),  I can once again insert a new document using the old username and it will return successfully.  Successfully means I get an object instance rather than (empty array?).

Where this led me is to notice how fragile this would be if you started updating uniquely indexed columns without calling update().   This led me to expand our object cloning option which I described in issue #256 and already implemented in main branch.  So either adhere to restrained 'updating' of existing unique keys or pay the performance cost associated with turning on full collection cloning to ensure that your objects and loki objects are separate object instances (forcing you to use api to update).

Again, I never really received follow up from anyone with a detailed plunk to repro this issue, if you are encountering issue other than described, feel free to provide example.

**Comment by KodeAndGame** [comment]
@obeliskos I completely agree based on your initial reply. I don't think the problem is properly stated and I don't think I provided enough information to point to the true issue. Unfortunately, I haven't had an opportunity to follow up or continue work on the project I was working on in order to provide a better issue log. I think at this point, this particular issue can be closed and once I have better information, I can open a new one.

**Comment by siberian1967** [comment]
Not sure if this is bad form (tagging onto a close item) but I am also seeing this issue and thought the context was important. Attached is my database. I am loading it using this command:

`_articles = _db.getCollection('articles').ensureUniqueIndex('href');`

With that ensureUniqueIndex on there I get the below error when reloading.

The data is inserted once and never updated. The record with href 'https://cors3.stratfor.com/analysis/ukraines-conflict-rumors-compromise-grow' is unique and the $loki ids are also unique still.

I'm a newbie with loki so might be just doing something incorrect but my data seems ok. Maybe using a URL as a unique key is bad form or something in the URL format is causing the key check to exit early?

Tracing the code it looks like ensureUniqueIndex is looping back over the database file

```
     this.data.forEach(function (obj) {
        index.set(obj);
      });
```

I watched this function
`UniqueIndex.prototype.set = function (obj) {`

Loop through the entire dataset and then get called again for the first item in the dataset.

I tested this in sandbox and got the same error using the attached db and this code:

```
logDatabase();
inspectObject(db);
_articles = db.getCollection('articles').ensureUniqueIndex('href');


Uncaught Error: Duplicate key for property href: 
https://cors3.stratfor.com/analysis/ukraines-conflict-rumors-compromise-grow 
(line 4356 col 11)


```
[data.json.zip](https://github.com/techfort/LokiJS/files/127540/data.json.zip)

```
Uncaught Error: Duplicate key for property href: https://cors3.stratfor.com/analysis/ukraines-conflict-rumors-compromise-grow
UniqueIndex.set @ lokijs.js:4252
(anonymous function) @ lokijs.js:3336
Collection.ensureUniqueIndex @ lokijs.js:3335
(anonymous function) @ article-list.js:56
loadDatabaseCallback @ lokijs.js:975
loadDatabase @ lokijs.js:931
Loki.loadDatabase @ lokijs.js:972
initDB @ article-list.js:55
(anonymous function) @ app.js:49(
anonymous function) @ ionic.bundle.js:44991
onPlatformReady @ ionic.bundle.js:2447
onWindowLoad @ ionic.bundle.js:2428
```

**Comment by siberian1967** [comment]
I also just went up a level of debug and saw that 

Collection.prototype.ensureUniqueIndex = function (field) {

Is called twice in my load scenario. I confirmed that I was not calling it twice in my code and the sandbox test validates that. This is happening farther up the chain but I'm running out of late evening debug skills and someone more qualified can probably pinpoint it faster. 

Tx!
John-

**Comment by reenan** [comment]
@obeliskos sorry to bother on an old thread, but I'm facing this issue now, could you maybe help me understand what's the problem?

- I'm using next.js to fetch large amounts of data from a headless CMS
- I use LokiJS to cache this result so I can do fast SSG on next.js side
- After `getStaticPaths` is finished, I have all my data correctly set on LokiJS
- When `getStaticProps` runs, it will reload the DB and throws a error about duplicate key:

`Error: Duplicate key for property {key}: {value}`

I've double-checked the data and all responses and it's *not* duplicated, there is a single entry per unique key but still it complains.

```
this.instance = new loki(BASE, {
  adapter: new lfsa(),
  autoload: true,
  autoloadCallback: databaseInitialize,
})
```

```
this.instance.addCollection('entries', {
  unique: ['slug'],
  indices: ['id', 'slug'],
  clone: true,
})
```
