### ISSUE TITLE
API for delete database and count

### ISSUE THREAD

**Issue by matthiasg** [techfort/LokiJS#234]
I have been looking through the docs but i couldnt find a quick way to find the number of total documents in a collection (without using where which would propably be resource intensive returning all documents or map/reduce which would also be quite unnecessarily complex).

Also i would like to be able to totally delete the entire database. Closest i could find is removeDataOnly. Is there something that clears out everything ?

**Comment by obeliskos** [comment]
We probably need an api call for this.  I'll add it once outstanding pull requests are committed.

In the meantime you can peek at the internal collection data array : 

```javascript
var collCount = coll.data.length;
```

**Comment by obeliskos** [comment]
What adapter are you using for persistence?  filesystem, local storage, indexeddb, other?  I think only our indexed db adapter supports a delete option and its not official part of interface... could possibly add that in future.

**Comment by matthiasg** [comment]
Indexeddb ... And for unit asked integration testing against that out would be quite helpful already, but we need it when people log out and want to rejoice ask locally cached data.

----- Ursprüngliche Nachricht -----
Von: "obeliskos" <notifications@github.com>
Gesendet: ‎05.‎10.‎2015 23:58
An: "techfort/LokiJS" <LokiJS@noreply.github.com>
Cc: "matthiasg" <mgt576@gmail.com>
Betreff: Re: [LokiJS] API for delete database and count (#234)

What adapter are you using for persistence? filesystem, local storage, indexeddb, other? I think only our indexed db adapter supports a delete option and its not official part of interface... could possibly add that in future.

**Comment by obeliskos** [comment]
I think there is bad translation, so maybe I misunderstood.

If you meant to delete the in memory database, we could add database method to do that.  Currently you might just recreate the database.

If you meant to delete the database on disk, we could add method to adapter interface so that a database api might be created.

Since you are using indexeddb, you could call directly to adapter to do this like : 
```javascript
myAdapter.deleteDatabase('test.db');
```

If you have question about testing adapter, I don't currently have tests for indexed db adapter.  Your own tests might substitute a different, more testable adapter for depending on your testing environment.

**Comment by matthiasg** [comment]
ok .. then in order to do what i want .. i will have to create the adapter manually first and hand this to loki instead of relying on its auto mechanism. that way i retain the adapter interface. works for me. thanks
