### ISSUE TITLE
Search in nested arrays

### ISSUE THREAD

**Issue by andrii-mob** [techfort/LokiJS#235]
Here is the document I have:

``` javascript
{
    level1: [
        {  _id:1
            level2: [
                {_id:11},
                {_id:12}
        }, {
            _id:2
            level2: [
                {_id:21},
                {_id:22}
        }
    ]
}
```

A query 
collection.find({'level1._id':2}) 
works fine, but 
collection.find({'level1.level2._id':22})
does not.
Please advise.

**Comment by obeliskos** [comment]
You need to format your example better it doesn't appear to be valid json.  

Since I can't really make out exactly what is going on with your document(s), it may tread into needing to use collection.where along with a javascript filter function instead of using collection.find.

Normally, you can search arrays using the $contains, $containsAny find ops but i'm not sure they work with objects and dot notation.  object equality usually only evaluates to true if they are the exact same object instance.

Feel free to elaborate on exact data to use and format it within a markdown code block so that indention is preserved.  

Since level2 is an array, I would assume you need to run a $contains find op on it.  But your array contains objects

**Comment by andrii-mob** [comment]
Yes, I can use collection.where 
```javascript
var result = collection.where(function(obj) {
     return obj.level1.some(function(level1) {
           return level1.level2.some(function(level2) {
                  return level2._id == id; // id - an ID we're searching for
            });
     });
});
```
But this seems to be too many lines of code for such simple task.
(To give a little background: I'm migrating from mongodb to lokijs, and mongodb supports this 'double dots array' search queries)

**Comment by obeliskos** [comment]
I am not familiar with dot notation being used to express subarray objects in mongo.  Feel free to pass link describing this syntax if you can.  What I did find was mention of their $elemMatch operator and aggregration.  I find no examples of using this within a 'subarray-within-a-subarray' scenario like you described though.  In your scenario the dot notation does not evaluate on the object itself, since an interior 'dot' represents an subarray.

I think I can add $elemMatch op without much problem, but as for nested subarrays I might want more research.  

Feel free to let me know if I am missing anything or have any other ideas.

**Comment by andrii-mob** [comment]
Sorry, I did not mention that we had used mongoose to work with mongodb. So here is the simplified schema:
```javascript
var Foo = mongoose.Schema({
     _id: Number,
     level1: [{
         _id: Number,
         level2: [{
             _id: Number,
        }]
    }]
});
```

Here is the query:
```javascript
Foo.findOne( { 'level1.level2._id': id }).exec(function(foos) {
    // do something with foos
});
```

Would be great to have a similar query in lokijs.

**Comment by obeliskos** [comment]
I'll keep this in mind so when I have time to juggle the logic to see if this can be done, I can look into doing it :) 

 Easy one might be adding an elemMatch op.  Beyond that I will look over our dot notation implementation to see if detecting array and iterating makes sense at each level.

**Comment by markgillnz** [comment]
I have submitted a PR which implements nested dot notation.

**Comment by Viatorus** [comment]
Can be closed. Thank you.
