### ISSUE TITLE
id index is not preserved after loading database

### ISSUE THREAD

**Issue by hyusetiawan** [techfort/LokiJS#279]
steps to reproduce:
1. create a database with the following config: {
            autosave: true,
            autosaveInterval: 10,
            autoload: true,
            persistenceMethod: 'localStorage'
        }
2. create a collection
3. insert a document
4. calling collection.get(1) returns the object as expected
5. hit refresh and the database will be reloaded
6. searching through find() works, however calling collection.get(1) will return undefined and the collection idIndex contains [undefined].

I am using lokijs in the browser, through browserify

**Comment by obeliskos** [comment]
Your autosaveInterval is set to 10 milliseconds which is way to low, I would recommend minimum of 1000.  If you meant to use a sub-second interval, let me know and we can pursue it from there.

My sandbox test shows it to be working as I would expect it to work, you can view and run my sample here : 

[Loki Sandbox idIndex persistence test](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/31938855c23de4fd3173/raw/702089b44aa1081419f8456a897ebc7df026a1bc/idIndex%2520persistence)

If you click that link and wait 1.5 seconds it will create a test record (the first time you run it).  Refreshing the page will look up that existing object to get its $loki id and then do a get on it.  If I hardcode a get(1) in the setTimeout else statement, it still works.

**Also :**
Take this example constructor : 
```javascript
var db = new loki('idindex_test.db', {
	autoload: true,
	autoloadCallback : loadHandler,
	autosave: true, 
	autosaveInterval: 1000,
});
```

In order for the db variable to be 'set' and available when loki calls your loadHandler, we need to invoke it asynchronously with a timeout so that we return the instance before our async autoloadCallback fires.

So make sure your get(1) occurs either within the autosaveCallback or after yielding the js thread.   You can have it do your get on your own setTimeout (of greater than 1 ms?) delay or some other user interface invoked handler.

**Comment by hyusetiawan** [comment]
ah okay, I tried it out and it works.
Is it written in the docs that it has to be a minimum of 1 second? Shouldnt it throw an exception if it is set below 1 second?

**Comment by techfort** [comment]
@hyusetiawan this is not specified in the docs yet but we will be publishing a new release soon enough and amend all the documentation to reflect the changes and highlight best practices. I'll close this for the moment as not an issue. Feel free to reopen if you think codebase should be amended to address the minimum autosaveInterval property.
