### ISSUE TITLE
.find({$and: [{prop:{}}, {prop2:value}}]) results in exception

### ISSUE THREAD

**Issue by moshewe** [techfort/LokiJS#284]
I can understand why the above results in an error from the library code POV, but it should be documented. I tried understanding the code there but I got a little lost. Maybe this can all be avoided by simple filtering of inputs?

```
collection.find(
        {
            $and: [
                {height: {}},
                {width: 200}
            ]
        }
    )


TypeError: fun is not a function
    at Resultset.find (...\node_modules\lokijs\src\lokijs.js:1862:21)
    at Resultset.findAnd (...\node_modules\lokijs\src\lokijs.js:1528:14)
    at Resultset.find (...\node_modules\lokijs\src\lokijs.js:1650:48)
    at new Resultset (...\node_modules\lokijs\src\lokijs.js:1041:21)
    at LokiEventEmitter.Collection.find (...\node_modules\lokijs\src\lokijs.js:3514:14)
```

**Comment by obeliskos** [comment]
Yes our find function may be the most performance critical and difficult to read part of loki.

A direct solution to this specific empty object comparison may be performance sensitive since we would have to alter our $eq operator to test for empty object conditions on both sides using Object.keys and yield true if that case exists.  This additional logic would slow down most other $eq operations significantly.

You have mentioned two features lately (multiple properties in find object as implicit $and statement), which lead to think a simple pre-processor should be used to handle fix-up of the query object before we pass to find().   So before we run the query as many checks as we can without knowing the data involved and alter the find object so the query engine performs as you expect it would.

For this specific issue I can see a preprocessor scanning for empty objects as right hand values of find expressions, and maybe converting it to use a custom equality operator like $eoe (empty object equality) for its internal use.  You wouldn't 'need' to know to use some custom $eoe op, we would detect and in that specific query path we would use a (slightly slower) empty object equality test.

Your other issue of $and ops commented in #150 would actually be easier and could be done in a similar preprocess phase.

**Comment by moshewe** [comment]
Good points. A preprocessor also lends itself easily to compiler run-time optimizations. Are there no ready made components we can cannibalize from Mongo?

**Comment by obeliskos** [comment]
Shouldn't be necessary... I have some logic i'm using for collection transform parameters which I could use for this part of said preprocessor.

**Comment by moshewe** [comment]
Bumped into this problem again - wrote a wrong built-in function name for find, got `TypeError: fun is not a function`. We should really document this and explicitly say that this will remain so for performance purposes.
