### ISSUE TITLE
Slow refresh of angularjs select when using indexeddb adapter

### ISSUE THREAD

**Issue by EduardoJimenez** [techfort/LokiJS#295]
I have a 1,500+ rows 20+ properties collection which I populate from a restful JSon webservice, when I create the database and collection the first time, an angularjs select populates inmedialelly, but when I refresh the page, with the collection saved, it takes 30+ seconds for the select to show data.

When not using the indexeddb adapter, the select is shown with data inmediatelly.

```
$scope.clientes = [];
var idb = new LokiIndexedAdapter('ruteo');
var db = new Loki('SGABaseMovil', { adapter: idb });
db.loadDatabase({}, function () {
    $scope.dbclientes = db.getCollection('clientes');
    if ($scope.dbclientes === null) {
        $scope.dbclientes = db.addCollection('clientes', { unique: ['cliente']});
        $http({method: 'GET', url: 'http://localhost/SGA/CRC/clientes/todo'}).
           then(function (retorno) {
               $scope.dbclientes.removeDataOnly();
               $scope.dbclientes.insert(retorno.data);
               db.saveDatabase();
         });
    }
    $scope.clientes = $scope.dbclientes.data;
});
```

The select is bound to $scope.clientes as such:

```
<select id="selcliente" ng-model="selcliente" ng-options="c.clientenomb for c in clientes track by c.cliente"> 
</select>
```

**Comment by obeliskos** [comment]
I would expect a database of that size to load instantly, which leads me to think this is angular databinding issue somewhere.  

First off i'll assume you are using the latest verson of loki, if not how old is your version?

Next, the indexeddb adapter is capable of being used for diagnostic purposes with a browser console.  Open up a browser console and type something like the following : 
```javascript
var lia = new LokiIndexedAdapter('ruteo');

kia.loadDatabase('SGABaseMovil');
```
Directly calling adapter load method without callback should dump string to console. That will help diagnose if issue is adapter itself since it should return serialized db string right away.

Our indexeddb adapter is truly asynchronous (since indexeddb itself is asynchronous).  Our callback approach should work similarly for both asynchronous (like indexeddb) and synchronous (like localstorage) adapter back ends.  A few console.logs() in those callback events should verify this is the case.

Feel free to let me know your results and/or provide more info.

**Comment by EduardoJimenez** [comment]
Thanks very much for your response (almost synchronous :) ) and for your tips to debug.

Yes, I am using the latest version of all js components, Loki and Angular and Loki-Angular.

As you say, I've come to determine that the problem is in the refreshing of the select control, when I click once on the empty control and click outside, it shows the data.  Again, if I don´t use the adapter, this does not happen.

Who do you suggest I take this issue to?

**Comment by obeliskos** [comment]
I have not had the time yet to examine the loki angular adapter, perhaps @helzgate or @techfort could look over and let you know if they see anything.

So if you change the last few lines of your callback to be this : 
```javascript
console.log('setting $scope.clientes');
$scope.clientes = $scope.dbclientes.data;
```
and monitor the console, does it hit that in a normal timeframe?  If so loki should already have set the data array you are binding to so I would think it should work.

**Comment by EduardoJimenez** [comment]
All data is retrieved timely, it is the redraw of the select that takes some time.

I have another issue, which is most important to what I am trying to do.

I create de database and a pair of collections, and work with them viewing data, and the data persists the same day without problem (I even reboot my computer and data still there).

But when I browse the same page next day, I find that apparently data is not there.

I use Firefox with indexeddb adapter.  I don't use an app, just the browser.  I do use the db.saveDatabase instruction after creating the collections.

Will the persistence only work if I use a web server to serve the pages?

Am I lacking some additional procedure here?

**Comment by EduardoJimenez** [comment]
Eureka:  it seems that the data binding needed a little help for some reason, so I surrounded the variables with such:

        $scope.$apply(function () {
            $scope.vendedores = $scope.dbvendedores.data;
            $scope.clientes = $scope.dbclientes.data;
        });

**Comment by obeliskos** [comment]
You should probably set up a local web server for your development environment.

IndexedDB storage is typically allocated to a 'domain'.  If I set up a localhost web server that domain is 'localhost' no matter what page or url params I pass to a page served up from that domain.

My experience with firefox is that, while it does seem to allow indexeddb even when the page is just loaded from filesystem, since it lacks a real domain the storage seems to be tied to a url.  So your data might still be there, just tied to a file:// url which includes page and hash params.

You can probably look in option / advanced to see 'offline content and user data' to find your many makeshift domains.

Since even for SPA apps, angular is very hash dependent, I would recommend finding at least a simple static file server to serve up your site.
