### ISSUE TITLE
`clone: true` with dates

### ISSUE THREAD

**Issue by jsumners** [techfort/LokiJS#299]
```javascript
const fivemin = new Date(Date.now() + 5 * 60 * 1000);
const sixmin = new Date(fivemin.getTime() + 60 * 1000);

const db = new Lokijs('memory');
const collection = db.addCollection('foo', {clone: true});
collection.insert({
  foo: 'bar',
  myDate: fivemin
});

const doc = collection.findOne({ foo: { $eq: 'bar' } });
doc.myDate < sixmin; // should be true but is false because now `myDate` is a string
```

**Comment by obeliskos** [comment]
Yea, by default, the clone method is 'parse-stringify' which does such things.  Since most people concerned about cloning probably save their database, the same thing will happen upon save when we serialize your database along with its objects.

If you are just concerned about the 'in-memory' part, you might try some of the other clone options if they are available (or make sense).

The collection 'clonemethod' option is by default 'parse-stringify', but it could also be : 
"jquery-extend-deep" : if you have jquery loaded you can use this option to do deep clone.

"shallow": if your objects are not hierarchical, or you only care about cloning the top level properties, you can use this option.

We probably need a dependency free deep clone option, but have not had the time to look into this.  

If you search for : 
```javascript
function clone(data, method)
```
You will see our clone function and could modify it with your own cloning implementations.

**Comment by jsumners** [comment]
In this case, I'm working all in-memory in a server side application. I'm basically using Loki to store state between requests, i.e. the objects being stored would be lost if they aren't cloned.
