### ISSUE TITLE
DynamicView.applyFind issue

### ISSUE THREAD

**Issue by shaderzak** [techfort/LokiJS#306]
Hello 
I have some case with applyFind function, similar to snippet below.

```
var view = activitiesDB.getDynamicView('timeline');
view.applyFind(filter);
```

Although passed filter parameter was always the same, it created a new filter every-time. 
![loki-multiple-filters](https://cloud.githubusercontent.com/assets/7924666/12075284/90228c20-b17b-11e5-9da7-47d72e8d13ca.PNG)
Is it possible to have some check, if the same Find already exists then just overwrite it.
Thanks
p.s. appyFind is persistent, while applyWhere and applySimpleSort no, is that the way it was designed?

**Comment by obeliskos** [comment]
How many filters do you want to have active at a single time and how often do you change the pipeline? 

We offer the ability to name filters and remove them independentlyusing : 
```javascript
view.applyFind(filter, 'SomeFilter');
view.removeFilter('SomeFilter');
view.applyFind(anotherFilter, 'SomeFilter');
```

Dynamically modifying the filter pipeline is a work in progress, so perhaps @VladimirTechMan can clarify if there is an easier way.

We could also have method to clear entire pipeline if you do not wish to name filters.

Having said all that, the effectiveness of using a dynamic view depends on some form of stability in the filter pipeline, otherwise you might as well just issue queries directly against the collection.   Your queries should hit a single filter pipeline 'variation' more than once to gain any value at all.

**Comment by shaderzak** [comment]
Hello @obeliskos 
Thank you for reply.
Basically I needed only single filter, but some function was mistakenly called it more than once (with the same exact parameter) and applyFind was just adding a new one, without any check if it already exists. The result was tremendous number of filters in the pipeline.

**Comment by VladimirTechMan** [comment]
Just to add a few more details to what @obeliskos already pointed out above:

* LokiJS allows to give names to the filters being added to dynamic views. By referencing the (unique) name of an existing filter, you can update or remove that filter. Having said that: To my knowledge, the related code changes were not released yet as a new official public version of LokiJS. Thus, if you install LokiJS as a ready package (e.g. with "npm install lokijs"), it won't give you the updated API that @obeliskos mentioned above. However, if you are directly using (or can switch to using) the most recent code from LokiJS' repository at GitHub, then you can try it immediately. Based on some previous comments from @techfort, I guess that a new public version of LokiJS is not too far away.

* With the updated API, when you call `dynamicView.applyFind(query, 'uniqueFilterName')` for the first time, the filter will be added to the view with the name specified with the second argument of the method call. Then, if you want to remove that filter, you can call `dynamicView.removeFilter('uniqueFilterName')`. If you want to update the filter, you simply need to call `dynamicView.applyFind(updatedQuery, 'uniqueFilterName')` and it will replace the filter with that same name (you are not required to call `removeFilter` in this case before calling applyFind to replace the query with a new one).

* If you want to completely remove the whole filter chain from an existing view, rather than individual view(s) with names, you can now call `dynamicView.removeFilters()`. Please, note that it will also remove the sort function / criteria, if any, that was previously applied to the dynamic view.

* To your recent comment: We might easily extend the API described above with a method like `dynamicView.hasFilter('uniqueFilterName')` to let the external code check if there is already a filter with the given name in the filter chain. But, honestly, I would suggest that you explicitly add that application state detail to your own code and check it as appropriate, to avoid adding the same filter more than once. That, in some cases, can be done more efficiently. Especially given that you have only one filter, as you mentioned.

Hope that helps!

**Comment by shaderzak** [comment]
@VladimirTechMan now I understand your point. Following will solve my case. Thank you very much.

**Comment by deenfoxx** [comment]
I was having difficulty finding documentation on these features. I finally found updated docs here... https://rawgit.com/techfort/LokiJS/master/jsdoc/DynamicView.html

This might help others looking for info on the newer functionality that has not been documented on http://lokijs.org/#/docs or https://github.com/techfort/LokiJS/wiki

Perhaps a reference can be mentioned on these sites on how to find the most up-to-date documentation?

**Comment by obeliskos** [comment]
Good idea.  I added link to wiki overview page.  Maybe @techfort can add a link to lokijs.org sometime.

While our link is to the hosted jsdoc pages, and github clone will bring those pages over to your local filesystem... if you are using npm you can build them locally yourself with : 
```
npm run jsdoc
```
