### ISSUE TITLE
Accurate count

### ISSUE THREAD

**Issue by rmckeel** [techfort/LokiJS#308]
Hello,

  A nice API feature would be counting the number of entries in the Loki collection.  Currently, it seems I have to either do a `collection.find().length` or inspect the Loki object e.g. `_.size(collection.data)` (examples uses Lodash library).
  I know that a length of an array that has been modified is not necessarily accurate, so it would be great to have an API wrapper for a quick response of 'how many items do I have in my collection'.

Thanks for considering!

  Ryan

**Comment by obeliskos** [comment]
We should not have any holes in our collection.data array, so a collection.count() function could easily determine this with collection.data.length.

Care to submit a pull request for this?  If not I will try to update this soon.

**Comment by rmckeel** [comment]
Hey, thanks for the response.  I tried, and I can't get collection.data.length to fail, except by accessing directly (`delete collection.data[5]`).  Going off of this: http://blog.caplin.com/2012/01/13/javascript-is-hard-part-1-you-cant-trust-arrays/

LokiJS is awesome, so I'd love to have a hand in contributing to it, even if in a small way.  I'll try the PR route and should have something in a day or two.  Thanks!

**Comment by obeliskos** [comment]
Your link brings up very valid points... and it may apply to some of the constructs within lokijs, but collection.data is not one of them.  Since collection.data is such a pivotal data construct in terms of performand we use array.slice. array.splice, array.push to ensure there are no holes in the array.  We use collection.data.length internally all the time.

Other areas within loki use arrays as hashmaps which would exhibit the behavior your link describes.

Sure, just add a collection.prototype.count method (maybe just after we assign Collection.prototype to LokiEventEmitter), and have it just return collection.data.length.

**Comment by rmckeel** [comment]
Hey obeliskos, I implemented but then found it `Collection.prototype.count` already was implemented!  Since documentation is not connected to GitHub (as far as I can tell), I would suggest documentation be updated as soon as possible, as the `count` function looks very handy.

Thanks!

**Comment by obeliskos** [comment]
Hah, go figure... not sure who added that maybe @techfort..  He has been pretty busy lately but we can add documenting this to his queue of tasks for whenever he can.  If you run into anything else, feel free suggest or make other pull requests.

**Comment by obeliskos** [comment]
I believe we determined that we already have a count() method on collection, closing

**Comment by rmckeel** [comment]
Thanks @obeliskos.  Yes, `count()` was implemented but is not yet documented, and documentation isn't in Git repo, so I can't help you out there.  Thanks!
