### ISSUE TITLE
Sort 

### ISSUE THREAD

**Issue by OmerHerera** [techfort/LokiJS#309]
Seems that the API simple sort, first sorts all the entries with capital letters and then all without capital, so if I have the following elements
Z, d, A, b, a, o
I'll get:
A Z a b d o
It's possible to sort ignoring capital letters? 
Thanks

**Comment by obeliskos** [comment]
Currently you would have to write your own sort function.  Maybe in the future we could add this option, but we would need to do type checking and add option to indicate case insensitivity.  Since multiple objects might have different types or nulls for that property it is more prone to errors, hence why its probably not in there already.

Having said that, if you are certain each object has that property and that property is always string you might do something like this to create the behavior you are describing : 
```javascript
function mySort(obj1,obj2) {
    return obj1.toLowerCase().localeCompare(obj2.toLowerCase());
});

coll.chain().sort(mySort);
```

**Comment by OmerHerera** [comment]
Thanks for your answer.
This solves my issues, but I'll like to see it in LokiJS like a feature.
I'm not closing the issue, I'm leaving the decision to close it for the maintainers of the repo, I'll respect any decision.
Thanks for this great repo :thumbsup:
 
Thanks
