### ISSUE TITLE
Memory/Persistance Storage Best Practices

### ISSUE THREAD

**Issue by erichulburd** [techfort/LokiJS#342]
I'm working on a project where two of the main requirements are performance and persistent storage for large datasets (potentially in the 200MB range).

I came across LokiJs as well as PouchDB and I'm leaning towards LokiJs because it has both memory and persistent storage caching layers.

I have a couple general best practice questions.

Let's say I have a model like a house. And we are receiving 15-minute electricity consumption data from it - let's call this model a PowerDatum. The house metadata will be very light (name, address, etc). The power data request, however, could return 3000-18,000 rows for a given house. I'll need to be able to query that data on `PowerDatum#time`.

**Question 1**

Coming from a SQL background, I'm trying to wrap my head around structuring this database(s). One alternative is:
- Each house is a separate database.
- That house has a 'PowerData' collection - this has a unique index on time.
- Each power datum is a doc, which can then be queried with LokiJs methods.

This will create a database for each house.

An alternative is:
- One database.
- There is one 'PowerData' collection. This would need to be indexed on house_id and time (separately).
- Each power datum is a doc, which can then be queried with LokiJs methods.

Is there a clear advantage to one of these approaches to you?

**Question 2**

Because our dataset is so large, my goal is to be able to save data in persistent storage and clear it out of memory to create room for another set of data (say power usage from another house).

Do I call `db.save(); db.close();` to clear it out of memory and subsequently `db.loadDatabase()` when I need that data back? Or do I need to call `db = null;` as well?

Thanks for the great work.

**Comment by Arbolista** [comment]
Also, is there a way to load only selected docs from a database into memory and add additional rows into the persisted database without loading and re-saving the whole database? Or is this best done using two different databases - one of which is active in memory, the other which is only brought into memory when needing to re-write it.

This would limit the persisted databases to memory size limitations rather than storage limitations.

**Comment by techfort** [comment]
@Arbolista sorry for the late reply, time is not my friend lately. I will look through your use case in the next few days hoping it's not too late for you.

**Comment by Arbolista** [comment]
@techfort Thanks I totally understand. Feel free to point me to an existing blog post, etc if it'd help.

I know I'll have a client need meeting some of the above requirements mentioned above, so if there's not existing support to do what I'm trying, there's some potential I'd be able to implement if it fits the direction of loki.

**Comment by obeliskos** [comment]
Probably too late to chime in but if not, or for future reference, it would seem this would be a good candidate for a for an [advance database adapter supporting collection spanning](https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters#advanced-adapter-interface).

You don't mention hardware requirements so I will assume desktop or server class hardware where 200mb in memory at once is no big deal?  Also assuming desktop class harddrive/storage which could load 200mbs in a timely manner.

If either the memory overhead or initial load times from io are too slow for the task you intend then, short of us/you coming up with a way to lazy load individual collections, you would instead need to do as you mention and save separate databases.  In that case close() does a final save/flush (currently) only when autosave is configured.  And it does not currently free the memory but reassigning the db or setting to null should cause memory to be released.  Loki.close() currently emits a close() event so i'm not sure if those event listeners need to see the data... if not we could free in close().

Since you plan to query on PowerDatum#time you might want to use an integral time format like date.getTime() for unix ms format.   Keeping property as javascript date will add overhead to our indexing as it has to cast it to string for comparison.  There are serialization issues with js dates so I tend to use integral format and convert back on demand...  but feel free to handle these issues however makes sense.
