### ISSUE TITLE
Question, filter

### ISSUE THREAD

**Issue by lygstate** [techfort/LokiJS#355]
Would the DynamicView would response to CUD(Create Update Remove) events of collection along
with the apply of filter?

**Comment by obeliskos** [comment]
Sorry I completely missed this, dynamic view is registered with collection and is 'notified' whenever documents are inserted, updated, or removed from the collection so that it can keep the dynamic view up to date.  The dynamic view emits a 'rebuild' event to let you know when any of those changes affect the view results.
