### ISSUE TITLE
Provide a way to showing DynamicView in listview directly without use the .data() function

### ISSUE THREAD

**Issue by lygstate** [techfort/LokiJS#360]
And
1. The ListView should response to the DynamicView's changes (create update delete)
2. The ListView should be sorted in some condition.

**Comment by obeliskos** [comment]
Well we support persistent dynamic views which have internal resultdata array along with rebuild events.  I would imagine a listview would raise update events where you yourself would fire off add/update/delete db calls.  If I recall correctly, you can call apply new sort and it will replace any previous sort.  

Loki is pure JavaScript so ui layers will have to interface with loki rather than loki interfacing with ui directly, if that is what you are asking?  If so that would need to be done in a different ui adapter layer of some sort outside the core loki file.

**Comment by obeliskos** [comment]
closing this pending more information
