### ISSUE TITLE
Clarification: Finding multiple documents with array of  *indexed* parameter values

### ISSUE THREAD

**Issue by ArekSredzki** [techfort/LokiJS#369]
Hello, looking through your documentation I found something which is unclear. What is the best way to find multiple documents if an array of _indexed_ parameter values is known?

**Comment by obeliskos** [comment]
Not sure I understand what you mean by indexed parameter.  Care to give a pseudo example of how this might look and I will see if there is a parallel.

**Comment by ArekSredzki** [comment]
@obeliskos Gladly :)

Let's say that I have created a collection with the following
```js
var collection = db.addCollection(collectionName, {
    indices: ['name']
  });
```

Now I would like to get all elements of the collection that have the name found in variable `desiredNames` containing an array

I know that I could use the following to get the entry I would like that matches this one value of name: `collection.by('name', 'george');`

Your documentation says that the form above will be faster than a regular `.find()` because `name` is indexed somehow. Can I get the same speed up when I have an array of names? (A method better than using a for loop of course).

Thanks!

**Comment by obeliskos** [comment]
Interesting, ok I believe collection.by requires index created with unique property.  The index it appears your example is creating is a binary (range) index useful for $lt/$gt ops in addition to $eq allowing dups.

Is each name unique?  If so we might need to modify function to accept array, which it could iterate and concat results.

If not unique, we might be able to create collection or resultset function which (behind the scenes) converts this into an $or op of many name $eq element subexpressions.

Currently (functionally) you might have to use find() along with an $in op which I think which may not be able to use a binary index (or unique index).

Let me know which of those paths is most relevant and we can determine feasibility of adding.

**Comment by ArekSredzki** [comment]
@obeliskos Thank you for the clarification!

Both of those use cases apply to what I'm doing with my project. I imagine that I'm not the only one that this functionality would help either. :+1: 

Let me know if any further information would be of use.

**Comment by obeliskos** [comment]
Alright, since I don't when exactly when I (or anyone else if interested) will be able to get around to this, I will summarize this as : 

Unique Index path mods : 
- modify collection.by() to detect when an array is passed into value.  If array then foreach it, running collection.by on each value, and concat document results into single array to return.

Binary index path mod would need either of the following : 
- either need a new find method such as findAnyExact()?  It might accept property name and array values and would simply compose into an $or query object with subexpressions for each array value converted into a {'prop': {'$eq':val}} sub expression.
- (or) we could add a new op such as $containsIndexed which is handled similarly to $and and $or ops in that they are pre-processed out and handled by resultset.find() and helper functions rather than implemented via loki ops (since it needs larger scope of collection in order orchestrate calls to other loki ops.

Since the $or op simply runs each query (val) against the whole collection set it is able to utilize binary indexes (if they are defined for that property) for each subexpression.
