### ISSUE TITLE
Make 'clone' true by default

### ISSUE THREAD

**Issue by alexandernst** [techfort/LokiJS#379]
As per previous conversations, make 'clone' true by default. As this is a breaking change, this will be blocked until 2.0

**Comment by obeliskos** [comment]
there is a significant performance penalty incurred when using the clone option on a collection.  

As a quick test I get around 775k ops/s without clone option and around 155k ops/s with clone option turned on.  that is for indexed finds.  unindexed find was only marginally slower 25k->22k.

**Comment by alexandernst** [comment]
@obeliskos Yes, but iirc we all agreed (in one of the issues I opened a few weeks ago) turning it on by default as this is the "usual" expected behavior from users. Also, this won't remove in any way the functionality/performance with `clone: false`, so people seeking performance over stability/expected behavior could still easily get it.

**Comment by obeliskos** [comment]
i'm sure i never suggested making an 80% hit the 'default'...  what is your reasoning for wanting it to be the default? Generally loki prioritizes performance over protecting you from yourself.   

I have no context for this, was this email or github convo?

**Comment by alexandernst** [comment]
Hmmm, maybe I'm brainfarting and I only spoke with @techfort? I'm sure this
was here in github. Let me search for the issue.

**Comment by obeliskos** [comment]
'clone' option used to just clone on inserts, i expanded this to clone when you get data out as well... this adds big performance hit but i think this is what one would expect from a clone option.

**Comment by alexandernst** [comment]
I knew it was here somewhere! https://github.com/techfort/LokiJS/issues/347

My final point in that issue was: Loki is, mainly, a database, not an in-memory-cache (like Redis). The normal/expected behavior of a database is to insert/fetch your data without doing funny things (modifications, in this case) if you're not explicitly doing it (calling update/delete). That's why I suggested to set `clone` to `true` by default.

There is indeed a major performance hit caused by this, but this is how it should work, or at least this is what users expect. And a prove of that are all the issues related to `clone`: https://github.com/techfort/LokiJS/issues?utf8=%E2%9C%93&q=is%3Aissue+clone

Also, after going through all of those issues I realized that the defacto-answer (like a template) is always "Do you have `clone` turned on?", which is a clear indicative that people expect this behavior, instead of having to switch it on.

**Comment by obeliskos** [comment]
Hmm, well as i said this feature 'used' to only affect 'insert' perf, but has since been expanded to getting data out so there is large perf hit when getting out that @techfort may not have been aware of.  He can weigh in.

Perhaps we can add another loki method like addClonedCollection or addReferenceCollection to simplify 'defaulting'?

Up to now loki has been dependency free making it easy to just drop in and run.  Having said that we do support a cloneMethod of 'jquery-extend-deep' so if lodash is more performant we could add soft-dependency similarly but that would not make for a good 'default'.   How does lodash handle date objects?  Using our current 'parse-stringify' clone method dates are flattened to a string (as they are when saving and reloading).

**Comment by alexandernst** [comment]
I don't think adding more methods to the API would be a solution as that would still require users to compare and understand the difference between `addCollection` and a theoretical `addClonedCollection`, which is pretty much the same as just leaving it as `addCollection({clone: true/false})`.

@VladimirTechMan had some negative thoughts about changing anything in Loki that might affect (negatively) the performance, so maybe I'm trying to defend a wrong idea in the first place, but I really do believe this is how a database should behave.

About the lodash deepClone:

```
x = _.clone({d: (new Date())})
Object {d: Wed Mar 16 2016 03:16:51 GMT+0100 (CET)}
typeof(x.d)
"object"
```

it looks like it's cloning objects as-is. I'm wondering if ES6/7 could offer some help here... will research that.

**Comment by VladimirTechMan** [comment]
Oh... :-( It sounds as if I'm getting a reputation of person obsessed with only performance, over any kind of safety. While I am definitely focused very much on the perf topic for my on-going project with Loki inside (well, again, dealing with up to 40-50K records, all in a browser app, not that surprising – I hope!). But I am not exactly a type of character ready to sacrifice any kind of safety / robustness measure over the performance. My stance is much more like: give the developers a choice between "less performance for more safety out of the box" vs "more performance for less safety out of the box".

From that perspective, the "clone" options itself is exactly that choice. Thus, no concerns for my app – I can easily set `clone: false` in my code. The real question is, between the two major choices (even "mindsets") from the previous paragraph, what do we want to make a default. @techfort as the author has his major vote on it. And @obeliskos as the key long-time contributor is also a key decision maker here, from my perspective.

Having said that, one thing that I was considering myself as a possible "third way" approach here. Are you aware of the Immutable.js (originating from Facebook)? That one is quite a reasonable approach to dealing with immutable objects in JS (trying to minimize performance overheads -- by doing some smarter things than what a typical "plain" cloning does in many cases). The library is not without some "caveats attached" – in particular, mixing objects built with Immutable.js and plain JS objects in one collection would be a call for troubles. And Loki will not handle the objects constructed with Immutable.js "out of the box" right now. But we might consider that approach, as I expect that it can be lighter (compared to plain cloning) while giving the immutability benefits / guarantees where that is desirable. [As a side note, it would also make Loki much more applicable to the Redux-based app design, if you're familiar with the concept / library.) Anyway, those are my two cents to your discussion above.

**Comment by VladimirTechMan** [comment]
To clarify: I meant to say, "we might consider the approach with supporting both the plain JS objects in Loki, with or without cloning them – as it has been implemented, though maybe with some tweaks – and the collections with the records constructed using Immutable.js".

**Comment by alexandernst** [comment]
> give the developers a choice between "less performance for more safety, out of the box" vs "more performance for less safety, out of the box".

I couldn't have expressed that better. The entire issue here is to decide whether to offer safety or performance out of the box. In any case, an improvement of the docs is required. I'm thinking about big red blinking text :smile: explaining what happens when `clone: true` and what happens when `clone: false`. Currently the docs don't say too much about that, thus so many users making the error of running their databases without `clone: true` and ending up with screwed documents.

As for Immutable.js, I heard a few things about it, but never got the time to read the docs/code. Will research that too.

**Comment by techfort** [comment]
hey @alexandernst @VladimirTechMan @obeliskos - regarding this: I think LokiJS always had a particular identity, with its unique combination of speed / simplicity / minimalism (among which I include the fact that it's dependency-free).
Offering a solution that is not faster than other solutions of the same type, not as easily integrated and easy to pick up puts the whole project's existence into question.

That is why the first iteration of LokiJS did not even have a `clone` option: I was basically giving everybody a solution that was screaming fast, although it was up to the developer to the brakes in place, LokiJS only had the accelerator pedal.

Now the product has matured, expanded and improved, especially because of the contributions you made, so it makes perfect sense to think of LokiJS as a fully-fledged F1 car instead of a dragster with no brakes.

In my view, as of 2.0, we should investigate and benchmark the performance of safety options, and provide "profiles" (e.g. full-speed, with-brakes, slow-and-steady-wins-the-race...). Developers will always have the freedom to customise and tweak every single configuration option, but if we guide them towards 2-3 major "approved" approaches they might be less likely to either misunderstand the db behaviour or slow it down unnecessarily. 
Just an idea.

As for the current cloning mechanism, we should definitely go the DI route. If a developer knows what they are doing then they'll choose a cloning mechanism that is both satisfactory functionality-wise and performs well (I could have said "performant" but i have a crusade against this word, it can be used to describe a priest telling mass "he's the performant of the ritual", not a fast database). So basically, either use our own clone function if none is injected or whatever is injected.

**Comment by TeamworkGuy2** [comment]
:+1: @techfort, I agree with your stance on LokiJS, please continue to give developers control over performance and use documentation and demo/example code to point developers toward the major 'approved' approaches. 
I work on an enterprise app which uses LokiJS and our architecture is designed around LokiJS being configurable as an in-mem store that doesn't copy or modify any references.

**Comment by alexandernst** [comment]
Hey @all, sorry for not REing early, kind of a busy week...

Ok then, let's keep `clone: false` by default, but let's make it clear what
exactly that means.

I also like the idea of profiles. This is pretty much how the Windows
installer of MySQL/MariaDB work (they ask you how many connections you have
and how much data, and then they optimize the DDBB).

​

**Comment by lukas-vollmer** [comment]
Hi @all, we just started with loki and had the same struggle as @alexandernst mentioned. I also agree that the performance boost is the better option, but please add a note in the docu.
