### ISSUE TITLE
Equivalent to findOne() for where() 

### ISSUE THREAD

**Issue by wisec** [techfort/LokiJS#387]
I think it would be very useful to have some way to stop looping through data collection when only the first match is required. 
Something like:
```
coll.chain().where(function (obj){
 return XXX==VVV...
},{maxResults:1})
```
Of course I may use .limit(qty) but from a performance perspective it's called only when the whole resultset has been visited.
Thanks, and keep up!

**Comment by techfort** [comment]
@wisec `find()` provides a `firstonly` flag (unfortunately this seems to be missing from the docs so my bad!). BTW I can't remember if `limit()` is lazy or not, I'll have to check that, @obeliskos might chime in to clarify.

**Comment by obeliskos** [comment]
This would be nice to have and not very difficult.  As @techfort mentioned, if it's possible to express your filter as a find() filter object, that is the preferred code path. 

If that doesn't meet your requirements (or you just prefer where function filtering), our current approach does not allow short-circuiting out a full array scan if you are only interested in the first element.  

This would not be difficult to add, if you are interested please submit a pull request.  I suppose we could add an options param to where() to indicate firstOnly.  Otherwise I will mentally queue this for when I (or others) get time.

I wonder if (for future refactoring) a es6 iterator option could be useful as well.

**Comment by VladimirTechMan** [comment]
@wisec, in addition to what @techfort and @obeliskos noted above, it is also worth of mentioning that I have recently implemented operator '$where' for the find-based loki queries. It is now in the main brainch for Loki 1.x, but not a part of a public version yet. And it's not yet documented on our project's site / wiki. (We certainly do have some technical debt on that side at the moment. And we plan to improve.)

In case if you are okay to grab the most recent version of Loki from its master branch at GitHub, then you can just play with it and see if that can help in your case. The new '$where' operator is applied against a field, just like most other query operators are, and the operator's parameter is a function that will get the field's value for each doc being tested, and it has to return `true` or `false` for the test result. That is, ```javascript { "field_name": { "$where": test_function } }```.

Being a part of the existing query mechanism for `find()`, you can apply the `firstOnly` parameter in this case just as you would with any other query passed to find(). Note that, while the operator works on a specific field, you can have several `$where` operators in the same query. And you can combine them with any other operators that we already have so that some pre-filtering can be done before custom functions in '$where' operators get applied.

Of course, the queries containing the '$where' operator would not suitable for persisting them with JSON, as JS-functions are hard to persist in such a way. But it's no different from the situation with the `where()` method.

In any case, if that can help you, I'll be glad to know your feedback -- or if you have any questions in relation to the details I gave above, let me know.

**Comment by wisec** [comment]
@techfort thanks, I saw the `firstonly` option by looking at the code, but my collection contains some complex object. Like: 
```
{a:{b:'c', d:1},..}
```
and the find function wouldn't work as far as I've understood. So I decided to give where a chance, but as you know callback is not really performance wise, so I thought to write here to hear from you, guys.

@obeliskos, thanks for looking into this!

@VladimirTechMan Interesting  thanks.

**Comment by VladimirTechMan** [comment]
@wisec Just a quick note on your previous comment for @techfort. The query objects for Loki's `find()` support nested fields in collection docs. The nested fields are not supported now by unique and binary indices, which means no index-based optimizations would be possible here anyway. But other than that, you can access nested fields and build your query based on their values. You just need to delimit the fields with the dot (".") character. For example, with your sample object above, you might use a query like this one:
```javascript
{ "$and": [ { "a.b": { "$eq": "c" } }, { { "a.d": { "$gte": 1 } } ] }
```
There are some limitations for the cases when your nested objects in collection docs contain arrays that contain objects in them, etc. For simpler cases, like you gave above, the query mechanism in `find()` should be able to handle it well.

I hope that helps.

**Comment by techfort** [comment]
thanks @VladimirTechMan - was just about to explain that but you got there first. @wisec if you're happy with the current state of affairs i'll close the issue.
