### ISSUE TITLE
Local file persistence adapter

### ISSUE THREAD

**Issue by moshewe** [techfort/LokiJS#388]
Other than `IndexedAdapter`, there are no persistence adapters ready OOTB.
Would you consider adding generic adapters, such as to a local file?

**Comment by moshewe** [comment]
My bad, didn't see the `saveDatabase` function... 
Maybe make it stand out more in the lokijs.org docs?

**Comment by moshewe** [comment]
So, eventually, you set the adapter in the `Loki` ctor? Am I the only one who got this one wrong at first?

**Comment by Kanaye** [comment]
Hey @moshewe,
Normally Loki picks a available adapter depending on the Enviroment (e.g. localstorage in the browser or an Filesystem adapter in nodejs).
But you can also provide your own adapter. 
For example the [LokiIndexAdapter](https://github.com/techfort/LokiJS/blob/master/src/loki-indexed-adapter.js):
```javascript
var db = new loki('MyDb', {
  persistenceAdapter: new LokiIndexedAdapter('MyDb')
});
```

**Comment by moshewe** [comment]
I understood that, eventually, but I don't think it was clear enough from the docs.

**Comment by obeliskos** [comment]
Our documentation is currently split between a very nice 'reference' type page here : 
http://lokijs.org/#/docs

As well as our wiki pages, for instance this one in particular for your issue : 
https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters

We are currently in the process of tweaking jsdoc syntax so that may be the best place to recommend changes to our 'reference' style documentation.  Feel free to contribute PRs to loki or or [lokijs.org github](https://github.com/techfort/lokijs.org) or offer suggestions for wiki pages.

**Comment by obeliskos** [comment]
closing this, we have new [jsdoc preview](https://rawgit.com/techfort/LokiJS/master/jsdoc/index.html) as well
