### ISSUE TITLE
Dealing with NaNs

### ISSUE THREAD

**Issue by pmorissette** [techfort/LokiJS#392]
First off, I want to thank you for this great library. 

I think I have come across a bug relating to the way ```NaN``` values are handled. I looked through existing issues and couldn't find anything related. 

Here's a quick example:
https://jsfiddle.net/c2ny7vvq/

Essentially, when filtering numeric data, ```$gte``` / ```$gt``` will return ```NaN``` values. ```$lt``` / ```$lte``` excludes them. The way I see it, ```NaN``` should be excluded on numeric searches, since they are not numbers. Right now they seem to be treated like ```Infinity```.

Adding the following to both ltHelper and gtHelper seems to fix the issue (at least for numeric data). I'm not sure if this is the right place to put it though - not very familiar with the library internals.
```js
if (isNaN(prop1)) {
  return false;
}
```
Another option could be to add a ```$notNaN``` filter. 

Thanks in advance for taking the time to look into this - I look forward to hearing back from you.  

Cheers,
Phil

**Comment by obeliskos** [comment]
Hi Philippe, since our current lt/gt functionality is used not only for $lt/$gt ops but for sorting and index generation we will probably leave those ops to function as they currently do.  Our current logic places NaN as greater-than ... say 12.

I would guess the easiest way would be to adapt our $ne op to support NaN.  It would be an extra test similar to your example.  We could also extend it to support testing for Infinity and -Infinity which is another weird case.

If your property is always a number (or number represented as string, like "12") we might also add $finite op which can use global javascript isFinite().  JavaScript isFinite() will be true for null, 0, 12, "12", 12.34, etc but false for NaN, Infinity, -Infinity, "test" and other cases.

I will look into the simpler updates to $ne since this is not critical path and that part seems straightforward for now.

**Comment by pmorissette** [comment]
Hey @obeliskos,

This makes sense to me - that's actually how I am currently dealing with it (I monkey patched a ```$notNaN``` function in ```LokiOps``` as a temporary solution) . 

So it would be something like this, correct?

```js
'$and': [
  {'$gte': 5},
  {'$ne': NaN }
]
```

If so, I think this is a clean, flexible solution. 

Cheers,
Phil

**Comment by obeliskos** [comment]
Yes, well add in the property name like : 
```javascript
'$and': [
  { orderCount: { '$gte': 5} },
  { orderCount: { '$ne': NaN }
]
```

In the future (possibly in a 2.0 version) we might split out $lt/$gt to use separate helper function than does our index calculation and sorting.

Thanks for raising issue, this should be in master branch, let me know if you have issues with it.

**Comment by pmorissette** [comment]
Hey @obeliskos,

This works for me! Thanks for the quick response, and thanks again for this great library.

Cheers,
Phil
