### ISSUE TITLE
Question: How large can a collection be?

### ISSUE THREAD

**Issue by kevinday** [techfort/LokiJS#410]
As I understand it there is a limit to how large of a file js is able to load. Is a collection just a file on disk, and if so, is there a hard cap on how large a collection can grow?

**Comment by obeliskos** [comment]
Since the whole database is loaded into memory, and when saving we serialize copy to string before persisting the entire database to disk, your main limitation would be roughly 1/2 to 1/3 of all RAM available to your javascript vm.

In the future we may support persistence adapters which store collections individually, in which case that limit would be 'per-collection' instead of 'per-database'.

Depending on the speed of your persistence method, you may find persisting (for example) 500 megs takes too long, in which case you will need to limit sizes accordingly to how long you are willing to wait for them to load/save.

**Comment by obeliskos** [comment]
- we now have a partition adapter which supports paging for optimizing browser collection sizes
- node fs structured adapter supports largest collections for node (maybe 2/3 heap alloc)
