### ISSUE TITLE
Collection update doesn't update index

### ISSUE THREAD

**Issue by piwnik** [techfort/LokiJS#412]
Collection update doesn't update indexed object. 
Here what I found
```javascript
Collection.prototype.update = function (doc) {
    
// some code here
        var arr = this.get(doc.$loki, true),
          obj,
          position,
          self = this;

// some code here

        obj = arr[0];

        Object.keys(this.constraints.unique).forEach(function (key) {

// !!! HERE index is updated with old object
          self.constraints.unique[key].update(obj);
        });

        position = arr[1];

// !!! Only HERE document is updated, but index still have old value
        this.data[position] = doc;
```

So when you try get get document by index, old document is returned

**Comment by obeliskos** [comment]
I think you are correct, we probably should update the unique[].update to use doc instead of obj.

Additionally, unique constraints can become internally inconsistent because doc is likely pointing to the same reference as obj.  If you do a get() and update a property on that returned object, you have already updated the document in our collection.data array, without having yet called update (since it is the same object reference).  

So unless the user is using unique constraints to enforce at the insert() level, they are not really safe to use unless you specify 'clone' option on collection creation to ensure internal reference is different than user space reference.  In that condition your change suggestion would be needed for successful index updates.

Would you care to submit a p.r. to fix that?  If you are familiar with adding unit test cases, that could be useful as well... otherwise we can just add that to list of things to do when we get time.

Thanks

**Comment by obeliskos** [comment]
I updated collection.update() to use doc which should help out when cloning is enabled (which it probably should be anyways).

Feel free to let me know if it works as expected, I will look into adding more unit tests to verify this later.

**Comment by obeliskos** [comment]
Closing this
