### ISSUE TITLE
how insert mango objectID _id ?

### ISSUE THREAD

**Issue by NuruddinBadawi** [techfort/LokiJS#417]
TypeError: Passed id is not an integer
what the way for insert new id and keep _id ?

**Comment by techfort** [comment]
Can you share the code that triggers the error? it would look as if you're trying to use `get()` or `by()` with a mongo id?

**Comment by nuruddinbadawi** [comment]
I think this error from mango id 
I have data come from mongo and each item has _id "I think I can't insert this object in lokijs because should be id integer value" so now the data has inserted no problem.

there is any problem when I make find in _id with string value ?

`_articles.findOne({_id:'PiY4AKELvnvTQ65mZ'})` it's work but ido't now if this right

AND 

`_articles.findOne({_id:id})`  not work and id is string like above.


any advice and thank you.
