### ISSUE TITLE
Database File corrupted

### ISSUE THREAD

**Issue by joehui** [techfort/LokiJS#429]
I am using Lokijs for one of our production REST servers.  The REST server uses the Express framework.  The database table that's being discussed here is the users table.  There are more than 2000 user records in the database table (the file is about 1 MB in size).  The database size is about   I use autosave (with autosave interval of 20 sec) to persist the database to a local json file.  As I understand, every time when the file is saved, the old file will get complete rewritten.  So, when the file is big, the save would take longer than a small database file.

Additional Information:  I use iisnode to run this server on IIS.

Earlier today, we suddenly discovered the database file become 0 size.  We are still looking for the backup file to restore the database.  Now, I am suspecting that this could be caused by one of the following:

1. Because the file is quite large, it could take a bit of time to save the file.   The node.js is really busy during the 20 sec cycle, could 2 consecutive file updates overlap each other and cause the file to become corrupted?

2. Some code could have crashed the node.js server during the writing to the file system.  I suspect that this is the most probably cause.  But, I don't have any evidence to support this.

3. I know that IIS reboots itself from time to time.  There is a chance that when IIS restarts itself, it would kill our server just at the right moment (i.e. in the middle of a database file update).

Do you have any other thoughts on how this could happen?

Another thing I am thinking now is the proper way to do backups for these files?  Because the file could change any second, there is a chance that the backup software may not catch the database right at the right moment.  I am thinking that Lokijs should have a feature to make proper local backup copies of the database.  There should be multiple copies of the database saved based on hourly, daily and  weekly schedules like a proper backup solution.   The backup software would at least be able to the backup the backup files.

**Comment by joehui** [comment]
After reviewing the server log file, I now think that the problem is caused by #2.  I saw that the node server crashed quite often (like once every other minute) at the same line of code during a user table sync process that lasted maybe 20 minutes.

**Comment by techfort** [comment]
@joehui this is really a broad conversation, beyond the issue you are experiencing. The reality is that when LokiJS is used on the server the persistence adapter should persist collections separately and - imho - even documents separately, because when Loki is used on the server the size of the db is expected to be larger. The aim is to avoid overwriting the entire database and limiting the damage in case of a crash. As for your question: as the nodejs model is non-blocking, it is entirely possible that two saves operations may access the same file.  The size file you are talking about though should only take milliseconds to save, so for now you shouldn't have overlapping saves.

So you have two solutions: 1. wait for me to write the nodejs incremental persistence adapter which would save all documents separately, with each document file being append-only, so the entire history of the document is available, or 2. write your own :) 

It is very difficult to guess why the save failed. Definitely without seeing the code it's impossible, and also i have literally zero experience of IIS / iisnode, which makes it harder. Maybe @obeliskos (who is more of a windows man than i am) has some experience in this environment.

As for backup tools, you are most definitely correct. I should be getting more time to get back to Loki and i want to start expanding tools (tcp/http wrappers, persistence adapters, and backup tools). One very important feature i'd like to develop is life beyond JSON, maybe utilizing msgpack or bson. But i don't have a precise idea of the work involved so no estimates on that backup tool just yet. Feel free to request features and I'll try to give it a stab as soon as i have time for it.

**Comment by obeliskos** [comment]
A 1meg file? Assuming normal hard drive that should take a split second to flush to disk.   A 20 second interval should be no problem... just to restate the obvious first make sure interval is passed as 20000 (ms).

So there's 'odds of collisions' among processes and then there are safeguards we can implement to address error prone edge cases.

We currently not detect if previous save is not yet completed.  We could keep flag of whether save is 'in progress' and skip a cycle in those cases to avoid potential filesystem conflicts.

In the future you may need to detect node's process.on("exit") and call db.close() to flush any pending changes.  During reboot it probably sends kill signal to node process which that event could detect to flush change and disable services in preparation for shutdown.  

So backup would need to be orchestrated by yourself until someone develops server tooling, but we might provide a method to temporarily disable adapter 'saves' while still tracking whether they are 'dirty'.  So you might tell loki to disable saves, issue file copy from node or spawn copy process, and when done tell loki to resume saves.

Also due to nature of single threaded main thread, the timer is more of a suggested schedule that can get thrown off by non yielding main thread activity.  Might we worth researching whether higher resolution timers in various environments are more 'reliable' as well as accurate.

**Comment by joehui** [comment]
Thanks for your replies.

Luckily, our IT department kept good backups of the server.  We were able to restore the file to 1 day ago.  Looks like we didn't lose anything.

Yes, the interval time is 20000 ms.

Yes, to make LokiJs a more robust solution for production use, I think it would be a good idea to have some code to protect the subsequent cycles from conflicting with each other.

Add process.on("exit") to flush the database sounds like a good idea.  I will definitely look into that.

In terms of doing my own backups, sounds like I will have to wait until you have such a method for temporarily disable the "saves".

**Comment by techfort** [comment]
@joehui i'm closing this as there is - strictly speaking - no issue. I have included in my personal roadmap backup tools to prevent your situation happening again..

**Comment by retorquere** [comment]
@joehui what I do in my own adapter is write the DB to a temporary file with a unique filename, and then move it into place (overwriting the older version). This should minimize the risk of corruption, as a halfway-written file interrupted by something will simply not be moved into place.

Incremental/partial save would be most welcome aside from that.
