### ISSUE TITLE
IndexedDB Adapter - delete callback?

### ISSUE THREAD

**Issue by vasumahesh1** [techfort/LokiJS#440]
Hi,

Correct me if i'm wrong. I can't seem to [find the callback](https://github.com/techfort/LokiJS/blob/master/src/loki-indexed-adapter.js#L180-L204) mechanism for deleting a database from IndexedDB?

There is a comment there written, which I couldn't comprehend

```js
// lazy open/create db reference so dont -need- callback in constructor
```

Any such reason why it isn't there?

**Comment by obeliskos** [comment]
Your right, looks like LokiIndexedAdapter.deleteDatabase doesn't accept callback, but it could since LokiCatalog.deleteAppKey (which it calls to do actual delete) does support callback.

Should be easy enough to add.  

As for the comment, i think that should be changed too.  Previously i think the constructor opened indexeddb database but now we lazy open 'indexeddb' database (as opposed to loki appkeyval database within it).  Therefore your code doesnt need callback in constructor but within loaddatabase where we hide callback of async opening database and then call your callback on async loading of key (loki db) within that idb database.

**Comment by vasumahesh1** [comment]
Yeah, I ll make a change when i'm free. Thanks for the input.
