### ISSUE TITLE
.applySimpleSort() doesn't seem to retain after .branchResultset()

### ISSUE THREAD

**Issue by hongxiangrong** [techfort/LokiJS#453]
Sorting seems to disappear after branching out the results of the dynamicView

**Comment by hongxiangrong** [comment]
```
var db = new loki('sandbox.db');

// Add a collection to the database
var items = db.addCollection('items');
var dyn = items.addDynamicView('test').applySimpleSort('name').applyFind({'owner':'odin'});

// Add some documents to the collection
items.insert({ name : 'mjolnir', owner: 'thor', maker: 'dwarves' });
items.insert({ name : 'gungnir', owner: 'odin', maker: 'elves' });
items.insert({ name : 'tyrfing', owner: 'Svafrlami', maker: 'dwarves' });
items.insert({ name : 'draupnir', owner: 'odin', maker: 'elves' });

// Find and update an existing document
var tyrfing = items.findOne({'name': 'tyrfing'});
tyrfing.owner = 'arngrim';
items.update(tyrfing);

var res = dyn.branchResultset();
logObject(res.data())

// These statements send to Text Output
logText('tyrfing value :');
logObject(tyrfing);
logText('odins items');
logObject(items.find({ 'owner': 'odin' }));

// This statement sends to Inspector
inspectObject(db);
```

**Comment by obeliskos** [comment]
Sorry I missed this.  I think you are encountering lazy sort which doesn't get applied until a call to data().

Since you are calling dyn.branchResultset() before calling dyn.data() you are branching a not yet sorted resultset.  I suppose it would make sense to apply sorts before branching I will have to think about it performance wise.   In the meantime you can either force lazy sorting via a call to dyn.data() or use branch resultset and chain a simplesort in there.

**Comment by hongxiangrong** [comment]
Thanks for the reply.

Yeah, having sort applied before branching will be great. Currently i'm sorting after branching as a work around. The implications are that the sort needs to be performed on every call.

Having said that, the speeds with the current workaround are still great. We also noticed that a custom filter function is more efficient than chaining multiple filters when it contains multiple checks for matches.
