### ISSUE TITLE
Object.observe has been deprecated to Proxy API

### ISSUE THREAD

**Issue by ohenepee** [techfort/LokiJS#455]
https://developers.google.com/web/updates/2016/02/chrome-49-deprecations?hl=en#objectobserve-is-deprecated

I keep getting console warnings from Chrome (haven't tested Firefox) each time I use LokiJS... just wanted to give a heads up on the deprecation before it breaks dependent apps or perhaps doesn't break them for too long.

https://www.chromestatus.com/features/6147094632988672 says `Object.observe` has been removed in Chrome 50 [ personally I use Chrome 49 for development ]

**Comment by obeliskos** [comment]
Sorry late reply, so I guess they don't want to add any features to JS spec that can't be completely polyfilled.  

Notice to @Cortys (re: #231) : I guess we will have to watch this and remove if this becomes breaking.

**Comment by Cortys** [comment]
Sure. It should not become breaking if autoupdates are not enabled though. Chrome only complains because of [this check](https://github.com/runnr/LokiJS/blob/db8b5c49794b2a794638df886163fd4a7f000068/src/lokijs.js#L3007) which is interpreted as "usage" of a deprecated API.

I've thought about reimplementing autoupdates via Proxies, which would also make them synchronous, but that may not be feasible for performance reasons and it also does not play well with the object inflation feature of `loadDatabase`.

Since the `Object.observe` based implementation does not / will not work anymore, removing autoupdates is probably the best thing to do for now. Let me know if you need a pull request reverting #233.

**Comment by xland** [comment]
Object.observe，This feature is obsolete. Try to avoid using it. Use Proxy.

Electron can not auto update collections.
