### ISSUE TITLE
collection find on nested object does not work

### ISSUE THREAD

**Issue by pearljamik** [techfort/LokiJS#476]
See this:
http://stackoverflow.com/questions/39494575/loki-js-filter-nested-objects

```
My object:

{
 report: {
          expirationTimeStamp: new Date(),  //some date object    
          anotherProperty: 'dada'
         }
}
Now as I try to do query like this:

let currentDate = new Date();

 return <T[]> this.collection.find({
  'report': {
    expirationTimeStamp: {'$lt': currentDate}
  }
});
Or:

return <T[]> this.collection.find({
  'report.expirationTimeStamp': {
    '$lt': currentDate
  }
});
```

it does not return a thing, where as:

```
let currentDate = new Date();

return <T[]> this.collection.where( obj => {
     obj.report.expirationTimeStamp < currentDate
     }
```

it returns a thing.

How come ? Is that find does not support nested indexing like report.expirationTimeStamp ?

**Comment by obeliskos** [comment]
Sorry I missed this, I think I understand.  I tried to recreate this in a sample and encountered the same behavior as you.  When I opened console tools to trace, it worked.  When I closed console tools and re-ran the find() had empty result.  

I think this is javascript being faster than the clock they are using for dates and in the empty result situations its because they are equal.

You should be able to verify this by modifying your currentDate declaration to be something like : 
```javascript
// calculate 1ms from now using unix epoch 
var currentDate = new Date((new Date).getTime() + 1);
```

**Comment by obeliskos** [comment]
closing due to no issue?
