### ISSUE TITLE
Setting "clone: true" on an existing collection

### ISSUE THREAD

**Issue by retorquere** [techfort/LokiJS#503]
Is it possible to set "clone: true" on an existing collection? `Collection.prototype.configureOptions` only seems to understand `adaptiveBinaryIndices`.

**Comment by obeliskos** [comment]
Sounds like it should be simple, just update the internal cloneObjects if passed in a 'clone' option.  If passed in true immediately clone data array.   You can either submit a pr for that or I will add it to my todo list.  Should probably also handle reconfig of 'cloneMethod' option as well.

**Comment by retorquere** [comment]
I'm not fully sure what the above means. Would the same be achieved by just setting `.cloneObjects = true` after loading the collection?

**Comment by obeliskos** [comment]
Well ideally if you are turning on cloning you want to make sure the objects in your collection.data are not referenced by any old user references... so I would also set collection.data = a clone of itself.  Since our clone utility method accepts a cloneMethod I would also add that.  

Having said that if you just set that collection.clone option and don't have any lingering references you might accidentally update (without calling update), then yea that would reconfigure to turn on cloning for find and where ops.

**Comment by retorquere** [comment]
That would suffice for my purposes, I do this immediately after loading the database.
