### ISSUE TITLE
Index on "deeper" property

### ISSUE THREAD

**Issue by retorquere** [techfort/LokiJS#507]
If I have an object like

```
{ itemID: 1, citekey: {format: '...', key: '...'} }
```

is it possible to index on `citekey.key`?

**Comment by VladimirTechMan** [comment]
Hi @retorquere! As we speak, Loki does not support that out of the box. Having said that, I was considering our approaches to that extension for sometime already (for plain nested objects only, not covering nested arrays of elements / objects). And I plan to work on implementing it soon. (Well, "soon" here may mean, practically, end of November of December time frame, due to my current work activities. I hope that is not prohibitively long for your current purposes.)

**Comment by retorquere** [comment]
Nope, not a problem.
