### ISSUE TITLE
Add an updateWhere function

### ISSUE THREAD

**Issue by philipgiuliani** [techfort/LokiJS#514]
Currently we have `findAndUpdate` and a `removeWhere` function.
Would be nice to also have an `updateWhere` since it should be faster than `findAndUpdate` (maybe replace it?).

**Comment by obeliskos** [comment]
Our terminology in loki is a little mixed up on this one... the current Collection.findAndUpdate() should probably be called Collection.updateWhere().  

Most places in loki we have been naming query methods which accept a 'mongo-like' query object as 'find' methods and query methods which accept a javascript filter function as 'where' functions.  Both functions you mention use javascript filter functions which do not benefit from indexing so they will always do full array scan.

Our resultset is already capable of most variations of find/where/update/remove so essentially we can call out to it from a collection level method.  Resultset update does accept an 'update' javascript function... we have yet to provide update where you update via object expression.

An example of a 'find and update' which is able to use binary index might look like :
```javascript
var orders = db.getCollection("orders");

orders.chain().find({ customer: 111 }).update(function(obj) {
  obj.price *= .90;
});
```

Were you looking for something like that or something else?

**Comment by philipgiuliani** [comment]
Thank you for the answer. This is exactly what I wanted to do! Should I keep this issue open for normalizing the naming on this function?

**Comment by obeliskos** [comment]
Sure, leave it open for now...

We can't make breaking changes but we can probably detect whether they pass in object or function and route to correct functionality.  I'll try to verify what's already out there and how we can adapt later... maybe today.

**Comment by Viatorus** [comment]
@obeliskos - Breaking changes maybe with version 2.0.0?

**Comment by Kanaye** [comment]
you could move it and alias it (and I would add an ``@deprecated will be removed in 2.0 use updateWhere instead`` jsdoc comment to the alias).

But I'll leave that up to you :smile:

**Comment by obeliskos** [comment]
@Viatorus - this probably wouldn't be a breaking change if we do type inference... also these methods would essentially be aliases to functionality we already have.

@Kanaye : sounds like a good idea ... hmm except the method will still exist for the actual purpose the name would intend... will at least add some notes about that though.

Ok to clarify I am thinking instead of two methods mentioned we will have these four : 
- **findAndUpdate(function|object, function)**
*We already have this, if passed function, route to updateWhere() otherwise chain find() and update() ops*

- **findAndRemove(object, function)**
*(new method) chain find() and remove() ops*

- **updateWhere(function, function)**
*(new method) Basically this will be what findAndUpdate used to be)*

- **removeWhere(function|object, function)**
*This seems to already support both function and object and does its own routing... since people may
  already be using both methods, I will leave this unchanged.*
