### ISSUE TITLE
Major Update - LokiJS 2.x.x

### ISSUE THREAD

**Issue by Viatorus** [techfort/LokiJS#525]
Hey everyone,

I want to move forward with you to a new major release of LokiJS.
Let us discuss what our goal for 2.x.x should be and how we reach it.

---

Goals for LokiJS 2.x.x:
 - Use/Migrate to ES6 (promise etc.)
 - Split code base
 - Change concept ?
 - Integrate full-text search #513
 - Solve issues: ?

Procedure:
 - Finish last feature and close feature requests for v1.4
 - Make v1.4 "final" as is and just maintainance for bug fixes
 - Merge changes inside master to branches 2.0.0.
 - Create new repository for LokiJS2.

**Comment by Viatorus** [comment]
Here are some thoughts from me:
- @Cortys and some other of you have already integrate ES6 into the working branch 2.0.0. But currently the master is ~20 commits ahead. I am sure, keeping track of these changes between the branches is not to easy and also demotivating by not knowing the goal.

  To overcome this problem I would stop adding features to the current version (1.4.x) and only fix some bugs (according to expenditure and severity). All new and open feature request should be target for 2.x.x.

  - When should we start to stop featuer request for 1.4.x?
  - How long should we maintenance bugs 1.4.x?

- I recommend to split LokiJSs main file into smaller ones if possible. There are currently ~5.5k lines of code. It would be easier to maintenance. But we should still build a non minified file for easy integration into a single html file (avoid many includes).

- There are currently over 100 issues, some are out of date, solved or irrelevant. Almost all are not labeled.

  - We should tidy up all issues by labeling, removing or solving them. ;)
  - We should also use [githubs project](https://help.github.com/articles/tracking-the-progress-of-your-work-with-projects/) to better manage progress/issues/todos.

That is all from me, what do you think? =)

**Comment by Cortys** [comment]
@Viatorus Some time ago I began working on bringing the changes from master into the 2.0 branch but due to a lack of time I did not finish it.

- Because the work required to merge master into 2.0 will only increase over time, locking 1.4 feature-wise seems like a good idea to me.
- I agree that splitting the codebase should be of high priority. IMHO locking down the amount of changes allowed to 1.4 would be a necessity before this can be done though.

For now I think I'll try to finally complete the master -> 2.0 merge within the next few days. That should make it easier to move forwards with the 2.0 release.

**Comment by obeliskos** [comment]
Hey guys, this sounds in line with my objectives for winding 1.4x branch down to a maintenance support.  Since the last merge I have overhauled the serialization subsystem but I would imagine the new LokiMemoryAdapter and LokiPartitioningAdapter would just need their interface to be 'promis-ified'.  If this proves too much work, perhaps you can just temporarily disable the TravisCI (if needed) and I will attempt to update any issues based on work already done by @Cortys.  I also updated a lot of unit tests to increase code coverage which can be commented out if they need refactoring.

I was made aware of another minor functional gap which I could see being a final (minor) addition to close out non-maintenance additions.   We keep binary indices generated by sorting on a property but we don't allow simple sorted retrieval which can leverage that index.  That should be simple and I hope to just add that tonight or tomorrow at latest.

Not sure sure the best way to 'support' 1.4 branch after we move to 2.0.0 active branch... perhaps we should elevate 2.0.0 to its own GitHub project and just duplicate crititcal fixes on that project.

**Comment by techfort** [comment]
hey guys - yes LokiJS 2.x should really be its own repository. I believe
@obsliskos and I are on the same wavelength which is that we think of the
current implementation of LokiJS as "final", which means focus is on
maintainance, bug fixes etc. LokiJS 2.x can leverage all the lessons learnt
and a great deal of the concepts explored, but I would write Loki's code in
a radically different way nowadays.

**Comment by Viatorus** [comment]
Thank you for your input.

To summarize:
- @Obeliskos merges the last feature for v1.4. After that, the feature section is closed. And v1.4 is just maintainance for bug fixes. 
- In the meantime @Cortys and maybe some others merging the changes from the current master to the branch 2.0.0.
- LokiJS2 will be an own repository. Naming: techfort/LokiJS2 @techfort  ?
- The branch 2.0.0 will be used as the developer branch inside the new repo LokiJS2
- After that, we redesign LokiJS2 in
  > a radically different way ;)

What should we do different/better LokiJS2? 

I updated the main post accordingly.

**Comment by obeliskos** [comment]
Ok, I think that will do it for feature additions to 1.4.x branch.  Suppose we could allow pull requests on 1.4 if end users wish to extend its lifespan but those nothing needs be brought over... we can just duplicate bug fixes.  

New 2.x repo sounds great.  I will let you guys decide how radically you want to take LokiJS2... and how you wish to verify performance during architecture changes... perhaps our benchmarks should be upgraded as well.

**Comment by Cortys** [comment]
As discussed I just merged master #528.

**Comment by techfort** [comment]
@Viatorus @Cortys @obeliskos @VladimirTechMan @alexandernst you're all invited to join LokiJS-Forge. I made LokiJS2 a repo under that organization, it seems fairer than for it to be under my personal account, given that my contribution to LokiJS is - and will be for the foreseeable future - quite limited (regrettably, time is really not on my side). We can start design and implementation discussion over at https://github.com/LokiJS-Forge/LokiJS2

**Comment by Viatorus** [comment]
Thank you. This is a good idea.
You have the honor for the initial commit. ;)

**Comment by Viatorus** [comment]
@techfort - maybe first make an initial commit to master with just a .gitignore and Readme.
We should push the V2.0.0 branch into a developer branch in the new repository.

**Comment by skbergam** [comment]
Hi there. Is LokiJS 2.0 available yet? Wondering if there is any good in-memory full-text search engine I can use for a production web site. I have less than 1,000 products to index so it's a pretty small DB.

**Comment by Viatorus** [comment]
Hello, please have a look at:
https://github.com/LokiJS-Forge/LokiJS2/tree/feature/inverted_idnex
I am still working on it (last commit does not mean last working process).

But it is still in development.
