### ISSUE TITLE
Update meta information even on bulk inserts/updates  

### ISSUE THREAD

**Issue by franferns** [techfort/LokiJS#534]
Hi , 

When inserting an array of data into a collection the meta part of each records contains no values except zero . In lokijs code the meta information is added for bulk insert only after the entire array is added. 
We need the meta data for all records to be updated even for bulk inserts . How should we go about this ?

```
if (!bulkInsert) {
        this.emit('insert', returnObj);
      }
```
We use lokijs version 1.4.1 

Regards,
Francis P.

**Comment by obeliskos** [comment]
Just so I can understand using a point of reference, I made a [loki gist](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/4d57071719b172eb006293cb5101944d/raw/0c176a202304428859a17ba193253e7791a6cfa3/metaWithInsertsAndBatches) to demo current (latest) behavior.

It looks like the only thing not updated by the time the emitted events fire is 'created' meta property when inserting.  Is that what you are referring to?  A version of 0 and revision of 0 sounds normal for insert?  Just trying to clarify that this behavior is what you are seeing as I cannot remember if any fixes were made to this since 1.41.

**Comment by franferns** [comment]
Yes. While performing a batch insert meta tags get updated with meta property updated with 0 as values to it.

**Comment by obeliskos** [comment]
Let's try that again...

I believe 2 out of 3 of those meta properties -should- be zero.  

So your request is for created timestamp to be set correctly when inserting in batch, correct?

**Comment by franferns** [comment]
Yes batch inserts should contain meta details for each record that is created date.

**Comment by franferns** [comment]
As a work around for this can we have this part of the code commented out for now in my lokijs ?  . In which case each record will have its meta information. 
```
//if (!bulkInsert) {
        this.emit('insert', returnObj);
      //}
```

**Comment by obeliskos** [comment]
Our insertMeta was not handling properly when passed arrays, that should be fixed now.  I will probably add some unit tests this weekend so this is properly rolled into our upcoming 1.4.3 release.

Feel free to try out and report any issues you find with this.
