### ISSUE TITLE
Latest NPM version 1.4.2 does not have Collection.clear(options)

### ISSUE THREAD

**Issue by paos** [techfort/LokiJS#536]
The issue with removing indices was resolved with commit #5890781, but the node package version does not have these fixes. Please publish to NPM? Thanks.

**Comment by techfort** [comment]
@paos we're testing out a few features that have already been merged into master so it could take a few days before 1.4.3 is released, @obeliskos let me know when i have the all clear on that throttlesave. @paos if this is blocking you you may want to go with the latest master rather than npm for a little while.

**Comment by obeliskos** [comment]
made a couple unrelated fixes this morning, I will probably add unit test coverage for them today or tomorrow and will let you know when that's done...

**Comment by paos** [comment]
@techfort Thanks, I did pull the latest master locally and it works out of the box so far. Looking forward for the npm release as it makes deployment easier.

**Comment by obeliskos** [comment]
@techfort : we are probably good to push out a 1.4.3 release as soon as you get time due to a bug we fixed in 4b4d3a84d493d20fc1fb5d6a81ed20b05384613b relating to #535.

We've had several other bugs reported and have been able to fix them to include in this release but I am hesitant to wait longer as the previously referenced bug is high severity.

Thanks
