### ISSUE TITLE
'$Meta' doesn't initialized when the clone is enabled

### ISSUE THREAD

**Issue by ArthurG94** [techfort/LokiJS#548]
Hello, 
I use lokijs for one of my projects with clone mode activated for the collection.
The problem is when i insert my data, the $meta doesn't generate.

After analyzing the source code, i see a problem in the 'insertOne' function.

>Collection.prototype.insertOne = function (doc, bulkInsert) {
>
>  // Some code.
>
>  //Cloning element for removing reference
>  var obj = this.cloneObjects ? clone(doc, this.cloneMethod) : doc;
>
>  // Some code.    
>
>  //Insertion in collection
>  if (!this.add(obj)) {
>    return undefined;
>  }
>
>  //Recloning element.
>  returnObj = this.cloneObjects ? clone(obj, this.cloneMethod) : obj;
>
>  this.addAutoUpdateObserver(returnObj);
>  if (!bulkInsert) {
>
>    // In the listener of 'insert' event, the $meta is generated, but because of the clone above, there can't be a reference to the collection data
>    this.emit('insert', returnObj);
>  }
>  return returnObj;
>
>};

  I dont know if there is really a bug, or if i dont understand the source code.

  Thanks

(Sorry for the 'quote', 'code' seem broken)

**Comment by obeliskos** [comment]
I know we recently fixed a bug with batch inserts not getting meta applied applied correctly in 50ec15165f93e514e12c1d244eb35fa50089fd7a.  That was done before releasing 1.4.3 so make sure you are upgraded to that version.

I don't really see any problems, what behavior are you expecting?  We attach meta by internally listening to insert ourselves in [4534](https://github.com/techfort/LokiJS/blob/2c21e656050695aba81ce83e1b6cdcc6698b3cdb/src/lokijs.js#L4534) and [4548](https://github.com/techfort/LokiJS/blob/2c21e656050695aba81ce83e1b6cdcc6698b3cdb/src/lokijs.js#L4548).

[Here is a loki sandbox gist](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/4d57071719b172eb006293cb5101944d/raw/0c176a202304428859a17ba193253e7791a6cfa3/metaWithInsertsAndBatches) which listens on events and logs the objects... if you enable cloning and re-run it works just as well.

**Comment by ArthurG94** [comment]
I use the version 1.4.3 and in i still have the problem.

I have edited the code in the sandbox for reproduce the problem.

>var db = new loki('sandbox.db');
>
>// Add a collection to the database
>var items = db.addCollection('items',{
>clone: true
>});
>
>
>var mjo = items.insert({ name : 'mjolnir', owner: 'thor', maker: 'dwarves' });
>var gun = items.insert({ name : 'gungnir', owner: 'odin', maker: 'elves' });
>
>
>logObject(db);

**Comment by obeliskos** [comment]
Your right, the object we emit the insert on is clone of data array so our internal insertHandler is run on the 'safe' clone (not the object internal to data).

Maybe we can either move insertMeta phase to 'pre-insert' phase which we currently emit actual internal data array object references (even when cloning), or modify our emitting of 'insert' event to emit with actual data[] object reference (even when cloning).  Since this is more of a policy decision do you have any opinions on this?  (Not sure if @techfort has time but maybe he could chime in as well).

**Comment by ArthurG94** [comment]
I'm not sure I understand your answer,
But for me, it is not necessary to clone the object twice, which would allow the event "insert", to create the meta in the data of the collection.

For now,
I myself create the meta before inserting in the collection

**Comment by obeliskos** [comment]
Well the idea was that if you had 'clones' option turned on, we would expose internal data references minimally if ever.

so you give us an object to insert, we need to clone it to insert into collection.  Then we give you object back with $loki and meta properties attached, but that returned object is another clone of internal object.

as far as event emitting, I have updated it to emit internal data array objects on -both- 'pre-insert' and 'insert' events now.

Since the official applying of meta is done internally by the collection listening to its own insert event, it will now update the internal data array object instance rather than some clone.

In the future if we want 'insert' event to pass clone data to listeners, we can shift our internal listener to add meta over to the 'pre-insert' event.

**Comment by obeliskos** [comment]
Hmm, I've recently had to fix this again and added some code coverage.  I'll close this but feel free to reopen if still an issue.
