### ISSUE TITLE
Better documentation with more examples

### ISSUE THREAD

**Issue by joakim** [techfort/LokiJS#549]
I keep finding myself searching the issue queue or reading the code to figure out how to build more advanced queries with Loki. Feels like the documentation isn't up to date with all of Loki's features?

Overall, I think the docs (and Loki as a project) would benefit from a revamp, maybe use a different documentation solution? I also miss more realistic examples of using Loki, queries you'd encounter if building a medium to fairly complex app. I'm especially thinking of querying nested documents (not clearly documented) and joins (can't find any documentation).

Loki feels like a great library, with plenty of power and flexibility, but I wouldn't say it's what Rich Hickey would call easy (at hand, familiar) :) The latter is probably because I'm not familiar with MongoDB type queries, but not everyone is.

I mean this only as constructive criticism, and I realise that documentation is not easy in itself. All in all I'm very happy with my choice of Loki – thanks for the great work!

**Comment by obeliskos** [comment]
Sure,  well we have evolved two methods for documentation... jsdoc and GitHub wiki and the idea is we could evolve both over time.   Not sure which format you are suggesting to change but jsdoc / closure syntax has a lot of features we haven't tapped into yet or thoroughly documented.  

Loki topics branch out like a tree so its hard to cover all pathways in a wiki but we can always grow the pages longer to cover more scenarios.

I agree about some features being less documented, probably because the people coding them didn't document or they added the feature before we had the documentation framework you see today.

As far as the join feature, this might take a while for me to re-learn as I do not use it myself but the original issue was #106 if you want to see some examples...  this is probably what I would use to document if I get time.

Dot-notation is one I had a role in so I should probably add something to wiki query examples page to cover that.

Feel free to mention any specific suggestions or topics and if anyone wants to help out and contribute to documentation feel free.

**Comment by joakim** [comment]
I was thinking of JSDoc, which the Documentation menu item on the website links to. I don't think you link to the wiki anywhere? It's actually a bit confusing that the wiki, as far as I can tell, has the same content as the tutorials in the documentation. How about removing the tutorials from the wiki and making the documentation the canonical source for code documentation and tutorials, linking to more in-depth examples and explanations in the wiki? Examples could well be gathered from issues like the one about joins.

Another suggestion would be to use a JSDoc theme that makes it easier to navigate. Did a quick search and [minami](https://github.com/Nijikokun/minami) and [docstrap](https://github.com/docstrap/docstrap) both seem nice.

Documentation is a hassle, but it's important to get it right, or user will have a bad time learning the library. Loki's documentation isn't bad, it's almost there, I guess I'm just saying it should go all the way :) Maybe I can help out when I have the time, I'll keep it in mind.

Btw, thanks for dot notation! Don't know what I would do without it.

**Comment by obeliskos** [comment]
Ah great!  Yes, I was uncertain myself about how an op worked and remembered that I should probably document those better... so I did.   

I'll keep trying to improve examples over time but those should be all the ops currently supported.

**Comment by thw0rted** [comment]
I know this has been closed for ages but as far as I can tell the "documentation" link at the top of the LokiJS site still never mentions dot-notation at all.  I had to just futz with it in the REPL and guess until I got something that worked.  As I understand it, it's also impossible to index on nested properties, so while `find({"a.b": true})` does return the correct results, it won't be as performant as looking for a top level property.  Is that still true?

Also: it sounds like LokiJS is abandoned in favor of LokiDB, but that has also been abandoned.  True?  If I'm just starting a new project, is Loki a poor choice?  If so, is there another embedded DB with similar features I should look at instead?
