### ISSUE TITLE
LokiFsStructuredAdapter + autoload?

### ISSUE THREAD

**Issue by manspaniel** [techfort/LokiJS#550]
Hi there!

I'm getting an error with what I assume (from the docs) should work?

```
const LokiDB = require('lokijs')
const LokiFSStructuredAdapter = require('lokijs/src/loki-fs-structured-adapter')

const db = new LokiDB('test.db', {
  adapter: new LokiFSStructuredAdapter(),
  autoload: true,
  autosave: true,
  autoloadCallback () {
    // resolve()
    console.log("Oh hey loaded ;)")
  }
})
```

Gives me:

```
Error: ENOENT: no such file or directory, open 'test.db'
```

How can I change the code above to get it working without error? When I use the normal FS adapter, it works like a charm :)

**Comment by obeliskos** [comment]
I think we already fixed this on master but hasn't made it to npm yet.  Can you verify latest version from GitHub works? If you want you can just update loki-fs-structured-adapter.js to test that one fix.

I think the workaround for npm 1.4.3 was to manually create/save a database first and then the autoload will work fine.

So far we have only had a few small bugs fixed since last npm release so I am inclined to wait before asking @techfort to publish a new version... feel free to request otherwise.

**Comment by manspaniel** [comment]
Hey @obeliskos thanks for taking the time to reply!

Yep, using the cloned repo rather than the current npm version fixes the problem :) It'd be great if this fixed could be published to the npm repo though! I've got an application in development at the moment and it'd be much more convenient to rely on the latest npm version rather than having to clone the git repo whenever I need to deploy.

**Comment by Kanaye** [comment]
Hi @manspaniel.

At least until the next release you could let npm fetch the dependecies from github.
``npm i --save https://github.com/techfort/Lokijs.git#fe93de2f9cfc1dc579e4ffac8f1d1a29ac012aa9``
The part after the ``#`` is the commit identifier just to make shure that if someone  ``npm install``s it in future get's a working/compatible version.
The hash I included above is the current master commit.

**Comment by manspaniel** [comment]
Thanks @Kanaye, that'll do for now :)
