### ISSUE TITLE
what is the maximum file size(database) that lokijs can handle?

### ISSUE THREAD

**Issue by mahmed0715** [techfort/LokiJS#551]
HI,
I am developing with lokijs, its good, but i need to be sure about future,
My database will grow  rapidly, like 200 entry per month, each one has ~600Byte size,
i guess in 5 years: it will become a huge,
Now question is, what is best solution over here?
what is maximum file size that lokijs can handle? and please help..
Thanks in advance

**Comment by obeliskos** [comment]
So that is (120k*12) ~1.4megs a year?

You running in node or browser?

Using your example data load 
High end using node/LokiFsStructuredAdapter can easily scale well over 600megs. (~5000 years)
Medium browser/IndexedDb might be around 120megs (~1000 years)
Low end would be browser/local storage which is usually 5mb.  (~3.5yrs)

**Comment by mahmed0715** [comment]
Thanks for reply quick,, i appreciate this..
my bad , i miscalculated/estimated my data size.
its nodejs env, each entry will be estimated 50KB, so 50KB*200*12 = 120MB per year
so next 10 years: 1200mb , is it huge for a file? 
what is best for me in this situation?

so if i understood you, 600MB is okay for go, but if bigger what would you suggest to do?
Thanks in advance..

**Comment by obeliskos** [comment]
once you get over 600 megs or so, it takes a while to save the database

when running node in using the current default heap limit of around 1.4Gigs, you are limited to around a 950meg database and at that size (on my test machine) it took 17seconds... which is why my 600 number is more recommended as it is faster and leaves more free heap for your app to use.  

if your ok with high file save/load times or if you if you distribute the db size across multiple collections (to lower save times) then you can increase the node memory limit to allow as big a database as your memory can hold.

there are node scripts in the benchmark folder called stress and destress which allow to test various numbers and sizes of collections to see how long it takes on your pc.  Crank up the numbers and/or heap limit to estimate how it will work years down the road.

**Comment by mahmed0715** [comment]
sorry for bothering one more time, (i was using a db file,)
but i cant find any solution? how could i scale? or should i use a new db file once its 600mb? 
or would you recommend to use mongodb instead?
please help, thanks in advance

**Comment by obeliskos** [comment]
not sure what your application does or what your collection structure would look like, so not sure how to advise...

if you don't need the ease and speed of using an in memory database like loki and don't mind running full mongodb then go with that

otherwise for scaling in lokijs you are mainly limited by your ram since you will need to have it in memory rather than pulling a record here and there from disk.  

if you want to read more into about our recent refactoring of this, read the first and last posts of this issue : 
https://github.com/techfort/LokiJS/issues/498
