### ISSUE TITLE
$contains/$containsNone/$cotainsAny does not return exact proper values

### ISSUE THREAD

**Issue by shashankdevp** [techfort/LokiJS#556]
Hi,

If a DB query is made using either **$contains/$containsNone/$cotainsAny**, it doest not return exact values.

For example an array contains these set of values ['1', '3', '4', '10'], and I query using $containsNone.

collection =  ['1', '3', '4', '10'];
filterList = ['1'];
collection.find({ 'Id': { $containsNone': filterList }});

The above query returns the following value ['3', '4'], whereas it actually has to return ['3', '4', '10'].

Thanks & Regards,
Shashank

**Comment by obeliskos** [comment]
Hey shashank, i'm trying to refamiliarize myself with these ops and think now is a good time to expand our 'Query Examples' wiki documentation to clarify how all the ops.  I'm going to have to figure out some of those as a go as I didn't implement a lot of them.  

@VladimirTechMan if you get some time in the near future maybe you can help fill in missing areas where you may be able to.

It seems like all of the 'contains' functions have multiple 'modes?' depending on what what you pass in and what they are being applied to.  This needs better documentation.

**I think the simpler op which may do what you are trying to do is $in/$nin?**  I am about to add documentation for $nin but I think that may be the op that would work as described.

So over the next few days I will try to add in some rough documentation of those ops to the wiki (maybe I will see if they can be included somehow in jsdocs as well).  That will hopefully establish a good documentation coverage which we can expand on until all are fully explained.

**Comment by obeliskos** [comment]
Alright so I expanded the wiki page with what I think is how many of these ops work and I think the 'contains' functions, when applied to a string property will do a substring pattern match (thus matching '1' and '10' for pattern of '1').  If your 'id' property had been an array, it would have checked for the exact string in any of the elements.  If your 'id' property had been an object, it would have checked to see if the property was defined on that object.

So I think in this example, $in and $nin are the ops you are looking for?

If you have more complete example, post that since I had to guess as your use.

**Comment by shashankdevp** [comment]
$containsNone works as you have mentioned above in my case. So I think $nin is the op which I should be using. 

Before $nin was not included in the documentation, so I had to use $containsNone. Thanks for updating the document :) 

I will try $nin instead of $containsNone.

Thanks for the update :)
