### ISSUE TITLE
Inconsistent return value of the Methods of the Resultset

### ISSUE THREAD

**Issue by Kanaye** [techfort/LokiJS#558]
Some methods of the Resultset return a reference to the resultset e.g. [sort](https://github.com/techfort/LokiJS/blob/f17963362298ee8283f6f88be1e7a33c07ecb8be/src/lokijs.js#L2795) 
other methods return a new Resultset e.g. [limit](https://github.com/techfort/LokiJS/blob/f17963362298ee8283f6f88be1e7a33c07ecb8be/src/lokijs.js#L2607-L2610).
That's inconsitent and therefore confusing behaviour.

I would recommend that either all methods return a reference or a new resultset.

**Comment by obeliskos** [comment]
Your right, my memory is that this was done that way because of the DynamicView so you could page its internal resultset without modifying it.   But around the same time we went ahead and implemented branchResultset() for DynamicView and branch() and copy() for Resultset so those should probably be called if the user needs to 'go back'.

Do you have a particular use case this is affecting you or should we possibly just fix this after researching more?   Normally we would not want to make changes that might be breaking but this would be very rare edge case assuming dynamic view doesn't depend on it.

**Comment by Viatorus** [comment]
Hello Kanaye, I think similarly about this. There are some more inconsitent in Resultset, etc... - possible developed historically. If you don't have any big issues with the current implementation of LokiJS, feel free to work with us on [LokiJS 2
](https://github.com/LokiJS-Forge/LokiJS2).

**Comment by Kanaye** [comment]
I was guessing that it's something from previous version.

@obeliskos I don't have a special use case that's broken because of this. I just stumbled across it. I'm fine if this doesn't get changed in the current Lokijs version but Lokijs2.
@Viatorus I've planed to take a look at the code of Lokijs2 when I've more time for it. I can PR for this and maybe other things I find. But that will probably not happen this month or the next.
