### ISSUE TITLE
Corrupt index after removal of documents with optional boolean attributes

### ISSUE THREAD

**Issue by FreshXOpenSource** [techfort/LokiJS#561]
We found a bug in the calculateRange function leading to a corrupt index. We have a mixed index on an optional boolean attribute. The documents without that attribute are indexed with an undefined value. The insertion and find operations on that index work correct. But if we remove documents the index get corrupted. The reason is, that the binary search in calculateRange uses the ltHelper function to determine the bounds for the linear search of values with equal attributes. The ltHelper function has a handling for "falsy" boolean attributes but the comparison in [calculateRange](https://github.com/FreshXOpenSource/LokiJS/blob/1a06dfa9c699e0aa174883c12714fbea58c599fd/src/lokijs.js#L5685) uses the strict comparison operator. On removal of a `false` value from an index with `undefined` values the bounds checking fails and the value does not get removed, leading to a corrupt index.

We circumvent this by transforming all "falsy" boolean values (lval, uval and val) to false. ([see code](https://github.com/FreshXOpenSource/LokiJS/blob/1a06dfa9c699e0aa174883c12714fbea58c599fd/src/lokijs.js#L5671-L5681))

This is maybe not the best solution, but the incremental removal is now proper handled.

**Comment by obeliskos** [comment]
I will look into this over the weekend and see if I can create an example which shows this and if there is a problem i will try to find out if it affects any other use cases.

**Comment by obeliskos** [comment]
I have recreated the problem and see the problem (similar to as you described)... I have encountered edge cases which are not working (before or with your work around, thanks by the way).

I might need to take a few days to think over and set up some unit tests so I can verify fixes fix those edge cases while not breaking existing ones.

**Comment by obeliskos** [comment]
It is taking longer to find time to carefully navigate and make these modifications but I am well underway to refactoring this to be more error tolerant and unified across all types.

Most affected are cleanup of of how undefined/null/NaN/objects/arrays are sorted and how internal calculateRange functions return ranges.

Once I am done I will need to add/update a database 'version' and if upgrading old database i will force rebuild of all binary indices to make sure they are in the order the new logic would expect.

Since employing a binary index by the very nature of 'our' binary index will imply a loosly evaluated sort order, meaning ('2', and 2 are sorted equally), I may want to add an optional second phase to indexable ops which will linearly run their hardcoded op function on all documents matched by the binary index.  This might be defined 'per op' whether this needs to be done... this would make $eq and $aeq work the same whether a binary index is defined or not.

It may take few more days but I feel as if I am over the uncertainty portion.

**Comment by obeliskos** [comment]
Ok, sorry it has taken awhile but you made me re-examine how our binary indexes handle mixed datatypes felt they weren't consistent enough.  I have made commit 342c8917ff4c1daf4d133d99d9ab434f1ef55fd5 to refactor how our binary indexes work.

To spare you the gory details, binary indices are now sorted in a sort of unified loose way where : 
- NaN is always lowest in binary index order (first)
- nulls, undefined, not defined are all equal and sorted next
- numbers or strings encoded as numbers are sorted next
- objects occur next in sort order
- strings occur last in sort order, using plain javascript string ordering

When mixed types are involved : 
- ops should return the same results now whether a binary index is involved or not
- strict $eq, and loose $aeq should work as expected
- $between op where loose numerics are involved "44.1", 2, "8", 5, "11" should return range of values as if they were all numbers.  This was a decision made more for consistency of range checks since there is no strict gt/lt.

I believe the null/not defined part of this commit is covered by the commit... anyone wishing to test out feel free to post feedback.
