### ISSUE TITLE
LokiJS simplesort issue

### ISSUE THREAD

**Issue by delhibabu86** [techfort/LokiJS#564]
Hi
I am facing an issue when trying to sort data via simplesort.Executed below example in Loki Sandbox.Both ASC and DESC have issues. 
var db=new loki('example.db');
    var users = db.addCollection('users');
    users.insert([{ name: '1391046.1141', age: 35}, { name: '20111', age: 30},{ name: '1391050.1141', age: 35}, { name: '20031', age: 30}]);
    //users.insert([{ name: '1391046.1141', age: 35}, { name: '1391036.1141', age: 30},{ name: '1391046.1140', age: 35}, { name: '1391056.1141', age: 30}]);
    var results=users.chain().simplesort('name',true).data();
   // logText('Results');
logObject(results);
 inspectObject(db)

**Comment by Viatorus** [comment]
The search results are correct. Your name property is a string. It use the default less than (<) comparator of javascript.

Have a look at this (run in JS console or node):

```javascript
'1391046.1141' <  '20111'   // true
'1391050.1141' <  '1391046.1141' // false
```

**Comment by delhibabu86** [comment]
Thanks for the clarification. Any plans to provide number sortings or do you have any recommendation to perform the same.

**Comment by Viatorus** [comment]
> From obeliskos:
>  You could use the sort() method instead and pass it your own custom sort function. It would probably look like :
>
> function mysort(obj1, obj2) {
>      // Implement your sort algorithm.
>  }
> 
>  var results = coll.chain().sort(mysort).data();

or

Store string numbers as numbers. ;)

**Comment by delhibabu86** [comment]
Thanks for your quick help

**Comment by obeliskos** [comment]
@Viatorus, @delhibabu86 : up until a few days ago i would have thought this would always be the case, but i have recently needed to revisit binary indexes and this was affected.

To make a long story short, (valid) numbers encoded within strings will be sorted according to the number they represent.  This change was made not for that functionality in itself but to ensure a more unified sorting for range ops so that string encoded numbers don't get in the way of numeric ranges.

So as of the latest commit on here (github), your original expected functionality should work.
