### ISSUE TITLE
find regex issue?

### ISSUE THREAD

**Issue by 7ammer** [techfort/LokiJS#577]
I've noticed an inconsistency with the find method when using regex to search a string. Below is an example which can be pasted into the sandbox which hopefully explains the issue. Let me know if not though.

```
//var db = new loki('sandbox');

var set1 = db.addCollection('set1');

[
'Mrs Sally Geeson',
'The Revd Sally Anne Baylis',
'Ms Sally Ann Beazley'
].forEach(function(i){
	set1.insert({ name : i});	
});

logText("Using the word 'sally' should find 'Mrs Sally Geeson' but does not.");
logObject(set1.find({ 'name': {$regex: new RegExp('sally', 'gi')} }));
logText("Using the word 'Geeson' finds 'Mrs Sally Geeson'.");
logObject(set1.find({ 'name': {$regex: new RegExp('Geeson', 'gi')} }));



var set2 = db.addCollection('set2');
[
'Mrs Sally Geeson',
].forEach(function(i){
	set2.insert({ name : i});	
});
logText("Set2 only contains item {name:'Mrs Sally Geeson'} and is used to return the array below.");
logText("Unlike the above, searching for 'sally' in this set does return 'Mrs Sally Geeson'");
logObject(set2.find({ 'name': {$regex: new RegExp('sally', 'gi')} }));

inspectObject(db);
```

**Comment by obeliskos** [comment]
I believe this is due to the 'g' part of your regex : 
https://stackoverflow.com/questions/8911542/why-does-the-g-modifier-give-different-results-when-test-is-called-twice/8911576#8911576

So can you just use the "i" flag or is there some functionality of "g" that i am missing.

Also, if you intend to include calls to $regex within any dynamic views or transforms, you might want to use an alternate syntax to ensure it will serialize (persist) correctly.  Our query examples wiki describes further : 

```javascript

// pass in raw regex
var results = coll.find({'Name': { '$regex' : /din/ }});

// or pass in string pattern only
results = coll.find({'Name': { '$regex': 'din' }});

// or pass in [pattern, options] string array
results = coll.find({'Name': { '$regex': ['din', 'i'] }});

```

**Comment by 7ammer** [comment]
Oops! Thanks for taking the time to correcting me on that one :)
Cheers for the tip too!
