### ISSUE TITLE
Hi, how to select all records?

### ISSUE THREAD

**Issue by bromoapp** [techfort/LokiJS#579]
I'm sorry to ask such question here (not an issue)
But I checked on your tutorial regarding Query, and I couldn't find any sample that shows how to select all available records and sort it based on column value.
Is such query available?

Thanks

**Comment by obeliskos** [comment]
Calling find without a filter object returns all rows, in order to sort you need to use chaining such as : 

```javascript
var result = users.chain().simplesort("age").data();
```

We now have many quickstart examples in the examples folder, so i have updated our Query Examples wiki page to reference them.

https://github.com/techfort/LokiJS/blob/master/examples/quickstart-core.js and
https://github.com/techfort/LokiJS/blob/master/examples/quickstart-chaining.js
https://github.com/techfort/LokiJS/blob/master/examples/quickstart-transforms.js
https://github.com/techfort/LokiJS/blob/master/examples/quickstart-transforms.js

**Comment by greaterking** [comment]
Thanks was looking for this as well but didn't find it in the [docs](https://rawgit.com/techfort/LokiJS/master/jsdoc/Collection.html#find) ...perhaps a note should be made.
