### ISSUE TITLE
React native

### ISSUE THREAD

**Issue by sm2017** [techfort/LokiJS#590]
Can I use LokiJS with React native ?

**Comment by sm2017** [comment]
???????

**Comment by obeliskos** [comment]
I have not tried but it expect it would work... 

You may need to pass [env: 'BROWSER'](https://rawgit.com/techfort/LokiJS/master/jsdoc/Loki.html) option to loki constructor.

Eventually you might want to adapt a simple [AsyncStorage](https://facebook.github.io/react-native/docs/asyncstorage.html) persistence adapter to use instead of synchronous local storage.  I could help with that if you want.
