### ISSUE TITLE
Save issue with large data set

### ISSUE THREAD

**Issue by heffrey78** [techfort/LokiJS#591]
I'm working on an Electron project using LokiJS for the database solution. I'm attempting to save a fairly large dataset in an import operation. The application has forecasts which are basically just dates. Each forecast has a collection (15,000+) of forecast locations that are lat/lon pairs. Each forecast location has 15+ measurements. With 39+ forecasts per import, we're looking at over 9,000,000 data points. Due to the structure of the import data, i first save a forecast and then get it's $loki which i use as a "foreign key" for the forecast locations. I accumulate all of the locations and measurements for the forecast and save them all at once. I've tried both saving the locations one at a time, getting their $loki to set as the FK for the measurements and then saving all of the measurements and I've tried saving the measurements as an array inside of the location allowing me to save all of the locations in bulk. My current code is below. My problem is that when I get to about the 9th forecast, the json file stops growing at about 240 MB. Using Node, I had originally thought that I didn't need an adapter. I've tried both and had similar failures. Also, when I use an adapter, if I use a path to loki.db, I get "Uncaught Exception: TypeError: Cannot read property 'collections' of null at Interace.<anonymouse>.... So I'm stuck just using 'loki.db' which creates the new db file in a non-persisted folder (Electron wants things under the Resource folder). Can you make any suggestions? 

```
//ForecastLocations.js
ForecastLocations.prototype.save = function () {
  for (let fl in this.collection) {
    if (this.collection.hasOwnProperty(fl)) {
      let forecastLocation = this.collection[fl];
      forecastLocation.save();
    }
  }
}

//ForecastLocation.js
ForecastLocation.prototype.save = function () {
  if (!this.id) {
    let result = Database.forecastLocations.insert({
      forecastId: this.forecastId,
      lat: this.lat,
      lon: this.lon
    });

    this.id = result.$loki;
  }

  for (let m in this.measurements.collection) {
    if (this.measurements.collection.hasOwnProperty(m)) {
      let measurement = this.measurements.collection[m];
      measurement.forecastLocationId = this.id;
    }
  }
}

//Measurements.js
Measurements.prototype.save = function(){
  for (let m in this.collection) {
    if (this.collection.hasOwnProperty(m)) {
      let measurement = this.collection[m];
      measurement.save();
    }
  }
}

//Measurement.js
Measurement.prototype.save = function () {
  if (!this.id) {
    let result = Database.measurements.insert({
      value: this.value,
      forecastLocationId: this.forecastLocationId,
      measurementTypeId: this.measurementTypeId
    });

    this.id = result.$loki;
  }
}

//Processor.js
Database.open();

//...processing...

function saveData(forecast) {
    forecast.forecastLocations.save();

    for (let fl in forecast.forecastLocations.collection) {
        if (forecast.forecastLocations.collection.hasOwnProperty(fl)) {
            let forecastLocation = forecast.forecastLocations.collection[fl];
            forecastLocation.measurements.save();
        }
    }
}

//Database.js
Database.open = function () {
    return new Promise(function (resolve) {
        //let dbPath = path.join(__dirname, "../../../resources/db/loki.db");

        //if(!fs.existsSync(dbPath)){
        //   fs.writeFileSync(dbPath, '');
       // }

        let adapter = new lfsa();
        Database.lokiDb = new loki('loki.db', { adapter: adapter, autoload: true, autoloadCallback: function(){loadDatabase(resolve)} });
    });
}

function loadDatabase(resolve){
  Database.forecasts = Database.lokiDb.getCollection('forecasts') || Database.lokiDb.addCollection('forecasts', { unique: 'forecastDate' });
            Database.forecastLocations = Database.lokiDb.getCollection('forecastLocations') || Database.lokiDb.addCollection('forecastLocations', {indices: ['forecastId']});
            Database.measurements = Database.lokiDb.getCollection('measurements') || Database.lokiDb.addCollection('measurements', {indices: ['forecastLocationId']});
}
```

**Comment by heffrey78** [comment]
I've decided to not try to be so tabular with my save. I'm able to save the highest level objects with children nested. It's performant and better yet not breaking.

**Comment by obeliskos** [comment]
Alright, have you tried using the [LokiFsStructuredAdapter](https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters#an-example-using-fastest-and-most-scalable-lokifsstructuredadapter-for-nodejs-might-look-like-)?  I would try either that or the Partition Adapter + your current adapter.  Once you get over around 128megs of saved file size, it is best to partition or use a streaming adapter like LokiFsStructuredAdapter.... otherwise it requires a lot of RAM to serialize in one shot.

**Comment by heffrey78** [comment]
I did a little bit with LokiFsStructuredAdapter, but had some issues. I might revisit if I have more issues. Currently, I'm saving the forecast object with its children as one record and it's working fine. I am still over 200 MB, so your 128MB warning makes me a bit nervous.

**Comment by obeliskos** [comment]
You are saving a single 200 MB 'record'?  What is a record... a 200mb document or data file?

How many documents in your collection and how many separate collections?

Yes in javascript serialization there is usually JSON.stringify and JSON.parse.    As you start passing more 'deep' objects to these recursive methods they starting using up an exponential amount of RAM to perform serialization (via many recursions and string concatenations).  If you pass a whole lokijs database at once to be serialized, you start requiring many times more RAM than the original database itself.  

LokiJS in a node environment using the LokiFsStructuredAdapter can serialize one document at a time and send that to buffered file stream.  Ram overhead is much lower... assuming you don't have a 200MB document in which case... fix that!

Partitioning adapter probably isn't preferable for node since you have LokiFsStructuredAdapter, but it can be used with any other basic persistence adapter like LokiFsAdapter, LokiIndexedAdapter, etc. to limit amount serialized at once to a single collection rather than entire database.

**Comment by heffrey78** [comment]
No, it's not a 200 MB record. That is the entire size of the json file. That said the lion's share of the size is taken up by a relatively small set of records (40-ish). Each one of these records has 15K child objects, each of which have 15 child objects. Previously, I had saved these all in their own tables, and that's where I ran into problems. It seems to actually work better to save them nested than in separate records.
