### ISSUE TITLE
LokiPartitioningAdapter loadDatabase -- signal "empty but OK"

### ISSUE THREAD

**Issue by retorquere** [techfort/LokiJS#594]
For a normal persistence adapter I can signal "source to load not found, please initialise an empty database" by given the callback `null` or `{}` (`null` used to work, but it seems I must now pass `{}`). If I wrap this adapter in a LokiPartitioningAdapter however I get

```
SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data
```

**Comment by obeliskos** [comment]
I think your right, we were not gracefully handle loading a partitioned database the first time (when it doesn't exist)... it would throw an error.  Our LokiMemoryAdapter also did not handle our 'no database yet' condition.

I added a commit to master which i think fixes this so that we use the following rules for interpreting an adapter's loadDatabase callback result : 
- if the adapter returns falsy values like null/undefined/false we consider the database did not exist, but do not treat this as error... we will keep the existing database as it was constructed and if autoload and autoloadCallback are involved, we will continue to run the autoloadCallback
- if the adapter returns an instanceof Error we will raise it as an error
- if the adapter returns an object we will loadFromJsonObject
- if the adapter returns a string (serialized database) we will parse to an object and loadFromJsonObject

Let me know if that works for you and if you still need answers to other #595 post.

**Comment by retorquere** [comment]
That works for me. Can the LokiPartitioningAdapter do transactions? I'm a little worried about partial saves. #595 would allow me to do transactional saves in the exportDatabase (and yes I'm still very much interested in understanding reference mode adapters)
