### ISSUE TITLE
Inconsistent behaviour with insert() followed by saveDatabase()

### ISSUE THREAD

**Issue by dgfreecodecamper** [techfort/LokiJS#600]
```javascript
const newApp = dbhelper.getFormattedApp(newAppInfo, function(newApp){
  db.loadDatabase({}, function(){
    db.getCollection('apps').insert(newApp);
    let nApp = db.getCollection('apps').chain().find({ 'application':newApp.application }).data();
    console.log(nApp[0].num + ' written to db $loki id reported as: '+nApp[0].$loki);
    db.saveDatabase(function(){
      req.session.assignment = helper.getOffName(newApp.assigned);
      res.redirect('/new');
      return;
    });
  });
});
```

In the above code I create a new object, insert into the database and then call db.saveDatabase as per the documentation. This works most of the time however sometimes the insert does not persist and upon a subsequent object being written the database reports the same id as the previous one. This is illustrated in the screenshot below:

![capture2](https://user-images.githubusercontent.com/17178347/29491223-1b9e64f4-854c-11e7-9776-1d780392c5ee.JPG)

As can be seen on the left the console.log reports the $loki id following the insert function call, but this does not persist consistently resulting in objects being missing highlighted on the right in yellow.

**Comment by obeliskos** [comment]
Can you tell if this is a timing issue?  How much time is elapsing between each load/insert/save.  I'm wondering if there are overlapping calls.

Ideally I would think you would not load every time, and additionally I would [autosave](https://github.com/techfort/LokiJS/blob/a2950436186fafec2a6b434e5c51cc125a42b2eb/examples/quickstart3.js) on interval rather than explicitly to keep this handler efficient.  

So you keep db instance global (outside handler), do you have a purpose for loading and saving manually or can we change that?

LokiJS supports load and save throttling so it should [drain save queue before loading](https://github.com/techfort/LokiJS/blob/a2950436186fafec2a6b434e5c51cc125a42b2eb/src/lokijs.js#L2450) unless you have disabled throttled saves.  

You aren't reinstantiating the db object elsewhere are you? Or are you just repeatedly reinvoking loadDatabase and saveDatabase on the same 'db' loki instance?

**Comment by dgfreecodecamper** [comment]
I reorganised the code so that there is now only one call to the loadDatabase function. This seems to have cleared the issue. Thank you for the feedback and the suggestions that help me better understand what I was doing wrong.
