### ISSUE TITLE
Dynamic View vs Find

### ISSUE THREAD

**Issue by marcgauthier** [techfort/LokiJS#605]
I need to display a dashboard and I have about a 1000 queries that need to be run to verify what need to be display.  I was wondering if it would be more efficient to do run a query every x second and run all my Queries about 600-1000 or if LokiJS Dynamic view would be efficient with 1000 view in memory?  

The query only return no more than 1 item and the database would hold between 50K to 100K items.

**Comment by marcgauthier** [comment]
I met run a function every x second and run all my Queries.

**Comment by obeliskos** [comment]
Dynamic views are useful if you can 'share' common filtering across multiple queries.  I would not run 1000 different dynamic views just because it would slow down inserts/updates/removes because each dynamic view is notified to (re)evaluate them.

Can you describe (in general) what your queries look like?  Are they all querying the same properties or different ones?  Does each query just query against 1 column or multiple? Are you using find filters or where filters?  Do you already have any binary or unique indices setup for that collection?

If you can 'share' common filters across several queries, I might use a dynamic view. I would be curious about measuring performance without them first though.
