### ISSUE TITLE
Can not use mongo/mongoose ObjectId.

### ISSUE THREAD

**Issue by qiulang** [techfort/LokiJS#606]
I want to save my search result from mongo into Lokijs (as cache). My document uses the ObjectId, i.e. _id.  When I tried to find them with ObjectId('string') in Lokijs, I got the following error. But when I check my Lokijs data, I did see the ObjectId was stored there. 

Unhandled rejection TypeError: fun is not a function
    at Resultset.find (/Users/qiulang/Project/customer_service/node_modules/lokijs/src/lokijs.js:3205:19)
    at LokiEventEmitter.Collection.findOne (/Users/qiulang/Project/customer_service/node_modules/lokijs/src/lokijs.js:5907:33)

**Comment by Viatorus** [comment]
Can you please post the query of the find method call?

**Comment by qiulang** [comment]
```
        mongoDB.find('user').then(function(users){
            _.each(users,function(e){
                var data = e._doc;
                data.id = data._id.toString();// this is the kludge solution I used now
                lokiDB.insert(data);
            });
            var id = ObjectId("595c837597e60c5d2403a1f1");
            var result = lokiDB.findOne({id:"595c837597e60c5d2403a1f1"});
            //Then crash with the error
            result = lokiDB.findOne({_id:id});
        });
```

**Comment by obeliskos** [comment]
Can you tell me what console.log(typeof id) would log?

**Comment by qiulang** [comment]
console.log(typeof id) of course shows "object" because ObjectId is bson object? What were you trying to find ?

**Comment by obeliskos** [comment]
so if your 'working' version you are passing string literal "595c837597e60c5d2403a1f1"?
and in your crashing version you are passing id var which is object?
can you extract convert the object instance to that string literal (possibly toString it like you did on insert) ?

**Comment by qiulang** [comment]
I am reporting an issue (in my opinion) because I hope loki can support ObjectId. But I can't figure ou t your point here.

**Comment by obeliskos** [comment]
My only point was a simple but not obvious one (sorry was in a rush).  My point was just that comparing (different) object instances doesn't work with pure javascript : 
```javascript
var obj1 = { a:1, b:2 };
var obj2 = { a:1, b:2 };
console.log(a === b); // logs 'false'
console.log(a == b); // logs 'false'
```

So mongo object id are likely prototyped objects that override toString() to give you that simple, portable hex string.

So, will your objects ever find their way to mongo (where mongo will need them in expected format) and do you save your loki database or just use in-memory?

When lokijs serializes, it will do a JSON.stringify on your objects and when it reloads them, they will have lost their prototype unless you implement a custom inflater to recreate them properly.

If just in-memory, you might try : 
```javascript
result = lokiDB.findOne({ _id: { $aeq, id.toString() }});
```

So when you don't include an 'op' in your find objects, the implicit operation is $eq which in lokijs is 'strict' equality.  In the above i am using 'abstract equality op' which is similar to ==.  Since _id is prototyped object but id.toString() is type 'string', javascript should coerce _id to string and perform its abstract equality successfully.

If persistence is involved and you don't expect to pass back to mongo, you may want to query against properties on that object using dot notation so that it will work not only before you save but after as well. If you are going that route, i can provide more options.

**Comment by qiulang** [comment]
I guess my complaint is more about the crash. If I don't use $aeq, no result is expected but the crash is not.

**Comment by obeliskos** [comment]
Yes, we might be able to provide a more meaningful error but object on right hand side of filter object expression usually means subexpression.  Maybe the object's 'constructor' property could be used.

Just out of curiosity, what is the value of : 
```javascript
console.log(data._id.constructor.name);
```

If it's a meaningful name we could possibly fallback to toString() in certain cases.

**Comment by qiulang** [comment]
“ObjectID”  actually I am always confused the difference between ObjectId & ObjectID

**Comment by obeliskos** [comment]
It would seem there is none.  So the mongo-client driver requires the 'bson' npm package which [defines ObjectID here](https://github.com/mongodb/js-bson/blob/1.0-branch/lib/bson/objectid.js).  Then it aliases ObjectId to it on line 69.  They also override both toString() and toJSON() methods to invoke and return toHexString() which gives your 24byte hex string.

So in loki you may insert a (mongo retrieved) doc which has _id field as a prototyped ObjectID class in memory, but when we save it the toJSON will convert it to 24 char hex string.   If you need to persist loki db and reinstance those properties as ObjectID you could use custom inflator and pass the hex string to ObjectID constructor.

**Comment by qiulang** [comment]
I finally figured out the reason for the crash. It is because I use mongoose and the result is actually a mongoose object which caused the crash. When I use lean option to return the plain javascript object, no crash then (of course without $aeq, not result then).

**Comment by qiulang** [comment]
Sorry my mistake, with the lean option, still crash. I planned to just delete mine previous comment. But maybe you have noticed it so I am adding this new comment
