### ISSUE TITLE
Clarification on `databaseVersion` in 1.5.0

### ISSUE THREAD

**Issue by artch** [techfort/LokiJS#623]
In 1.4.2 release there was a `databaseVersion` property which can be fetched from the JSON file. We used this property to track and update our own database schema. But in 1.5.0 release the fetching code has been [commented out](https://github.com/techfort/LokiJS/blob/master/src/lokijs.js#L1527-L1531):
```javascript
      // restore database version
      //this.databaseVersion = 1.0;
      //if (dbObject.hasOwnProperty('databaseVersion')) {
      //  this.databaseVersion = dbObject.databaseVersion;
      //}
```

Could you please clarify is it intended or just an oversight? Can we officially use this property for our needs, or have to store our schema version separately?

**Comment by obeliskos** [comment]
It has traditionally been used internally to handle upgrade scenarios as we do not update it unless we need an upgrade path.  If we load a database in an older format, and it needs some 'upgrade' logic, we will instantly upgrade (in memory) on load.  This won't actually get saved unless the database is saved.

I suppose we have overlooked the possibility of an older loki loading a newer database version, is that the situation you are encountering?  Not sure the proper path to take there, either throw an error without loading or try to load and log warning.

We could add meta property at database level and possibly collection level to allow you to store whatever (serializable) meta you want.

If you would like a solution not requiring upgrading your lokijs, you might try to setup some meta within a collection you know will exist using transforms, [like I described for another situation here](https://github.com/techfort/LokiJS/issues/602).  We have had collection transforms for a long time, so that method should work on older versions.
