### ISSUE TITLE
Transform mapReduce with parameter is broken

### ISSUE THREAD

**Issue by fi4sk0** [techfort/LokiJS#624]
Hi everybody, 

I think mapReduce is broken when used with a parameter. Consider the following example (you can copy/paste it to the [sandbox](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm)):

```javascript
var db = new loki('sandbox.db');

// Add a collection to the database
var items = db.addCollection('items');

// Add some documents to the collection
items.insert({ name : 'mjolnir', age: 5});
items.insert({ name : 'tyrfing', age: 7});

var mapper = item => item.age 
var reducer = values => values.reduce((a,b) => a + b, 0)

var tx = [{
    type: 'mapReduce', 
    mapFunction: mapper, 
    reduceFunction: reducer
}]

logObject(items.chain(tx)) // Works, returns 12
logObject(items.chain(tx, {foo: 5})) // Throws an error
```

The problem is caused in line 67 where `JSON.stringify` drops fields that yield a function.
https://github.com/techfort/LokiJS/blob/c19674bd1e46041848c3aa58ca5fc423bb7cc7d8/src/lokijs.js#L67
which is only executed when there is a parameter object passed in together with the transform.

Unfortunately, I haven't come up with a good solution for this except for a more sophisticated deep clone algorithm, that leaves functions in the transform objects as they are. Anybody with thoughts on this issue?

Cheers

**Comment by fi4sk0** [comment]
I have a workaround for the clone function. In case it's a mapReduce, I copy the functions from the original object. Unfortunately this should also be done for `sort` and `where` and then it feels like a clumsy solution. 

So just for reference:
```javascript
// iterate all steps in the transform array
for (idx = 0; idx < transform.length; idx++) {
    // clone transform so our scan and replace can operate directly on cloned transform
    clonedStep = JSON.parse(JSON.stringify(transform[idx]));

    // in case this step is mapReduce, revive functions that might have been dropped while cloning
    if (clonedStep.type === "mapReduce") {
        if (typeof clonedStep.mapFunction === "function") {
            clonedStep.mapFunction = transform[idx].mapFunction
        }
        if (typeof clonedStep.reduceFunction === "function") {
            clonedStep.reduceFunction = transform[idx].reduceFunction
        }
    }
    resolvedTransform.push(Utils.resolveTransformObject(clonedStep, params));
}
```

**Comment by obeliskos** [comment]
Thanks for the very descriptive repro...

So transforms are useful for : 
- substituting parameters which change frequently between execution, and
- substituting parameters which are not serializable so that the transform can be saved into database

I had coded an either/or, expecting that if you were using parameters you had extracted all nonserializable values into params, which your example does not.  Your example is valid i just did not consider that.

So if you understand that you can't persist those transforms as named transforms, saved along with the database, then your example did break as you pointed out.

Loki needs recursive parameter substitution to handle deep nesting of 'find' query objects which could be any number of levels deep.  That is why I was using the 'deep' parse-stringify method.  To accommodate both non-serializable step properties as well as deeply nested parameter substitution, I made up a new 'shallow-recurse-objects' clone method which shallow clones an object and then for each top level property of type "object" with constructor.name "Object" I will recursive shallow clone that (literal).

I think that should work for all transform steps or can be refined later but let me know if that works for you or if you foresee any issues with that method.

That fix should be committed to github now if you want to test it out.

**Comment by fi4sk0** [comment]
Hey @obeliskos, 

I looked through your code and it's working for me and I think your algorithm perfectly fits. Thanks for solving that so fast! You and lokijs rock!
