### ISSUE TITLE
$containsAny does not work with integer fields

### ISSUE THREAD

**Issue by ThomasPCG** [techfort/LokiJS#632]
$containsAny criteria does not work with integer fields of a document. As I'm relatively new to LokiJS, please kindly enlighten me if there's another criteria for dealing with integer fields. Didn't find anything in the documentation that mention that it shouldn't be used for integer fields.

Here's an example to illustrate:

```
    var temp = __lokiconnector.getCollection("temp");
    temp.insert({ id: 1, name: "Sample-1101", level: 18 });
    temp.insert({ id: 2, name: "Sample-1102", level: 22 });
    temp.insert({ id: 3, name: "Sample-1103", level: 18 });
    temp.insert({ id: 4, name: "Sample-1104", level: 15 });
    temp.insert({ id: 5, name: "Sample-1105", level: 31 });
    temp.insert({ id: 6, name: "Sample-1106", level: 27 });
    temp.insert({ id: 7, name: "Sample-1107", level: 33 });

    var suitableLevel = [18, 22];
    var suitableNames = ['Sample-1102', 'Sample-1105'];

    var workingResult = temp.find({
        name: { '$containsAny': suitableNames }
    });

    var buggyResult = temp.find({
        level: { '$containsAny': suitableLevel }
    });

    console.log(JSON.stringify(workingResult)); //Returns 2 items: Sample-1102 and Sample-1105
    console.log(JSON.stringify(buggyResult)); // Returns []. It should return Sample-1101, Sample-1102, Sample-1103 if it's working.
```
Any ideas?

**Comment by obeliskos** [comment]
I think the op you want to use is $in which should be used when the property is not an array but the compare values are.

Our [wiki page](https://github.com/techfort/LokiJS/wiki/Query-Examples#find-operator-examples-) was a little confusing, so I added more info to $in, $contains, and $containsAny descriptions.

$contains and $containsAny are mainly useful with strings and there multiple modes of use are why the string comparison seemed to work.

>When typeof property is : 
>- string: it will do a substring match for your string (indexOf)
>- array:  it will check for 'value' existence in that array (indexOf) 
>- object: it will check to see if your 'value' is a defined property of that object

So because your property was a 'string' it would just run substring matches on your value array.  If your property had been an array it would return matches where any of its elements were exactly represented within compare values (no substring match).  I won't cover object scenario as I don't feel it is relevant to your issue.

Let me know if that is clear or if you think our updated wiki descriptions could still be clearer there.

**Comment by ThomasPCG** [comment]
Now that makes sense. I have used $in instead and it now works perfectly.

Thanks!
