### ISSUE TITLE
Column comparisons

### ISSUE THREAD

**Issue by radex** [techfort/LokiJS#636]
I want to make a query that matches all records where, say, `record.oneColumn > record.otherColumn`. This can be useful, for instance, when having two columns with timestamps and you want to fetch records where "last change is newer than last seen".

Currently, I believe it's only possible using `where` queries, but that's undesirable for me because:

- it's tricky when Loki is moved to separate web worker (can't pass functions between threads)
- harder to test (when you have, say, your own model methods/helper functions that you want to check if they produce the right Loki queries)
- it's hard to mix with AND/OR queries

I'm thinking of a declarative syntax, say:

```
.find({ column1: { $gt: { $column: 'column2' } } })
```

or:

```
.find({ column1: { $column: [
  'column2',
  { $eq: 'column2' }
] } })
```

or something of that sort.

**I'm willing to dig into the code and implement the feature myself.** … but I could use a few pointers as to how to approach the problem, and where to start.

**Comment by obeliskos** [comment]
Sorry for the delay... busy time of the year.

This feature would require reworking a critical path in our Resultset.find() function.  As such this might be best implemented on LokiJS2.

All of our query operators currently work at the property level.  And those property level functions only accept 'source value' and 'compare values'.  The exception(s) being $and and $or ops which are compositional constructs which hierchically wrap other 'property level' expressions.  

This would not be able to utilize indices since the indices are property based... so to execute this compare op we would be doing a full array scan.  Planning for this could thus be compartmentalized to our unindexed LokiOps or equivalent.

Your syntax is that it looks great however it may require overhaul of query pipeline which would require much planning, testing, and benchmarking to ensure the critical path is not degraded for this newly added 'edge' case.  

So a (simpler?) solution might be to create a new class of query ops which are based on object reference and configuration object rather than 'source value' and 'compare value'.  An example of utilizing an object level op might look like : 
```javascript
coll.find({ column1: { $$gt : { $column: 'column2' } } })
```

That looks very similar to your expression except that we push final unwinding to the op. So an implementation of LokiObjectOps.$$gt might look like : 
```javascript
var LokiObjectOps = {
  $$gt : function(val, obj, config) {
    var val2 = obj[config.$column];

    return gtHelper(val, val2, false);
  }
}
```

Then we would just need to 'shim' detection of these new ops into Resultset.find() and pass parameters accordingly.  Whether we pass configuration object or value is debatable, with an object we could expand out to more (unindexed) use cases though.

**Comment by Viatorus** [comment]
I like the idea of  the `$$gt` syntax.

Could we simplify it to:

```js

coll.find({ column1: { $$gt :  'column2' } })

```

?

**Comment by obeliskos** [comment]
Sorry, I missed this... 

Sure, since the unwinding is done at the op level... if $$gt is passed a string we could treat as column name or if we add more 'overloads' we could detect if passed an object and access as many configuration properties as needed.

**Comment by radex** [comment]
Hey, thank you for the pointers.

I won't be able to work on this in the near future, but I will need this feature and intend to implement it in a few months, so please let this issue stick around :)
