### ISSUE TITLE
Binary index not automatically rebuilt after repeated updates

### ISSUE THREAD

**Issue by claudiosdc** [techfort/LokiJS#639]
I had a database with a collection that had a binary index in a boolean (I am not sure if the type of property is relevant though) property, and I noticed that, after updating a few documents and changing the value of that property, the find() method would not return the expected record set when querying by that specific property. When that happen, if I call the ensureIndex() method on the collection forcing the rebuild of the index, everything seems to be fixed and the find() method runs correctly once again.
I noticed that same erratic behavior with both Lokijs version 1.3.16 and the latest 1.5.1.
I have put together a simple Node.js test program (source code attached) that can be used to demonstrate this issue.
If you run the TestLokiDbIndex.runTest() method with no arguments, the error manifests itself, and you should see a few asset messages at the console. On the other handle, if the TestLokiDbIndex.runTest() method is run by passing true as its only argument, forcing ensureIndex() to be called after the document updates, the error does not take place.
[TestLokiDbIndex.zip](https://github.com/techfort/LokiJS/files/1594805/TestLokiDbIndex.zip)

**Comment by obeliskos** [comment]
Sorry its taken me so long to get around to this... this required focused deep tracing and diagnostics which I usually do in browser.

So I think you are running into a valid 'issue' but I am not sure the best way to handle this as of yet.  Since I don't expect to have a fix in today I will just explain and allow you to confirm/discuss.

So we added 'adaptive' binary indices which automatically 'recalculate' the index on every insert/update/remove as being faster than 'full lazy rebuild' on the first use (find) of that index.  Adaptive binary indices also prevent 'worst case' performance scenarios where you frequently mix updates and finds (where its constantly doing lazy full rebuild on dirty index).

In your example, you have :

```javascript
TestLokiDbIndex.prototype.allocateRows = function (amounts, fixIndex = false) {
// ...
        foundDocs.forEach((doc) => {
            doc.allocated = true;
        });

        this.coll.update(foundDocs);
    }
// ...
};
```

It seems there is an issue with updating documents in batch where properties being adaptively binary indexed are modified (and you are not cloning).   *whew*

I believe if you modify the above to the following :
```javascript
TestLokiDbIndex.prototype.allocateRows = function (amounts, fixIndex = false) {
// ...
        var self = this;
        foundDocs.forEach((doc) => {
            doc.allocated = true;
            self.coll.update(doc);
        });
    }
// ...
};
```

That should work correctly as each adaptive update can peer at neighboring index values to determine its new correct location within the index.

I expect that we may need to alter our collection.update() update to, upon detection of being passed an array, iterate the array (as it does now) but afterwards do a full index rebuild using ensureIndex() as you are doing... making batch updates slower in scenarios outlined in the (*whew*) comment above.  **Therefore I would recommend immediate updates rather than batch updates when you are updating docs where binary index property potentially has changed and you are not cloning.**  I am uncertain whether unique indices exhibit this same behavior, perhaps unit tests should be created surrounding both before implementing solution(s).

We and/or others can discuss this over the next few days or so and I may have time to look into solutions/workarounds after that.

Thanks for pointing this out... I do not want the current functionality to allow this edge case inaccuracy.

**Comment by obeliskos** [comment]
fixed.
