### ISSUE TITLE
Unique pair constraints ?

### ISSUE THREAD

**Issue by digitalnature** [techfort/LokiJS#646]
Are unique pairs supported?

```
files.addCollection('files', {
   unique : ['path', '$loki']
});
```

I tried paring the ID with another column, but it doesn't seem to work, I still get errors about duplicates on the path column

**Comment by obeliskos** [comment]
Currently the unique constraints operate on a single column only but $loki should never be indexed as it should always be unique.  I believe you can add multiple unique keys but they act independently.

So 'path' isn't unique on its own?

**Comment by digitalnature** [comment]
It's a relative path, from a zip file. Actually I needed path _ zip_id, where zip_id is the $loki column from another collection

**Comment by Viatorus** [comment]
I think using $loki as custom column is a bad idea since $loki is used internal by LokiJs itself.

**Comment by caligo-erik** [comment]
I bumped into this, since I was looking to use a combined unique key.
I agree with the others that you should leave $loki alone, but it would be great if LokiJS implemented a combined unique key functionality
Quick and dirty work around: create a new property which concatenates your relevant ids, and use that as single unique id.
Otherwise you can still perform your own duplicate checks before upserting the data.
