### ISSUE TITLE
Example of JOIN

### ISSUE THREAD

**Issue by Extarys** [techfort/LokiJS#650]
Sorry, this isn't really an issue but I'm having trouble making a join request and I would like to know if it's possible to have a simple example?

SO didn't seem to answer my question.

Thanks for your time.

**Comment by obeliskos** [comment]
I will work on a more complete one later today or tomorrow, Seems this method is best called where left is many and right is one (so the join column is kind of like a fk for right).  

Here's my example so far (which you can past into [LokiSandbox](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm)), seems I will have to use resultset mapreduce instead of eqjoin map function to combine all tags into single array.  Your use case may vary and this might be enough to get you going.

```javascript
var db = new loki('sandbox.db');

// Add a collection to the database
var users = db.addCollection('users');
var tags = db.addCollection('tags');

users.insert({ name: "odin", age: 1000 });
users.insert({ name: "frigg",age: 800 });
users.insert({ name: "thor", age: 35 });
users.insert({ name: "loki", age: 29 });

tags.insert({ tag : "knowlege", name: "odin"  });
tags.insert({ tag : "sorcery", name: "odin" });
tags.insert({ tag : "runes", name: "odin"  });
tags.insert({ tag: "foreknowlege", name: "frigg" });
tags.insert({ tag: "shapeshifter", name: "loki"  });

var mapfun = function(left, right) {
  return {
    name: left.name,
    age: right.age,
    tag: left.tag
  };
};
var result = tags.chain().eqJoin(users, "name", "name", mapfun ).data();

logObject(result);
```

**Comment by obeliskos** [comment]
I added a [better example to jsdocs](https://rawgit.com/techfort/LokiJS/master/jsdoc/Resultset.html#eqJoin).

**Comment by Extarys** [comment]
Awesome thanks !
