### ISSUE TITLE
Loki FS Structured Adapter problem

### ISSUE THREAD

**Issue by ohenepee** [techfort/LokiJS#653]
I created a database with LokiFSstructuredadapter and `autoload` with `autoloadCalback`... I've setup up 4 collections. When I start my app and insert data into the db, then close the app and start again, I get `Error: ENOENT: no such file or directory, open /home/userOne/serv/serv.db.1`

I don't see any `serv.db.1`, so why can't I move on?

I stumbled upon this though
```
// Since our LokiFsStructuredAdapter is partitioned, the default 'quickstart3.db'
// file will actually contain only the loki database shell and each of the collections
// will be saved into independent 'partition' files with numeric suffix.
```

**6 hours later into the future [ in other words: EDITED 6 hours after opening this issue ]**
I found something interesting... I mostly check for `null` and create my collections this way
```
Notices = db.getCollection("notices")
if (Notices == null) {
	Notices = db.addCollection("notices", {indices: ["for","datetime"], unique: ["for","datetime"]})
	db.saveDatabase() // Attention Here <<<<<<<<<<<<<<<<<<<<<<<<<
}

Notices.on("error", e => console.error("LOKI ERROR: ", e.message))
Notices.on("insert", () => db.saveDatabase())
Notices.on("update", () => db.saveDatabase())
```

As you can see, after adding the collection I save... and if I have 4 or even 10 collections being added on program startup; I save all of them right after `addCollection`... now this what was causing the problem. When I commented out almost all the `saveDatabase` and left only the one for the last collection creation, all partitions got created. **STRANGE!** (In other words if I had 10 collections to be created I only saved after `addCollection` for the 10th collection). Somehow only the first collection or partition (`serv.db.0`) got created along with the shell (`serv.db`)... the other collections (partitions) didn't get saved nor created even in the shell (`serv.db`). Maybe its because I added some data to that particular collection on program's first-run _(first-run only)_.

Why? Is it a crime to save on every `addCollection` (assuming its not necessary)?

**Comment by obeliskos** [comment]
Sorry for the delay, I will respond as best as I can without knowing if this is still an issue...

Async adapters add slight complexity to coding pattern, but without the async saves and loads would grow to be intolerable once the database grows over a certain size.  Since you have opted to use the LokiFsStructuredAdapter, I assume performance is a significant value to you so async should be employed wisely to eek out as much performance as possible.  [We do have a quickstart3 available which I would suggest looking into as the recommended practice](https://github.com/techfort/LokiJS/blob/master/examples/quickstart3.js).

To elaborate on your described use case above...  calling saveDatabase without a callback means you won't know when it completes.  You are relying on lokijs to avoid overlapping saves and loads.  LokiJS does in fact support the scenario you describe, with the ['throttledSaves'](https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters#save-throttling-and-persistence-contention-management) option on the Loki class being enabled by default.  A [bug was found and corrected](https://github.com/techfort/LokiJS/pull/643) in the 1.5.2 release surrounding overlapping saves.  If you have not upgraded, perhaps you should try >= 1.5.2 and let me know your results, otherwise perhaps we can recreate a simple test case and see if there is a real bug that needs to be fixed.

So now (having expressed that we want and expect LokiJS to handle the situation you have described), I would recommend that if you are doing manual saving, that you only save at the end of significant saves to avoid significant reliance of throttled saves.  Your initialization logic probably runs sub millisecond, whereas the disk I/O it induces... even if throttled to 2 saves (the initial and the last) take orders of magnitude higher time even with fresh/empty collections.  How large of a database are you dealing with?

**Comment by joshuaquek** [comment]
I built a library that might address this issue:

https://www.npmjs.com/package/lokijs-promise

Decided to build this as quite a lot of the issues that I found in the Issues section revolved around loading the persistent store (eg. `store.json`) and then ensuring that the store was loaded before doing inserts etc, which then automatically writes to the persistent store (eg. `store.json`)

**Comment by joshuaquek** [comment]
I built a library around LokiJs that might address this issue. You won't have to manually call db.saveDatabase() when you use this lib.

https://www.npmjs.com/package/lokijs-promise

Decided to build this as quite a lot of the issues that I found in the Issues section revolved around loading the persistent store (eg. `store.json`) and then ensuring that the store was loaded before doing inserts etc, which then automatically writes to the persistent store (eg. `store.json`)
