### ISSUE TITLE
Is it possible to initialize the database synchronous so that it waits until the database is initialized?

### ISSUE THREAD

**Issue by matmis** [techfort/LokiJS#656]
When I try this, `colSettings` is always null.
```
var loki = require('lokijs');
var db = new loki('settings/loki.json',{
    autoload: true,
    autosave: true, 
    serializationMethod: "pretty",
    autosaveInterval: 1000
});
databaseInitialize();

var colSettings;
function databaseInitialize() {
    colSettings = db.getCollection("Settings");
    if (colSettings === null){
         colSettings = db.addCollection("Settings");
    }
}
```

When use the option `autoloadCallback : databaseInitialize,` and I want to access `colSettings` at the beginning, it's empty because the callback has not run yet.

**Comment by Kanaye** [comment]
No it 's not possible to initialize the db synchronous.
Or to be precise: In theory someone *could* write a synchronous node fs adapter
but I recommend against it because this leads to unexpcected behaviour when someone swaps it out against an asychronous adapter.

I'd recommend to run your database depended code after loki has finished initializing.

**Comment by matmis** [comment]
Ok thanks!

**Comment by joshuaquek** [comment]
I quickly made a library that might address this issue:

https://www.npmjs.com/package/lokijs-promise
