### ISSUE TITLE
Simplesort with binary index improvements

### ISSUE THREAD

**Issue by Viatorus** [techfort/LokiJS#661]
@obeliskos 
I am currently try to port the newest changes of LokiJS V1 to V2.

I have some questions regarding the simplesort improvements (https://github.com/techfort/LokiJS/commit/4e28e8183aa1d2fa529e8d19a0a805923d11a650,  https://github.com/techfort/LokiJS/commit/82b5eb082e5786a8a3a6de52b197b97183101ecf, et sqq.)

1. Did you miss to add the field `a` to the binary indices of the collection?

https://github.com/techfort/LokiJS/blob/7702b06b9ed1bd0f72756e4de7bd949649254d5c/spec/generic/sortingIndexing.spec.js#L291-L294

2. DynamicView's simplesort uses compoundsort to sort the data.

https://github.com/techfort/LokiJS/blob/7702b06b9ed1bd0f72756e4de7bd949649254d5c/src/lokijs.js#L4100-L4103

https://github.com/techfort/LokiJS/blob/7702b06b9ed1bd0f72756e4de7bd949649254d5c/src/lokijs.js#L4418

Shouldn't compoundsort check also for the new option `{desc: true/false}`? 

https://github.com/techfort/LokiJS/blob/7702b06b9ed1bd0f72756e4de7bd949649254d5c/src/lokijs.js#L3140-L3146

3. CheckIndex has an unused variable `iter`. Should it be used in any way?

https://github.com/techfort/LokiJS/blob/7702b06b9ed1bd0f72756e4de7bd949649254d5c/src/lokijs.js#L5301-L5302

---

Still, thank you very much for your ongoing maintenance!

**Comment by obeliskos** [comment]
Thanks @Viatorus !  More validation of benefits that Typescript tooling and checking will benefit us with LokiJS2...

- randomSampling has been fixed so that it is actually not ignoring and doing full scan anyways
- unit test has been fixed

As for simplesort in dynamic view, our internal typings were a bit convoluted but functionally correct.  I believe a have made changes which should maintain the same functional effect but allow better internal typing for LokiJS2...
- Instead of having a single internal representation for both compound sort and simple sort, there are now two... compound sort uses the same (awkward and possibly nested arrays) and simplesort now uses a simple object with propname and options.
- The reason this worked before my latest changes is that Resultset.prototype.compoundSort calls simplesort if only one item exists in criteria array.  
- So rather than load up the method interface of compound sort to accomodate new simplesort options, i decoupled them.
- Currently compound sort does not leverage binary indices, that internal call to simplesort was workaround in case there was only one (indexed) criteria.  If a user wants to leverage a binary index on a search criteria, they should go through simplesort.

Let me know if I missed anything or if other glaring internal type cleanup might be useful. I'm starting to familiarize myself more with Typescript so I may join you in LokiJS2 soon :)  Will take a while to absorb all your fine refactoring though :)
