### ISSUE TITLE
Ability to use custom sort order/collation in index?

### ISSUE THREAD

**Issue by adueck** [techfort/LokiJS#672]
I have been searching the documentation for this, but is there any way to apply a custom search order when making a binary index? 

I need to be able to do this because I want to do `$gte` queries on a database of words written in a rare language with a special alphabet. Is this possible with loki.js?

Can different locales be used for sorting and comparing strings, ie (this [ICU demo](https://ssl.icu-project.org/icu-bin/collation.html)) ?

**Comment by obeliskos** [comment]
Well I have started refactoring our binary indexes for LokiDB and it currently allows passing a custom comparator on construction so a more full implementation will be implemented there.

For LokiJS, while we do currently have references (on default export) to our internal comparison functions, but don't think you can overwrite them as you would just be updating the references on export.  You -can- currently pass a javascript filter function to a where() call but that is an array scan and does not leverage indexes.

I could look into wrapping those LokiJS comparison methods into an internal object and return that reference on our default export which should allow you to override that objects internal comparison functions, but that replaces comparisons -everywhere- (any normal comparisons would have to be in a separate loki db instance in which you did not override the comparisons).  I would also need to benchmark this to ensure it does not adversely affect performance.

**Comment by Viatorus** [comment]
LokiDB has a full-text search (like a binary index for words) which
supports any kind of characters.

>

**Comment by obeliskos** [comment]
Ok still sounds similar to how @Viatorus's fts works but you could make do with the workaround I described.

I already have this done but feel the need to point out / clear up a few things : 
- This setting would seem affect all loaded loki instances, all collections within loki db instances, and all binary indices contained within all collections within all loki db instances.   If this is a web page that probably means per page load... for node it will probably cache the 'required' object so maybe for lifetime of node.js process (until the executable closes and restarts).
- If you intend to support multiple languages/sort ordering, you will have to 'hot-swap' the comparators when switching between different languages/sorting and any inserts/updates/removes/finds on a collection should always be done with the same set of comparators.
- You should only override the Comparators (aeq/lt/gt) if you are using binary indices, otherwise you can just override LokiOps operators.
- If you only have one set of comparators (one language) you can just override it directly after require() or script loaded and leave in effect without changing again.

So, easy to shoot yourself in the foot... 

LokiDB will have more fine grained comparators.  Internally we will have 'loki' sorting and plain 'js' sorting (when strongly typed/typescript).  We will probably also let you pass in named set of comparator functions on construction and optionally specify one of them when creating a binary index.

**Comment by obeliskos** [comment]
Ok, I added a 'Compators' property on default export... you can override its 'aeq', 'lt', and 'gt' function properties to point to your versions.

I made a [Loki Sandbox gist](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/cd7c219e348780f294e23a2ac292e1f3/raw/643f292fefeb91b797addf5b7c2c83f6b12c544d/LokiJS%2520Comparators) example which just creates a sort function and then retrofits those three onto it.  You can replace the 'cmp' function anytime you want to hot-swap a new comparator... such as swapping the 1 and -1 (gt/lt) values to sort descending.

**Comment by adueck** [comment]
Wow, thanks for the quick help on this.

I also found out that there is already a JavaScript `localCompare()` method that allows you to pass in any locale/language and it seems to work great! See: [String.prototype.localeCompare()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare#Checking_for_support_for_locales_and_options_arguments) 

So this works perfectly when I replace the sort function with, 

```
var cmp = function(a, b) {
  return a.localeCompare(b, 'locale-HERE');
}
```

Thankfully the two languages I need to sort don't share any of the same characters and so the `localeCompare()` method works for comparing/sorting strings in both languages. No need for swapping back and forth for me.

**Comment by obeliskos** [comment]
Great all comparisons of all properties will go through that method now so if you query on data types other than string make sure to do type checking and provide alternate compare paths.

**Comment by adueck** [comment]
Thank you so much. 

> LokiDB will have more fine grained comparators. Internally we will probably have 'loki' sorting and plain 'js' sorting (when strongly typed/typescript). We will probably also **let you pass in named set of comparator functions on construction and optionally specify one of them when creating a binary index**.`

This will be fantastic when if fully implemented. I don't think there's any other JavaScript database out there that currently does this?

Also, one last little question... you mentioned:

> You should only override the Comparators (aeq/lt/gt) if you are using binary indices, otherwise you can just override LokiOps operators.

Can you explain what you mean by the *LokiOps operators* ?

**Comment by obeliskos** [comment]
LokiOps contains an unindexed implementation of all the operators you can use within find() queries.  

https://github.com/techfort/LokiJS/blob/00cc7352088d80da04bfb56ac7e020bf4f5d7cf3/src/lokijs.js#L384-L567

We expose LokiOps similarly to how we just added Comparators now... on the default export

https://github.com/techfort/LokiJS/blob/00cc7352088d80da04bfb56ac7e020bf4f5d7cf3/src/lokijs.js#L7327-L7342

If you have a binary index defined, some of those ops can use that instead of LokiOps for much faster filtering, those items are determined by this (internal only) map : 
https://github.com/techfort/LokiJS/blob/00cc7352088d80da04bfb56ac7e020bf4f5d7cf3/src/lokijs.js#L569-L582

If you only want to override the unindexed LokiOps implementations you could (for example) just override LokiOps.$gte and all unindexed finds will use your new function.

So to be clear, how many collections do you have, (roughly) how many objects within those collections, and have you or will you be using loki binary indices within collection(s) to do ranged filtering or sorting?

**Comment by adueck** [comment]
Thanks very much for the info. I wish I could give your repo 5 stars, not just one. 

I only have one collection to be queried. There are currently about 5000 objects, but it will grow to around 15,000. I was planning on using the binary indexes because I'm aiming for maximum speed. 

Along with the `$gte` I also have another feature to do fuzzy searching using `$regex` queries to correct common spelling mistakes. (Currently I am doing this with PouchDB using IndexedDB but is too slow for this, taking 4-5 seconds per `$regex` query on older phones). Does the loki binary index help the speed of `$regex` full-text queries much? Or is it more important with a `$gte` type query?

**Comment by adueck** [comment]
Thanks, I'm working on implementing it right now. Just one last question. Can the `find()`, `chain()` or, `where()` methods be used asynchronously, returning a promise? Or would we need to create our own promises from the synchronous functions?

**Comment by obeliskos** [comment]
LokiJS is synchronous (as you mentioned), dependency-free and ecma5 (been around for awhile), that's not likely to change, so no probably not.


We have not discussed this for LokiDB but feel free to open an issue there to request that... we might be able to 'promisify' a version of our chained data() calls although we don't have failed conditions in query chains.  Our persistence adapter api could probably benefit from this more.

**Comment by adueck** [comment]
So LokiOps are for unindexed filtering, and the `loki.Comparators` are for binary indexed (faster) filtering?

In the [gist you gave above](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/cd7c219e348780f294e23a2ac292e1f3/raw/643f292fefeb91b797addf5b7c2c83f6b12c544d/LokiJS%2520Comparators) you attached the $aeq, $gt, and $lt operators.

i.e. attaching the $gt operator

```
loki.Comparators.gt = function(a, b, eq) {
  	var result = cmp(a, b);
	switch(result) {
      case -1: return false;
      case 0: return eq?true:false;
      case 1: return true;
    }
}
```
If I want to use the `$gte` operator with my custom index then I don't need to expose or attach anything else? Because the `$gte` operator works with the `$gt` operator?

```
$gte: function (a, b) {
        return Comparators.gt(a, b, true);
      },
```

Am I able to use the $gte operator as well with a situation like the [gist you gave above](https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm#rawgist=https://gist.githubusercontent.com/obeliskos/cd7c219e348780f294e23a2ac292e1f3/raw/643f292fefeb91b797addf5b7c2c83f6b12c544d/LokiJS%2520Comparators)? 

Thanks for all your help and patience.
