### ISSUE TITLE
why is lokijs's source code not es2015+ style?

### ISSUE THREAD

**Issue by anlexN** [techfort/LokiJS#679]
i review lokijs source code from begining to end. that's all es5 style. it's boring and not simple. so it make me read very hard.

**Comment by obeliskos** [comment]
This project is shifting into maintenance mode where we focus mostly on bug fixes. 

The next version of LokiJS is called [LokiDB](https://github.com/LokiJS-Forge/LokiDB) which uses modern language constructs and toolchain.

**Comment by anlexN** [comment]
@obeliskos , 
1. why choose typescript? typescript is not javascript! i don't like typescript.
2. where is your LokiDB'S source code?
3. when is LokiDB's document completed?

**Comment by obeliskos** [comment]
LokiDB toolchain can output various levels of ecmascript (es6 by default) so that end users do not need to use typescript.  

I don't understand, are you saying you don't like anything that adds a type system and checking?  Plain es2015 might be good enough for small scripts and projects, but to implement larger projects like LokiDB, i would no longer attempt it without type system like typescript (or other).

LokiDB's source code is at the link I provided above : 
https://github.com/LokiJS-Forge/LokiDB

If you to see the 'typescript' source, start at : 
https://github.com/LokiJS-Forge/LokiDB/tree/master/packages/loki/src

If you want to see the (output) es6 source, start at : 
https://github.com/LokiJS-Forge/LokiDB/tree/master/dist/packages/loki

LokiDB is in beta and we have not yet determined a 'release' date.  Documentation is being worked on, you can look over the beta documentation at : 
https://lokijs-forge.github.io/LokiDB/api/index.html

**Comment by anlexN** [comment]
all in all, code base is typescript, i don't like typescript. Is because of your talent? or your team? why certainly typescript give you power? how much sure do you have? are you mater at ecmascript? how is your  larger project?

**Comment by Alex-Werner** [comment]
@anlexN I guess you could easilly fork it and made it in ES6 :) 
The beauty of MIT License

**Comment by obeliskos** [comment]
I think some of your comments may be lost in translation but i get that you do not like typescript :)

What benefit would we get from porting LokiJS to es6/es2015+ at this point in time?  The only use case i can think of is to 'promisifiy' our persistence adapters.  Existing features do not really need es6 language constructs and it is not enough benefit that people reading the source are not bored 😛 

As @Alex-Werner mentions, you could or maybe we could host another branch for the community to continue to expand lokijs.  Maybe we could even host it on our new LokiJS-Forge organization if enough community members would like to continue enhancing or porting existing LokiJS source.

**Comment by Viatorus** [comment]
I decided to use TypeScript for LokiDB because when I first contribute to
LokiJS it was so difficult to understand which internal relation between
classes, members and function exist. Changing something in a huge API
needes much more unit tests if it is not type safe.

An example: When obeliskos did some changes in LokiJS and I had port them
to LokiDB I found issues which were not covered with unit tests but the
type system "found them".

And TypeScript does not change the code that much at all and ES8 maybe has
an optional type system too.

**Comment by anlexN** [comment]
so bad, i give up loki. because typescript easily make me forget the beauty of pure ecmascript. also think more about differences between them.

**Comment by anlexN** [comment]
Do you know [Bruce Lee](https://en.wikipedia.org/wiki/Bruce_Lee) ? Be water, my friend. typescript is from javascript, have its own benefits, like you say, typing check. But can you understand the philosophy of javascript? surpass myself, evolve myself, open myselft. javascript can also do typing check, just you can't in javascript.
