### ISSUE TITLE
Question - LokiJS vs plain JSON file to object? (Node)

### ISSUE THREAD

**Issue by lethevimlet** [techfort/LokiJS#685]
Hi, in my search for a simple local JS database for a small project I came across with LokiJS, and a few questions arose.  These are a few kind questions to help others and maybe contribute to the future of LokiJS.

1. Aside from the search functions and the API resemblance to MongoDB, what advantages does LokiJS against a simple JSON file being parsed to an in-memory object? I can manipulate the object with less overhead and stringify it to a file when persistence is needed, and it has the same serialization limitations, size, I/O, etc so what are the advantages?

2. Looking at the stored JSON I can see "documents" are stored in an array, I believe a simple object with a unique key could speed initial load and get() times, since it will never have to reconstruct and iterate through the array, acting much like a HashMap. I'm sure LokiJS creates an in-memory index for the unique keys but isn't this approach more reasonable to avoid the initial load times and queries?  

```
"collections": {
  "myCollection" {
    "id1": { ... },
    "id2": { ... },
  }
}
```

3. How often should I split databases into multiple files, I know JSON files can reach 0.5 GB without a sweat but how well does LokiJS generate the initial indexing and save operations for big files?

4. How could I save big chunks of text? I know I could always store the files separately and their paths in the actual collection, but is there a kind of binary format like BSON?

Anyway, nice work with the project, keep it up ^_^

**Comment by obeliskos** [comment]
So obviously LokiJS is built around wrapping JSON entities and enhancing with features that make it more like a traditional database.

Considering [serialization](https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters), we support partitioning which reduces IO and overhead during serialization and deserialization.  Partitioning also helps mitigate the behavior JSON.stringify usually exhibits when serializing a single deeply heirarchical object... exponential memory overhead due to internal recursive string manipulation/concatenation.  

If you are using within nodejs environment, we have LokiFsStructuredAdapter which writes each object individually to disk after each object is serialized and does not buffer into single string, lowering memory pressure even further.

If you are serializing to memory only we also support loki constructor ['serializationMethod'](https://rawgit.com/techfort/LokiJS/master/jsdoc/Loki.html) of 'destructured' which will serialize each object separately.  In [LokiDB (next gen lokijs)](https://github.com/LokiJS-Forge/LokiDB) we will probably update adapter model to support generator/iterator modes similar to that used in LokiFsStructuredAdapter.

It is too late to change $loki index to hashmap for LokiJS as it would break compatibility.  We are looking into doing this for LokiDB as it is a bit faster and avoids having to 'optimize' internally by using data array positions.  The $loki index in LokiJS is a binary index though so its still pretty fast.

Size limits for each collection/database would vary depending on environment and adapter.  For 'basic' adapters which do not partition and do not use 'destructured' serialization method we just JSON.parse the object and graft data into new loki/collection prototype instances.  Other mechanisms have been described above.

Save big chunks of text?  Depending on how big, you may want to look into creating or modifying one of  our reference adapters (which are all dependency free), and pull in your own dependencies such as @Kanaye did with his [loki-msgpack-adapter](https://github.com/Kanaye/loki-msgpack-adapter).

**Comment by lethevimlet** [comment]
Nice, I find LokiFsStructuredAdapter approach very interesting and compelling over a basic JSON.stringify/write to file.

I'm glad object key as indexes are in consideration for next gen of LokiDB, as you point out current approach is more than fast enough for a small embeddable database. 

Finally, for the big chunks of text, a custom adapter sounds like a perfectly valid approach I'll give it a try, thanks for the response and once again, good job with LokiJS, and LokiDB.
