### ISSUE TITLE
Bug in Collection.removeDynamicView

### ISSUE THREAD

**Issue by michael-felden** [techfort/LokiJS#694]
This function should remove every DynamicView from a Collection with a given name. 
It does not.
As an example suppose you have ten views with the same name in a collection.
removeDynamicView will remove only five.

The cause is the structure of the loop:

    Collection.prototype.removeDynamicView = function (name) {
      for (var idx = 0; idx < this.DynamicViews.length; idx++) {
        if (this.DynamicViews[idx].name === name) {
          this.DynamicViews.splice(idx, 1);
        }
      }
    };

While the array DynamicViews is shortened the index idx increments.
The array tail moves to the beginning and the index steps over it.

A simple example step by step:

remove   items called "view"

views = [view, view]
idx = 0, length = 2
found view at 0, remove it,   increment idx
 
views = [view]
idx = 1, length = 1
! idx < length hence   terminate loop
 
Half of the items still there

**Comment by obeliskos** [comment]
I agree that code looks problematic... we should either reverse iterate or use filter.... filter would probably be cleaner.

If you would like to submit a pull request, feel free to do so otherwise I will try to get to this sometime in the next week.

**Comment by michael-felden** [comment]
Thank you, but for now only bug reporting

**Comment by obeliskos** [comment]
Well upon implementing this fix I realized that it would probably be a good idea not to let you add multiple dynamic views with the same name in the first place.   

For now i have just reworked the iterator in removeDynamicView (in 04910ca). I did not add 'duplicate dynamic view' test coverage since I am not sure if we will eventually change that.  Do you have a use case where it might be useful to have duplicate dynamic view names?  Since our getDynamicView() lookup method will only return the first view with that name, anyone utilizing this must be accessing internal array.

**Comment by michael-felden** [comment]
Discovered the bug while testing. Duplicate names were not intentional.

Since the name is the key, I guess you would expect uniqueness.

**Comment by obeliskos** [comment]
We should probably keep this open to not allow dups
