### ISSUE TITLE
refresh page when lokijs autosaving database, the indexeddb is damaged

### ISSUE THREAD

**Issue by aokaywe** [techfort/LokiJS#713]
1. set loki autosave
2. refresh page when saving 
3. the database damaged
![image](https://user-images.githubusercontent.com/19823829/46254022-76735b00-c4bb-11e8-9767-949d29c84645.png)
10 partitions in 'file_ff37f0cd_6904_41ed_bd4a_30488f94b92a.1', but only 'file_ff37f0cd_6904_41ed_bd4a_30488f94b92a.1.0' and 'file_ff37f0cd_6904_41ed_bd4a_30488f94b92a.1.1' in database.

**Comment by aokaywe** [comment]
I add some code in here.
![image](https://user-images.githubusercontent.com/19823829/46255092-b04c5d80-c4cb-11e8-8233-36df86affe71.png)

**Comment by obeliskos** [comment]
IndexedDb provides a transaction around the saving of a record.  

If you use the indexeddb adapter without partitioning, the entire save is wrapped in a transaction.  If this save is interrupted, the previous value of the save will be reverted to.

If you use indexdb adapter with partitioning only (no paging), each collection save is wrapped in a transaction.  If this save is interrupted, that collection's save file will be reverted to the previous value.

If you use indexeddb adapter with partitioning + paging, only each page save is wrapped in a transaction.  This is very brittle if you expect the process to fail frequently.  Paging was only added because Chrome seemed to have a limitation of 25 or so megs for an individual 'record'.  

It may be possible at some point to modify our adapter interface so that paging is supported within a single transaction, but for now i would recommend it only for large internal databases where the user is aware of the sensitivity of the save and perhaps initiated it themselves.

I also would have to do some testing to verify whether Chrome's limitation of 25 or so megs was per record or per transaction, if per transaction then wrapping all pages within a transaction would encounter the same limit.

**Comment by aokaywe** [comment]
@obeliskos thank you .
