### ISSUE TITLE
Idea: Setting to throw error on full collection scan?

### ISSUE THREAD

**Issue by aguynamedben** [techfort/LokiJS#734]
Hi, we're evaluating LokiJS as an alternative to managing our own in-memory b-trees. Our app is latency-intensive (i.e. we always want really fast results). We're impressed with LokiJS so far, thanks for the work you put into making this an open project.

I have an idea I wanted to ask about. It'd be interesting if I could configure my LokiJS database (or query) with a setting called `throwOnFullScan`. Most databases will **always** try to answer the question posed to therm, even if it means doing a full scan of the collection. Because LokiJS is a very fast, in-memory database, it'd be interesting I could instruct LokiJS to throw an error if a query was not able to use indexes sufficiently.

This mode would prevent developers on my project (ahem, me!) from accidentally writing suboptimal queries. For my project, if a query is not using an index there is probably an oversight somewhere!

Is that a valid idea? Have you ever heard of such a feature?

Thanks again for this great project. 🙏

**Comment by obeliskos** [comment]
I had toyed with the idea of predetermining a sort of "query plan" and possibly optimizer but that is beyond the scope of maintenance changes we are prepared to make on LokiJS.  In theory would look into this for LokiDB.

So in theory we might be able to scan a query object and determine that several find filters are being executed in a certain order and some of the relevant properties have binary index defined but not the first and we might reorder those filters.  We might also take into consideration the number of rows in a collection and determined it is below a certain threshold not even bother optimizing.  

There may even be practical uses for "preparing" a query might take a query object, run some analysis on it to determine the 'best guess' optimization and return that for use in subsequent querying. 

In theory you might also add added internal timing and diagnostics and possible use that feedback and practical usage 'profiling' to allow Loki to experiment with real world query inputs.  Since your query object may have drastically different performance if your primary index filter sometimes eliminates 90% of results and sometimes 1%, another index (or rather the usual parameters passed to it) might consistently eliminate 65% of results, being better on average.

**Comment by aguynamedben** [comment]
Cool. Those are interesting ideas but I totally understand that they're not really necessary for the scope of LokiJS. We're no using LokiJS more heavily and the indexing works great, so as with any database, we just have to make sure we're don't run dumb queries.

Thanks again for the work you put into making LokiJS available.
