### ISSUE TITLE
JSON is apparently prone to corruption

### ISSUE THREAD

**Issue by NightYoshi370** [techfort/LokiJS#771]
So, I'm working on a Discord bot called Yamamura which will be using LokiJS to have user data. However, after talking with a few other programmer, I feel like I should ask you guys about a concern I've been having.

https://anidiots.guide/coding-guides/json-based-points-system

> The issue isn't with JSON. The issue is with fs. So really, this applies not just to JSON but also to TXT files or any other plain text file you're attempting to write to.
See here's the thing: If you're attempting to simultaneously read a file and write to it at the same time, or if you're writing to a file from more than one location, the file risks being corrupted. And the more this happens, the higher the chances. It might work for small bots, but as it grows you are going to lose that data.

After taking a look at LokiJS, it looks like it does use JSON. So I'm curious: does LokiJS use the fs module?

**Comment by IrosTheBeggar** [comment]
Just limit your program to read the file once on boot and lock your save function so it can't get called to run more than once at a time

**Comment by obeliskos** [comment]
The default persistence adapter when loki is run in a node environment is the LokiFsAdapter which uses "fs" module.

Since (by default) those methods are asynchronous (as is indexeddb), loki added a database level ["throttledSaves"](https://rawgit.com/techfort/LokiJS/master/jsdoc/Loki.html) option which loki uses for [save throttling and persistence contention management](https://github.com/techfort/LokiJS/wiki/LokiJS-persistence-and-adapters#save-throttling-and-persistence-contention-management)

By default, that throttledSaves option is set to true unless you explicitly disable it.

I think that covers the issue you are discussing?

**Comment by NightYoshi370** [comment]
Yes it does. Thank you for addressing my concern.
