### ISSUE TITLE
lokijs.org is down

### ISSUE THREAD

**Issue by yigitkonur** [techfort/LokiJS#804]
I would like inform you about the website (lokijs.org) is down.

**Comment by IvanFon** [comment]
Duplicate of: #797 

You can access the documentation at: https://rawgit.com/techfort/LokiJS/master/jsdoc/index.html

**Comment by marcellobarile** [comment]
https://rawgit.com/techfort/LokiJS/master/jsdoc/index.html gives 404

**Comment by IvanFon** [comment]
It’s been moved to: http://techfort.github.io/LokiJS/

**Comment by ericop** [comment]
Homepage needs to be updated on https://www.npmjs.com/package/lokijs as this is what lead me to the old site today as well

**Comment by mesqueeb** [comment]
I came here because I noticed the same. That new website points to the old website 😄

**Comment by muescha** [comment]
### lokijs.org

yes - lokijs.org is now filled with spam nonsense content :(

this pages need an update not to point to lokijs.org:
- at https://www.npmjs.com/package/lokijs
- at http://techfort.github.io/LokiJS/


### LokiSandbox

since rawgit is stop working in near feature the LokiSandbox @ https://rawgit.com/techfort/LokiJS/master/examples/sandbox/LokiSandbox.htm should be moved to github pages

**Comment by kaeverens** [comment]
https://github.com/techfort/LokiJS/wiki also points to lokijs.org

**Comment by rafalkrupinski** [comment]
Might I suggest js.org free domain name? Unfortunetaly loki.js.org is taken, but lokidb is available.

Cheers

**Comment by mesqueeb** [comment]
please don't close. this issue is still very relevant

**Comment by ericop** [comment]
agreed, this needs work.

**Comment by mesqueeb** [comment]
Oh dear!!! Issue still present

**Comment by muescha** [comment]
problem still exists

/cc @techfort ?

**Comment by finwo** [comment]
Problem was only partially fixed in #842
