### ISSUE TITLE
LoadDb On Demand

### ISSUE THREAD

**Issue by juniorschen** [techfort/LokiJS#846]
Hello, I have a problem where I have a database with several collections, but this database is growing too much, what happens is that my entire app depends on the database loading, but when loading the database it is taking too long, what would be the my best alternatives for this case?

![image](https://user-images.githubusercontent.com/46031261/85018772-1d8e9f00-b144-11ea-80f7-16e2e556e127.png)

**Comment by Bandito11** [comment]
This is the main weakness of this database, it is the same weakness as SQLite. It is made for small amounts of data. 

In your case scenario I would try to make an adapter that streams read the data instead of waiting for it to load synchronously but I don't know how you will be able to do this on NativeScript.

**Comment by juniorschen** [comment]
I started using Sq Lite and had better results, only when I will bring new data to my app do I miss out on the loki, because I need to make tratatives to insert in Sq Lite, but for my its not a problem
