### ISSUE TITLE
Question about changes API

### ISSUE THREAD

**Issue by c0bra** [techfort/LokiJS#94]
Is there a chance that a change could occur in-between serializeChanges and clearChanges?

If so could they both take a Date argument to avoid this? Or maybe I'm missing something?

**Comment by obeliskos** [comment]
This is mostly Techfort's area of expertise, so hopefully he will chime in.  

Looking at the code it seems both calls are synchronous... do you have pending insert/update/delete calls into loki which are async on your end?

**Comment by techfort** [comment]
Yep, confirming the synchronicity of those calls. Due to the
single-threaded nature of javascript if you generate your changes and then
call clearChanges nothing will happen in between.
clearChanges however is not called automatically (IIRC, i need to double
check this), so you will need to make that call yourself. I remember not
wanting to make the assumption that once generateChangesNotification is
completed you would want to wipe all the changes up to that point: it is a
very likely usage, but - for example - if you're transmitting that data
over a network I'd wait for a successful response before wiping the
changes, and you would not want to lose all the changes if the network
connection failed (then you'd find yourself with all the local changes lost
and your remote source not having received the changes up to that point).

If this is the kind of usage you're making of the changes api then yes - it
is possible a change will have occurred between the time you issue your
network request and the time you got a response. In that case you're going
to have to come up with an ad-hoc mechanism to manage that.

This case does bring up the issue of a transaction "lock" though. It would
probably be a nice feature to prevent "leaking" changes. If you have any
more details on the use case we can examine implementing a particular
safeguard / lock to avoid inconsistencies.

**Comment by c0bra** [comment]
Yea my use case would involve changes synchronization being done asynchronously, so I wouldn't be able to guarantee that changes could occur during the interim.

Specifically, I've just been brainstorming about syncing changes between devices on a LAN over WebRTC. This would probably be better accomplished when replication or the like is finished, but I was curious if there was anything already available that would allow for subsetting changes based on a timestamp.

**Comment by techfort** [comment]
Actually I've been cooking in my mind a similar idea recently. Basically, changes are creating clones of objects, and i was thinking of wrapping the changes into a collection. Because lokijs objects have timestamps (creation, update), you could then create resultsets or dynamicviews on those. At that stage all your application would need to do is keep track of the last time you queried for changes. Does that sound like it would resolve your problem?

**Comment by c0bra** [comment]
@techfort changes are full clones, and not diffs? I guess in that case it would be "last write wins"? Seems like it would work, more or less.

**Comment by techfort** [comment]
Yeah sounds right. Let me know if it does.
