### ISSUE TITLE
cryptedFileAdapter

### ISSUE THREAD

**Issue by seriousme** [techfort/LokiJS#96]
Hi,

I've been playing a bit with Loki and thought it would be fun to see if I could create an adapter for crypted file storage on Node.js

The first version was using Krypt (https://github.com/mmoulton/krypt/), but to reduce dependencies I added the relevant code to the adapter itself.

The result is at:
https://gist.github.com/seriousme/122684ca0396dbd6262f

The idea is that the secret comes from the user (e.g. in a nodeWebkit app)

If you have Krypt installed you can verify the result by running:
krypt --decrypt loki.json.crypted --secret mySecret

Cheers,
Hans

**Comment by techfort** [comment]
Hi Hans,

well that's just awesome, mighty kudos your way!

I would very much like to include this into the main repo, however I'd be
reluctant to do so because lokijs has no dependencies and i'd like to keep
it that way...

So maybe the best solution is for you to create a github repo for it and
I'll reference your project from Loki's README and in the official
documentation (and wherever else we talk about persistence), and by the way
I'm really curious to use it!
I think there are an infinite number of use cases for this.
all the best
joe

**Comment by seriousme** [comment]
Joe,

great to read you like it. I already read in the docs that you were proud on having no deps 
(thats why I cut Krypt out of the loop :-))
However the code uses no external dependencies. Crypto is part of the node core libs ( see https://nodejs.org/api/crypto.html#crypto_crypto ) just like "fs". 

As I did it just for fun and have no intent do long term maintenance I'd rather donate the thing to you.

Enjoy !

Hans

**Comment by techfort** [comment]
Well that's even better, sorry for not getting that you didn't use any
external deps.
If you want to submit a PR and get the credit for it, please do and I'll
merge it right away.
And thanks a lot for your great work, it's really appreciated. I hope Loki
made your life a bit easier in your projects.
joe

**Comment by obeliskos** [comment]
Very cool!

Since you mention node webkit, you could rename your global var to something other than 'crypto' since that is already defined in webkit as (web) crypto api.   

Yea do a pull request as @techfort  suggested if you want.

**Comment by seriousme** [comment]
Thx for the tip, I changed crypto to cryptLib
